hamming/src/test/java/HammingTest.java
For issue [#12 Make Hamming conform to official definition](https://github.com/exercism/xjava/issues/12).
The hamming distance is undefined for strings of different lengths, so throw an InvalidArgumentException if either strand is longer.
=> Change hamming test to throw an exception for different strand lengths

scrabble-score/src/test/java/ScrabbleScoreTest.java
multibillionaire can't be played as a word in a real scrabble game. See https://github.com/exercism/x-common/issues/86
=> scrabble-score: replace illegal word

simple-cipher/src/test/java/RandomKeyCipherTest.java
I changed the cipherKeysAreRandomlyGenerated test so that it does not compare the new Cipher to the length of the old Cipher.
=> Corrected error in RandonKeyCipherTest.java

crypto-square/src/example/java/Crypto.java, crypto-square/src/test/java/CryptoSquareTest.java
The existing tests were normalizing the strings based on the square size and not the actual sequence of characters from the columns.
You can refer to the source material where "If man was meant to stay on the 
ground god would have given us roots" should be "imtgdvs fearwer mayoogo anouuio ntnnlvt wttddes aohghn  sseoau" but were grouped by square size on the existing tests. This is a temporary fix until #55 uses the json file.
=> crypto-square: Fix invalid tests

.travis.yml
The dashes are optional, but we've been adding them to the other repositories.
=> Add yaml dashes to travis config for consistency

config.json, linked-list/build.gradle, linked-list/src/example/java/Deque.java, linked-list/src/example/java/Element.java, linked-list/src/test/java/DequeTest.java
The tests assume that the Deque class is implemented with generics.
The example implementation keeps track of a circular head Element.
Completes one task in https://github.com/exercism/xjava/issues/3.
=> Add linked-list exercise

exercises/build.gradle, exercises/grade-school/build.gradle, exercises/grade-school/src/example/java/io/exercism/xjava/NotReady.java, exercises/grade-school/src/test/java/SchoolTest.java
Introduce a new JUnit test category that lets us mark certain tests as
not ready for execution. The test task in the individual project
can then be configured to not run tests marked as `NotReady`.
For the CI server builds, add a fullTest test task that simply runs
tests as normal, and link it into the check task so it runs on builds.
This is not perfect, as the class under test must still compile, so it
must have at least the correct signatures of all the methods tested.
Also, it may be worth finding a way to distribute the NotReady interface
that doesn't require checking it into every project.
This will fix #101.
=> Initial POC of how to ignore all-but-first test

exercises/meetup/build.gradle, exercises/meetup/src/example/java/Meetup.java, exercises/meetup/src/test/java/MeetupTest.java
As of Java 8, the DateTime libraries have become more usable and less bizarre.
This PR replaces the Joda dependency from the meetup exercise with references to the standard library, as discussed in #116.
=> Replace JodaTime in Meetup with standard lib

exercises/etl/src/test/java/EtlTest.java
As described in issue #168, I removed the dependency from Guava library in order to use `Collections.unmodifiableMap` from the standard library. The last test case is longer than before, but at least now all the test cases are written coherently and so they are easier to understand.
Also, I noticed that this exercise was using the Guava assertions `assertJ`. So I removed it and used the standard `assertEquals` from JUnit (though, I could have used the Hamcrest library for the `assertThat`, or the `assertThat` from JUnit + a matcher from Hamcrest. Let me know if you prefer that way for the assertion instead of the standard assertEqual).
=> Remove Guava and use JUnit assert

config.json, exercises/all-your-base/build.gradle, exercises/all-your-base/src/example/java/BaseConverter.java, exercises/all-your-base/src/main/java/BaseConverter.java, exercises/all-your-base/src/test/java/BaseConverterTest.java, exercises/settings.gradle
Canonical data [here](https://github.com/exercism/x-common/blob/master/exercises/all-your-base/canonical-data.json).
The test `both bases are negative` was skipped as it is redundant given the structure of this implementation.
The canonical data also poses some questions for implementors, which I answered as follows:
> What's the canonical representation of zero?
`[0]`
> What representations of zero are allowed?
`[0]`
> Are leading zeroes allowed?
No.
> How should invalid input be handled?
By throwing an exception with an appropriate message.
=> all-your-base: add to track

docs/INSTALLATION.md
Without this instruction, the system continues to use the default OpenJDK.  This is confusing since we instruct the practitioner to install Oracle's JDK.
=> Make Oracle JDK default for Debian distros

config.json
Upstream issue: https://github.com/exercism/x-common/issues/279
Per the policy discussion in that issue, I have not deleted the supporting files for the deprecated exercises.
It would be nice to perform this deprecation now to trim the work required in #142 and to streamline the track for newcomers ASAP!
=> Deprecate binary, hexadecimal, octal, trinary

exercises/etl/src/test/java/EtlTest.java
The JUnit API documents assertEquals as taking the expected argument
before the actual argument.  Failure to adhere to this can result in
very confusing test failure messages.
For example in testTransformOneValue 'old' contains 'A' and 'expected'
contains 'a'.  If the implementer does not lower-case the key, the
failure message is as follows if the argument order is
(actual, expected):
EtlTest > testTransformOneValue FAILED
java.lang.AssertionError: expected:<{A=1}> but was:<{a=1}>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:118)
at org.junit.Assert.assertEquals(Assert.java:144)
at EtlTest.testTransformOneValue(EtlTest.java:27)
This is very confusing as "was:<{a=1}>" is exactly what we were hoping …
=> Invoke JUnit assertEquals with Argument Order (expected, actual)

exercises/grade-school/build.gradle, exercises/grade-school/src/test/java/SchoolTest.java
This is to allow a broad range of implementations. Currently, users must return the type HashMap<Integer, List<String> to pass this test. 
The updated test will check the order of any Map that maps Collections as value types. This opens the doors for more types of solutions.
=> Issue #253: Make the sort test more generic. 

exercises/hello-world/src/test/java/HelloWorldTest.java
Hello World was not supposed to be tricky, but I think I've found an uncovered case.
In some solutions people were using `name == ""` to check for empty string, as opposed to `name.equals("")`. The `==` operator in java compares object references, not values. Currently the tests pass in such case, but it's only a coincidence, since they compare to the same instance of the String constant `""` in JVM's constant pool. For newcomers, it could be a dangerous misconception. This change avoids it.
It's my first PR, so any feedback and guidance is welcome.
I've also considered making a separate test case instead of changing current one, to clarify the problem. Do you think that would be better?
=> hello-world: Modify tests to reject `name == ""` comparison

exercises/nucleotide-count/src/test/java/NucleotideTest.java
=> Nucleotide-count: use JUnit's @Rule feature [Fix #264]

.travis.yml, bin/build-jq.sh
- we need version 1.5 and can't get it from the official repo.
- includes adjusting the PATH so that our tools (like jq) get
precedence.
=> Build jq from source.

exercises/acronym/src/test/java/AcronymTest.java
Test case with description **non-acronym all caps word** is missing. Same has been added to be in sync with canonical-data.json from x-common project.
=> acronym: update tests according to canonical data

exercises/perfect-numbers/src/example/java/NaturalNumber.java, exercises/perfect-numbers/src/test/java/NaturalNumberTest.java
perfect-numbers [now has canonical data](https://github.com/exercism/x-common/blob/19d0c7714ce664a1ad762af624c17f8e269fa8b2/exercises/perfect-numbers/canonical-data.json). This PR updates the xjava tests to match this new data. Note too the comment at the top of the file which specifies the version of the tests being implemented. Does this seem like a reasonable practice moving forward?
=> perfect-numbers: update to canonical tests v1.0.0

exercises/rna-transcription/src/example/java/RnaTranscription.java, exercises/rna-transcription/src/main/java/RnaTranscription.java, exercises/rna-transcription/src/test/java/RnaTranscriptionTest.java
Changed rna-transcription to have an object based implementation (see issue #177) and added starter implementation as it is currently the second exercise in the new ordering (see issue #178).
=> rna-transcription: make object-based and add starter implementation

exercises/grade-school/src/test/java/SchoolTest.java
Changed school object instantiation to be in a setUp method instead of the class body. And added import statement for @Before.
=> grade-school: remove potential test pollution [Fix #371]

exercises/twelve-days/src/example/java/TwelveDays.java, exercises/twelve-days/src/test/java/TwelveDaysTest.java
=> twelve-days: use instance methods [Fix #357]

exercises/prime-factors/src/example/java/PrimeFactorsCalculator.java, exercises/prime-factors/src/test/java/PrimeFactorsCalculatorTest.java
=> prime-factors: convert to use instance methods

exercises/pig-latin/src/example/java/PigLatinTranslator.java, exercises/pig-latin/src/test/java/PigLatinTranslatorTest.java
Closes #360.
If I understand correctly, this is now an example of a "Function Object" rather than a "Value Object"? Yay, functions as almost-first-class citizens.
=> pig-latin: convert to use instance methods

exercises/atbash-cipher/src/example/java/Atbash.java, exercises/atbash-cipher/src/test/java/AtbashTest.java
=> atbash-cipher: make class use instance method [Fix #366]

.github/stale.yml
Closes #411.
Initial configuration specifies that "first-timers only" and "policy" issues should be exempt from cleanup, and that issues with no activity in the last 60 days should have the (new) [stale label](https://github.com/exercism/xjava/labels/stale) applied. I _think_ the quoted string will work here!
Defaults for non-specified configuration can be found here:
https://github.com/probot/stale#usage
=> Add probot configuration file

scripts/prune-extra-keep-files.sh
**Goal**
Automate removal of extraneous `.keep` files (used to retain practitioner source directories in Git when no explicit `.java` starter files are provided).
**Usage**
From the root of the xjava repository, execute `./scripts/prune-extra-keep-files.sh`
=> Add script to prune extraneous .keep files

bin/journey-test.sh
- was: hand-rolling a version of Trackler based of master and then
applying changes from the PR/commit/local change to that trackler gem.
- now: using the exact tagged version of Trackler as the basis for the
hand-rolled gem.
This fixes the issue where a change make to Trackler's master is
incompatible with the current version of x-api.  In short, we were
building the Trackler gem wrong.
=> Base patched Trackler gem off actual version tag.

exercises/nth-prime/src/example/java/PrimeCalculator.java
nth-prime: simplify example implementation
=> Fixes #420

exercises/space-age/src/test/java/SpaceAgeTest.java
=> space-age: add hint to @Ignore annotations

exercises/sum-of-multiples/src/test/java/SumOfMultiplesTest.java
=> SumOfMultiples : add hint to @Ignore annotations

exercises/queen-attack/src/test/java/QueenAttackCalculatorTest.java
=> queen-attack: add hint to @Ignore annotations

exercises/largest-series-product/src/test/java/LargestSeriesProductCalculatorTest.java
=> largest-series-product: add hint to @Ignore annotations

.github/PULL_REQUEST_TEMPLATE.md, POLICIES.md
Closes #425.
I surveyed our policy label to seed this document, and also included a new PR template that links to the policy checklist (for ease of PR review).
Some of the relative links might not be quite right; it's hard to test that off-GitHub.
Feedback welcome!
=> Add central policies document

exercises/rna-transcription/src/example/java/RnaTranscription.java, exercises/rna-transcription/src/main/java/RnaTranscription.java, exercises/rna-transcription/src/test/java/RnaTranscriptionTest.java
Ref. #455 
Also renamed input string to `dnaStrand`
=> rna-transcription: rename "ofDna" with "transcribe"

exercises/simple-linked-list/src/test/java/SimpleLinkedListTest.java
Replace deprecated methods and ensure order of arguments is correct. Fixes issue #567.
---
=> simple-linked-list: fix array comparison in tests [Fix #567]

exercises/difference-of-squares/src/test/java/DifferenceOfSquaresCalculatorTest.java
The canonical test data of `difference-of-squares` has recently been [modified in x-common](https://github.com/exercism/x-common/pull/791). This pull request synchronizes the corresponding tests in the Java track with the generic data.
In short, the test inputs are changed to 1 and 5 and 10 for each of the three tested methods.
---
=> difference-of-squares: synchronize tests with x-common

exercises/linked-list/src/test/java/DoublyLinkedListTest.java
Per https://github.com/exercism/xjava/issues/230, this PR updates the `linked-list` exercise so that the test suite exercises the generic nature of implementations. Solutions were already required to be generic, so no change was necessary there.
---
=> linked-list: exercise generics via tests

config.json, exercises/ocr-numbers/src/example/java/OpticalCharacterReader.java
Closes #341.
@FridaTveit I think this could be a 7 or an 8 but it is definitely easier than `rectangles`, which involves searching a grid for rectangles of arbitrary sizes and is currently also rated a 7. That might need to bump to an 8 or 9. The main difference is that in `ocr-numbers` we have an input grid of known-ish size and we're comparing against known digit representations; in `rectangles` we have arbitrarily-sized input (IIRC) and arbitrarily-sized rectangles.
---
=> ocr-numbers: estimate difficulty, position

exercises/isogram/HINT.md
Fixes issue #629. Setting an environment variable fixed the problem for me so I thought it was worth documenting this in a HINT.md file in case anyone else has this problem.
---
=> isogram: add hint for german umlauts encoding

bin/unit-tests.sh
~~**Includes #599, do not merge before that**~~
Adds `--parallel` flag to Gradle invocation used to run unit tests. Results in a ~2x speed increase for that portion of the build.
Before:
After:
---
=> Parallelize unit tests

exercises/acronym/src/main/java/Acronym.java, exercises/all-your-base/src/main/java/BaseConverter.java, exercises/bracket-push/src/main/java/BracketChecker.java, exercises/change/src/main/java/ChangeCalculator.java, exercises/diamond/src/main/java/DiamondPrinter.java, exercises/flatten-array/src/main/java/Flattener.java, exercises/luhn/src/main/java/LuhnValidator.java, exercises/minesweeper/src/main/java/MinesweeperBoard.java, exercises/ocr-numbers/src/main/java/OpticalCharacterReader.java, exercises/perfect-numbers/src/main/java/NaturalNumber.java, exercises/queen-attack/src/main/java/BoardCoordinate.java, exercises/queen-attack/src/main/java/QueenAttackCalculator.java, exercises/rectangles/src/main/java/RectangleCounter.java, exercises/robot-simulator/src/main/java/GridPosition.java, exercises/robot-simulator/src/main/java/Robot.java, exercises/saddle-points/src/main/java/Matrix.java, exercises/saddle-points/src/main/java/MatrixCoordinate.java, exercises/scrabble-score/src/main/java/Scrabble.java, exercises/secret-handshake/src/main/java/HandshakeCalculator.java, exercises/sublist/src/main/java/RelationshipComputer.java, exercises/wordy/src/main/java/WordProblemSolver.java
Here's some work toward #642. Wasn't sure whether you wanted `final` removed from the `example` implementations also so I didn't do that yet, but I will gladly zip through those ones too if you want.
---
=> Removing final from starter classes

exercises/all-your-base/src/test/java/BaseConverterTest.java
Closes #519.
[v1.1.0 of the tests](https://github.com/exercism/x-common/blob/c4d8d95bf53112d0dc39f6d66956b1c983d5fea3/exercises/all-your-base/canonical-data.json).
I chose to skip the x-common test case "both bases are negative" since
the xjava implementation of this exercise forces the first base to be
validated before a second base can be supplied. This test would
therefore be redundant since we already have tests that validate the
first base.
---
=> all-your-base: update to v1.1.0 of tests

docs/MAINTAINING.md
https://github.com/exercism/todo 404's now.
---
=> Remove link to dead todo repository

exercises/all-your-base/src/test/java/BaseConverterTest.java, exercises/change/src/test/java/ChangeCalculatorTest.java, exercises/hamming/HINTS.md, exercises/largest-series-product/src/test/java/LargestSeriesProductCalculatorTest.java, exercises/nth-prime/src/test/java/PrimeCalculatorTest.java, exercises/nucleotide-count/src/test/java/NucleotideTest.java, exercises/ocr-numbers/src/test/java/OpticalCharacterReaderTest.java, exercises/pascals-triangle/src/test/java/PascalsTriangleGeneratorTest.java, exercises/perfect-numbers/src/test/java/NaturalNumberTest.java, exercises/queen-attack/src/test/java/QueenAttackCalculatorTest.java, exercises/series/src/test/java/SeriesTest.java, exercises/simple-linked-list/src/test/java/SimpleLinkedListTest.java, exercises/triangle/src/test/java/TriangleTest.java, exercises/wordy/src/test/java/WordProblemSolverTest.java
=> Clean up exception-related hints

POLICIES.md, exercises/binary-search-tree/src/test/java/BSTTest.java, exercises/custom-set/src/test/java/CustomSetTest.java, exercises/palindrome-products/src/test/java/PalindromeCalculatorTest.java, exercises/poker/src/test/java/PokerTest.java, exercises/pythagorean-triplet/src/test/java/PythagoreanTripletTest.java, exercises/series/src/test/java/SeriesTest.java, exercises/sum-of-multiples/src/test/java/SumOfMultiplesTest.java, exercises/transpose/src/test/java/TransposeTest.java, exercises/two-fer/src/test/java/TwoferTest.java
A user accidentally deleted the `@Test` annotation in an exercise where that annotation appeared first. This PR standardizes the order of annotations so that any `@Ignore` annotation appears before any `@Test` annotation.
---
=> Standardize order of test annotations

exercises/twelve-days/src/main/java/TwelveDays.java, exercises/twelve-days/src/test/java/TwelveDaysTest.java
As this is exercise 20, I only provided a stub for the verse method as it was the only method used in the first test case, and I commented out the two test cases that use the verses method.
Resolves #551 
---
=> twelve-days: create and validate starter implementation

bin/unit-tests.sh
We will be adding subcommands to configlet.
For now, we've released a version of configlet which handles both the
old command:
configlet path/to/track
as well as the new command:
configlet lint path/to/track
This will let us update all the travis files to include the
subcommand before we release the version of configlet that requires
the subcommand.
https://github.com/exercism/configlet/pull/23
=> Support a subcommand on configlet in CI

.travis.yml, bin/journey-test.sh, bin/unit-tests.sh
Reference #410 
This pull request attempts to optimize the speed of the travis build's some more.  Unit tests and journey tests are run on separate build nodes, this trims a few minutes.  In the journey test it now downloads everything in parallel to save some time. And then `gradle` builds now use `--configure-on-demand` and `bundle install` uses the `-j4` tag.
After this get's reviewed and it all looks good, I'll make a pull request to mirror the changes in the kotlin track.
---
=> Optimize CI Tests

CONTRIBUTING.md
I've restructured some things in the docs repository. This fixes the links to the content that moved.
=> Update links to reflect changes in the docs repository

CONTRIBUTING.md
I fixed the link path to end in "installation" instead of "installing"
---
=> Fix broken link - exercism.io: Installing Java

exercises/two-fer/src/test/java/TwoferTest.java
This should close #728 
I've added additional test (as discussed) somewhat specific to `java` track and put it in the end of the file  (even though this test doesn't present in [canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/two-fer/canonical-data.json) for this exercise)
---
=> [WIP] Adds additional test for two-fer exercise

exercises/word-count/src/example/java/WordCount.java, exercises/word-count/src/test/java/WordCountTest.java
Remove redundant generic type params in map initialization in WordCount and WordCountTest
---
=> Fixes #716 remove redundant type params

bin/run-journey-test-from-ci.sh
So I noticed that when trying to get files modified when running the journey-tests, the builds are not able to get the required information, so it continues and runs the entire journey-test suite. This pr is to figure out where the problem is, and fix it
---
=> Add echo's to run-journey-test-from-ci for debug info

docs/INSTALLATION.md, docs/TESTS.md
[Markdown syntax](https://daringfireball.net/projects/markdown/syntax#list) states code blocks should be double indented in order for the numbering in the lists to continue.
Seeing as how the Java Installation and Tests page had numbered lists that were broken. I opted to fix them. [The issue is discussed here for v2 of exercism](https://github.com/exercism/v2-feedback/issues/105). I am checking the v1 pages to see what are affected by this.
As you can see the current rendering of the Installation page has the numbering thrown off. This should fix that.
---
=> Double indent code blocks to resolve list numbering

CONTRIBUTING.md
Fixes #769 
The local setup requires jq & ruby to be installed. This should be mentioned in the CONTRIBUTING.md file to make it easier for folks to contribute in the future
Happy Hacktoberfest! 
---
=> Adding the prerequisites to the CONTRIBUTING.md file

config.json
added topics for the queen-attack problem
fixes #829
---
=> Update config.json 

exercises/binary-search-tree/src/test/java/BSTTest.java
- Always use angle brackets in BSTTest when constructing BST objects
---
=> BST: add angle brackets when calling constructor

config.json
=> Add topics to pascals-triangle

config.json
=> wordy: add topics for exercise to config.json per #850

exercises/list-ops/.meta/hints.md
=> list-ops: add hint of using static methods per #378

CONTRIBUTING.md
When adding new exercises myself and reviewing other people's PRs for adding new exercises, I've missed having a guide which explains specifically what you need to do on the Java track and has links to general information you need about adding an exercise. So I thought it could be useful to add that to our contributing guide :)
I've also added a link to the general contributing guide because I think that could also be useful. I know in the README we link to both, but there are places where we only link to the Java guide, in which case people might not find the general one.
Please let me know if anything I've said is wrong, not well put or insufficient :) And of course if I've made any spelling mistakes or other errors :)
---
[Track …
=> Add new exercise section to the contributing guide

exercises/binary-search-tree/.meta/src/reference/java/BinarySearchTree.java, exercises/binary-search-tree/src/test/java/BinarySearchTreeTest.java
=> Renamed classes and added @Before method to test class

exercises/saddle-points/.meta/src/reference/java/MatrixCoordinate.java, exercises/saddle-points/src/main/java/MatrixCoordinate.java
The saddle-points tests make it seem like you can use any kind of set for your output. However, if you use `TreeSet` then the tests will fail because `MatrixCoordinate` doesn't implement `Comparable`.
`MatrixCoordinate` does now implement `Comparable` to prevent this failure.
Another solution would be to make the tests enforce use of `HashSet` instead of `TreeSet`. I'd be happy to change to that solution if anyone thinks that's preferable :)
---
=> saddle-points: make MatrixCoordinate implement Comparable

exercises/robot-simulator/src/main/java/GridPosition.java
We recently improved the implementation of equals for `GridPosition` so that we could use `assertEquals` in the tests. However, we only changed the reference implementation, not the starter implementation. This changes the starter implementation to be the same as the reference implementation.
---
=> robot-simulator: improve equals for GridPosition

exercises/binary-search-tree/.meta/src/reference/java/BinarySearchTree.java, exercises/binary-search-tree/src/main/java/BinarySearchTree.java, exercises/binary-search-tree/src/test/java/BinarySearchTreeTest.java
Should hopefully fix the `binary-search-tree` part of issue #230.
Also swaps `expected` and `actual` around in the first test as they were, as far as I can tell, the wrong way around.
---
=> binary-search-tree: use generics

scripts/canonical_data_check.sh
Sample output:
```text
$ ./canonical_data_check.sh  -t .. -s ../../problem-specifications/
hello-world: needs update or version file (v1.0.0).
two-fer: needs update or version file (v1.1.0).
pangram: needs update (v1.1.0 -> v1.3.0).
hamming: needs update (v1.1.0 -> v2.0.1).
gigasecond: needs update or version file (v1.0.0).
space-age: needs update or version file (v1.0.0).
raindrops: needs update or version file (v1.0.0).
secret-handshake: needs update (v1.0.0 -> v1.1.0).
perfect-numbers: needs update (v1.0.0 -> v1.0.1).
sum-of-multiples: needs update or version file (v1.1.0).
luhn: needs update or version file (v1.0.0).
largest-series-product: needs update or version file (v1.0.0).
sieve: needs update or version file (v1.0.0).
rotational-cipher: needs update or version file (v1.1.0). …
```
=> Add script for checking for exercise updates

exercises/luhn/src/test/java/LuhnValidatorTest.java
Add additional luhn test for fuller coverage in the Java stream. This fixes #972.
---
=> Add additional luhn test for fuller coverage as in #972

POLICIES.md
POLICIES: update stub policy for nextercism
---
=> POLICIES: update stub policy for nextercism

exercises/clock/.meta/src/reference/java/Clock.java
Fixes #1043. I couldn't remove the public access modifiers on toString() or equals() because they were overridden methods. 
---
=> clock: make classes and methods package private in reference solution

bin/run-journey-test-from-ci.sh, exercises/build.gradle
I was curious if the CI also tried to run tests against build.gradle similar to how settings.gradle was having tests run against it if it was in the change set. It was fixed in #1064 for settings.gradle as a reference.
---
=> Ignore build.gradle when CI runs tests against changeset

exercises/reverse-string/src/main/java/ReverseString.java
[Tests](https://github.com/exercism/java/blob/master/exercises/reverse-string/src/test/java/ReverseStringTest.java) in `reverse-string` exercise require that the method `ReverseString#reverse` should have the following signature - `reserse(String)`
This PR modifies the exercise placeholder to fix this inconsistency
---
=> Change reverse method signature to follow test requirements

CONTRIBUTING.md, POLICIES.md, exercises/flatten-array/.meta/hints.md, exercises/flatten-array/README.md
As exercises with difficulty 5 are the first exercises without starter implementation, they should have a hints file explaining how to fix the compiler errors that occur when an exercise doesn't have any starter
implementation.
This should be detailed in the policies doc.
I thought I would add the file to only one exercise until it's been reviewed so that I don't have to make changes to lots of files :) After the contents of the file has been agreed I could add the other files, or we could open good first patch issues to add them.
Fixes issue #1075.
---
=> Add hints to exercises without starter implementation

exercises/pig-latin/.meta/hints.md, exercises/pig-latin/README.md
=> pig-latin: add hints about no starter implementation

config.json
Both exercises have concurrency as a topic so it makes sense for them to be grouped together. This will also mean that parallel-letter-frequency won't be encountered until later in the track. See issue #1075.
---
=> parallel-letter-frequency: unlock by bank account

exercises/two-fer/.meta/src/reference/java/Twofer.java, exercises/two-fer/src/main/java/Twofer.java
Classes and methods in reference and starter implementation are now package private as described in the policies doc.
Fix for issue #1108 
---
=> two-fer: make classes and methods package private

exercises/parallel-letter-frequency/.meta/HINTS.md, exercises/parallel-letter-frequency/README.md, exercises/parallel-letter-frequency/src/test/java/ParallelLetterFrequencyTest.java
Fixes #1104.
I have removed the two Strings called 'OdeAnDieFreude' and Wilhelmus. The test case for appending all three anthems has been removed, and in the comma test case, I have substituted 'StarSpangledBannner'.
---
=> parallel-letter-frequency: remove characters with accents / diacritics

.travis.yml
As mentioned in #1199, build as failing intermittently.
This PR adds a retry parameter to the `rvm install` line, which seems to be where about half the build failures come from. The others seem to come from a mix of timeouts from installing caching utils and broken connections.
I wasn't too sure if the retry parameter could be added to caching utils, and I wasn't too sure where this would go. Let me know about improving this PR if we think more problems can be fixed here, as I don't have much experience with Travis :slightly_smiling_face: 
---
=> add travis_retry param to rvm install

exercises/run-length-encoding/.meta/hints.md
Added new hints.md file copied from exercises/flatten-array/.meta/hints.md
and regenerated the README.md file using configlet. Fixes #1089
---
=> run-length-encoding: added hints about no starter implementation

exercises/atbash-cipher/.meta/hints.md
Added a hints.md file to the atbash-cipher exercise and generated
the README.md file again using configlet. Fixes #1098
---
=> atbash-cipher: added hints about no starter implementation

exercises/bracket-push/.meta/hints.md
Added a hints.md file to the bracket-push exercise and generated
the README.md file again using configlet. Fixes #1095
---
=> bracket-push: added hints about no starter implementation

config/exercise-readme-insert.md, config/exercise_readme.go.tmpl, exercises/all-your-base/README.md, exercises/alphametics/README.md, exercises/bank-account/README.md, exercises/custom-set/README.md, exercises/forth/README.md, exercises/list-ops/README.md, exercises/markdown/README.md, exercises/minesweeper/README.md, exercises/parallel-letter-frequency/README.md, exercises/rectangles/README.md, exercises/sublist/README.md, exercises/tournament/README.md, exercises/two-fer/README.md, exercises/word-search/README.md
Now that we're operating with a track-wide template for generating exercise
READMEs we no longer need a separate markdown document to use for hints
and instructions that apply to all the exercises in a track. These instructions
can be defined directly in the template.
The first commit regenerates the exercise READMEs to pick up tweaks to problem descriptions, which have been updated with various formatting changes, whitespace changes, and clarifications to the description.
That gives us a clean diff when inlining the template and regenerating.
Ref: https://github.com/exercism/meta/issues/94
=> Inline the exercise README insert

exercises/complex-numbers/src/test/java/ComplexNumberTest.java
Fix #1284 
I added a message to assertDoublesEqual to display which part of the complex number was being tested when the error occurred. The output produced is (assuming testing the real part of the number):
```java
java.lang.AssertionError: While testing real part of number, expected:<9.0> but was:<6.0>
```
I'm not sure if this is the best solution though, considering the tests that call assertDoublesEqual directly.
---
=> complex-numbers: improve error message for failing test

.github/PULL_REQUEST_TEMPLATE.md
Just noticed that in the PR template we still reference 'xjava' instead of 'java'.
I've swapped it to use the newer term, so first-time users aren't confused :slightly_smiling_face: 
---
=> remove reference to xjava

config.json
It was previously unlocked by rna-transcription which is not a core exercise.
Exercises must be unlocked by core exercises.
Fixes #1366.
---
=> protein-translation: update unlocked by

CONTRIBUTING.md, POLICIES.md
We have decided that every exercise with diffulty less than 3 should reference the hello world tutorial to make it easier for people to solve those exercises. This has now been added to our policies doc.
We also now reference those policies in the contributing doc in the section for adding new exercises.
See issue #1389 for discussion.
---
=> Add reference tutorial policy

exercises/rna-transcription/.meta/hints.md, exercises/rna-transcription/README.md
For issue #1414 "add reference to tutorial"
---
=> added hints.md to .meta

config.json
The first core exercise on the track should be auto-approved. This means that mentor approval isn't needed in order to move forward when the exercise has been completed.
Currently any hello-world exercises are auto-approved in the backend of v2 but this special handling might be removed later which is why this also needs to be set in config.json.
This fixes the last point in issue #1481.
---
=> hello-world: set auto-approve to true

config.json
Completely missed this in my review! From the look of #1481, it seems like the `config.json` should use `auto_approve` not `auto-approve` 🙂 
---
=> amend auto_approve for hello-world

bin/journey-test.sh, bin/run-journey-test-from-ci.sh
The exercism cli has been updated, therefore we need to change our build script so that it still works.
Problems we still need to fix:
- `exercism configure` can't be called without a token so I'm currently using my own token. We should find out what the standard procedure is for this, e.g. creating a token for the track or using some option that allows us not to use a token.
- I get the error `The base API URL 'http://localhost:9292' cannot be reached` even though xapi should be running. Apparently other tracks have had this issue as well.
- `exercism --config` doesn't appear to be a valid option anymore. I can't find the config file we were using so I'm hoping it's fine to not use it anymore?
See issue #1493 for details.
---
[Track …
=> Make journey-test up to date with exercism cli updates

exercises/matrix/src/main/java/Matrix.java
Fix #1495 by removing unused methods.
`getRowsCount`/`getColumnsCount` are neither tested nor defined in the reference implementation.
---
=> matrix: Remove unused methods in starter source

exercises/error-handling/src/main/java/ErrorHandling.java
Fix #1509   
I removed the ```UnsupportedOperationException``` from both ```handleErrorByThrowingAnyUncheckedException``` and ```handleErrorByThrowingAnyUncheckedExceptionWithDetailMessage```
---
=> error-handling: remove UnsupportedOperationException from starter implementation

exercises/gigasecond/.meta/src/reference/java/Gigasecond.java, exercises/gigasecond/src/main/java/Gigasecond.java, exercises/gigasecond/src/test/java/GigasecondTest.java
Hello,
with this PR I want to resolve the issue #1513. 
I'm renaiming the `getDate()` method in the [gigasecond](https://github.com/exercism/java/tree/master/exercises/gigasecond) exercise to `getDateTime()`.
---
=> Renames the getDate method in the gigasecond exercise to getDateTime

gradle/wrapper/gradle-wrapper.properties
Gradle 4.0.1 does not understand the new JDK versions (9 and beyond) well and build fails with an error (ex: Could not determine java version from '9.0.1')
---
=> update gradle to the latest release (v4.10.2)

exercises/two-fer/README.md
Updated two-fer readme according to https://github.com/exercism/problem-specifications/pull/1374
---
=> two-fer: updated readme

exercises/roman-numerals/src/test/java/RomanNumeralsTest.java
This pull request is to fix the Roman Numerals exercise test case for converting 3000 to MMM.  The current test case mistakenly reuses the test for converting 1024 to MXXIV.
---
=> Fix test3000ToRomanNumberMMM

POLICIES.md
Adds more explanation concerning the starter implementation policy
Closes #1669
---
=> POLICIES.md: update good first issue, starter impl

CONTRIBUTING.md, scripts/create_issues_versionchange_canonical.sh
Closes #1670
Suggested script using GitHub API to create new issue when difference between track exercise version file number and canonical data version number is detected.
I based the script on the [canonical data check script](scripts/canonical_data_check.sh).
I introduced a new label to filter for duplicates, `exercise version update`.
The script adds a generic title, body and labels.
For example:
Please have a look at the generic texts and fell free to add or remove information/wording (I'm not a native speaker of English, so I would be very glad for corrections :smile:). I tried to incorporate parts of texts that have been previously used.
The script may be tested with a private repository. For authentication you need to create a …
=> Create script for issue submission (canonical data version changes)

CONTRIBUTING.md, POLICIES.md, _template/src/main/java/StubTemplate.java
=> Create stub template, change POLICIES.md/CONTRIBUTING.md

CONTRIBUTING.md
Both `-s` and `--spec-path` arguments are specified in the canonical data check command, whereas only `-s` is supported.
---
=> Remove invalid --spec-path argument for data check

exercises/two-fer/src/test/java/TwoferTest.java
We decided in issue #1783 (and previously) that the empty string should not be treated as a special case like null. As such, I think we should have a test for it.
---
=> Explicitly test that the empty string is not treated specially in twofer

.gitignore, exercises/alphametics/src/test/java/AlphameticsTest.java, exercises/anagram/build.gradle, exercises/anagram/src/test/java/AnagramTest.java, exercises/circular-buffer/build.gradle, exercises/circular-buffer/src/test/java/CircularBufferTest.java, exercises/diamond/build.gradle, exercises/diamond/src/test/java/DiamondPrinterTest.java, exercises/grade-school/build.gradle, exercises/linked-list/build.gradle, exercises/linked-list/src/test/java/DoublyLinkedListTest.java, exercises/nth-prime/build.gradle, exercises/nth-prime/src/test/java/PrimeCalculatorTest.java, exercises/nucleotide-count/build.gradle, exercises/nucleotide-count/src/test/java/NucleotideCounterTest.java, exercises/proverb/build.gradle, exercises/proverb/src/test/java/ProverbTest.java, exercises/robot-name/build.gradle, exercises/robot-name/src/test/java/RobotTest.java, exercises/simple-linked-list/build.gradle, exercises/simple-linked-list/src/test/java/SimpleLinkedListTest.java
Per #1803, we have decided not to allow Hamcrest assertions. Fixes #1820.
---
=> Remove uses of Hamcrest assertions or migrate to AssertJ

exercises/rest-api/build.gradle, exercises/rest-api/src/test/java/RestApiTest.java
Updating to JUnit 4.13, adding AssertJ dependency.
Fixes the test imports so static imports are up top and the rest are sorted order.
---
=> Fix rest-api build.gradle and test import ordering.

exercises/build.gradle
This Pr addresses issue raised in  https://github.com/exercism/exercism/issues/5353
---
=> set default encoding for all problems to utf-8

exercises/practice/hangman/build.gradle, exercises/practice/rest-api/build.gradle
Fix the `build.gradle' of some exercises, moving from deprecated `compile` to `implementation` settings 
---
=> fix deprecated gradle configurations

exercises/practice/largest-series-product/src/test/java/LargestSeriesProductCalculatorTest.java
Since `calculateLargestProductForSeriesLength` return type is declared as long, I wonder if this side exercise is a good place to make students think about integer overflows?
---
=> Test for integer overflow

docs/INSTALLATION.md
Current instructions result in an error
`unknown command: cask not found`
This change seems to fix it.
---
=> Updated installation instructions for MacOS 

exercises/concept/annalyns-infiltration/.meta/config.json, exercises/concept/bird-watcher/.meta/config.json, exercises/concept/blackjack/.meta/config.json, exercises/concept/cars-assemble/.meta/config.json, exercises/concept/classes/.meta/config.json, exercises/concept/constructors/.meta/config.json, exercises/concept/inheritance/.meta/config.json, exercises/concept/interfaces/.meta/config.json, exercises/concept/lasagna/.meta/config.json, exercises/concept/log-levels/.meta/config.json, exercises/concept/squeaky-clean/.meta/config.json, exercises/concept/switch-statement/.meta/config.json, exercises/concept/ternary-operators/.meta/config.json
The authors and contributors of exercises are stored in an array of objects in the exercises' `.meta/config.json` files.
Each author/contributor used to have two properties: their GitHub username _and_ their Exercism username.
As we're only using the GitHub username, we're flattening the `authors` and `contributors` array to an array of strings representing the GitHub usernames.
We will update `configlet` to validate the new structure, so you might be seeing build failures once we've implemented this change. 
See https://github.com/exercism/docs/pull/90/files
We will automatically merge this PR immediately to be able to submit a different PR in which we'll add the authors/contributors for practice exercises.
https://github.com/exercism/v3-launch/issues/26
=> 🤖 Flatten authors and contributors in .meta/config.json files

exercises/practice/nucleotide-count/src/test/java/NucleotideCounterTest.java
Fix for #1843 referencing discussion in #1938 
Removed zero-width space from the end of `containsExactlyInAnyOrderEntriesOf` method.
U+200B	​	0xe2 0x80 0x8b	ZERO WIDTH SPACE
These zero-width space characters only seem to be a problem with IntelliJ. They are only visible in the hex view of the file.
---
=> Removed zero-width space characters from test methods

exercises/shared/.docs/tests.md
Move instructions about how to run tests from v2 path ( `java/docs/TESTS.md`) to v3 one (`java/exrcise/shared/.docs/tests.md`)
---
=> Fix #1956: move test instructions to v3

exercises/practice/secret-handshake/src/test/java/HandshakeCalculatorTest.java
Some solutions simply checked if the input is greater than 16 to reverse, thus wrongly reversing the sequence for numbers greater than 16 whose bit at position 4 is not set. These test cases enforce that solutions check the bit at position 4 explicitly.
---
=> Add more exhaustive tests for secret handshake

exercises/concept/elons-toy-car/.meta/config.json
The icon for this exercise is called `elons-toys`, see: https://raw.githubusercontent.com/exercism/website-icons/main/exercises/elons-toys.svg
=> Specify custom icon for elons-toy-car

exercises/practice/isbn-verifier/src/test/java/IsbnVerifierTest.java
The isbn verifier tests did not check for a valid isbn number padded with addition characters. Solutions were able to grab the valid isbn number from inside the string. This was allowing invalid string input with a valid isbn inside to pass. This test case resolves that issue.
---
=> Added more exhaustive test case for isbn verifier

exercises/concept/annalyns-infiltration/.meta/config.json, exercises/concept/bird-watcher/.meta/config.json, exercises/concept/blackjack/.meta/config.json, exercises/concept/cars-assemble/.meta/config.json, exercises/concept/elons-toy-car/.meta/config.json, exercises/concept/football-match-reports/.meta/config.json, exercises/concept/log-levels/.meta/config.json, exercises/concept/need-for-speed/.meta/config.json, exercises/concept/remote-control-competition/.meta/config.json, exercises/concept/salary-calculator/.meta/config.json, exercises/concept/squeaky-clean/.meta/config.json, exercises/concept/wizards-and-warriors/.meta/config.json, exercises/practice/bowling/.meta/config.json, exercises/practice/darts/.meta/config.json, exercises/practice/dnd-character/.meta/config.json, exercises/practice/flatten-array/.meta/config.json, exercises/practice/food-chain/.meta/config.json, exercises/practice/largest-series-product/.meta/config.json, exercises/practice/linked-list/.meta/config.json, exercises/practice/markdown/.meta/config.json, exercises/practice/minesweeper/.meta/config.json, exercises/practice/pig-latin/.meta/config.json, exercises/practice/resistor-color/.meta/config.json, exercises/practice/reverse-string/.meta/config.json, exercises/practice/twelve-days/.meta/config.json, exercises/practice/yacht/.meta/config.json
I copied the blurb text from the exercises these were forked from to replace the "TODO" text that was there. Most from csharp track, one from go. Don't know where the salary-calculator exercise came from so left it as a TODO.
---
=> replaced TODO with blurbs from exercises these were forked from.

exercises/practice/resistor-color/src/test/java/ResistorColorTest.java
a student was confused by the compiler warning and I think it is even displayed as error in the UI. So let's use `assertArrayEquals` instead of `assertEquals(Object[], Object[])` which is deprecated..
---
=> avoid deprecation warnings

config.json
Fixes config.json after latest configlet linting. See #1992
---
=> Mark unreachable concept exercises as wip

exercises/concept/salary-calculator/src/test/java/SalaryCalculatorTest.java
... by using a value that is actually above the threshold
Fixes #1989
---
=> Fix SalaryCalculatorTest.skippedAboveThreshold

exercises/practice/resistor-color-duo/src/test/java/ResistorColorDuoTest.java
Another AssertJ update.  This one for ResistorColorDuo.
Let me know if there's any issues with the formatting.  I'm using IntelliJ's defaults of 8 spaces for continuation indents, but have no issues changing it if you use another style here.
---
=> Updating ResistorColorDuo tests to use AssertJ

.github/workflows/gradle.yml
--info returns more helpful information than --stacktrace
---
=> Use info rather than stacktrace for gradle

concepts/basics/.meta/config.json, concepts/booleans/.meta/config.json, concepts/chars/.meta/config.json, concepts/classes/.meta/config.json, concepts/conditionals-if/.meta/config.json, concepts/constructors/.meta/config.json, concepts/inheritance/.meta/config.json, concepts/interfaces/.meta/config.json, concepts/numbers/.meta/config.json, concepts/strings/.meta/config.json, concepts/ternary-operators/.meta/config.json, exercises/concept/cars-assemble/.meta/config.json
Also fix the typo in one of the concept exercise blurbs
Fixes #1897 
---
=> Add blurbs for all concepts

exercises/practice/atbash-cipher/src/test/java/AtbashTest.java
Updating Atbash tests, converting junit assertions into AssertJ ones.
---
=> Converting Atbash tests to AssertJ

.appends/.github/labels.yml, .github/workflows/stale.yml
The workflow definition is pretty self-documenting, but the full documentation is here: https://github.com/actions/stale
This is setup to leave stale issues open (but tagged) but auto-close stale pull requests.
---
=> Add a workflow to automatically close stale PRs and comment / tag stale issues

exercises/concept/remote-control-competition/src/main/java/ProductionRemoteControlCar.java
The parameter for the `setNumberOfVictories()` method has an incorrect name in the exercise.
---
=> change parameter name to numberOfVictories

exercises/practice/hamming/src/test/java/HammingTest.java, exercises/practice/hangman/src/test/java/HangmanTest.java, exercises/practice/hello-world/src/test/java/GreeterTest.java, exercises/practice/hexadecimal/src/test/java/HexadecimalTest.java, exercises/practice/house/src/test/java/HouseTest.java, exercises/practice/isbn-verifier/src/test/java/IsbnVerifierTest.java, exercises/practice/isogram/src/test/java/IsogramCheckerTest.java, exercises/practice/kindergarten-garden/src/test/java/KindergartenGardenTest.java, exercises/practice/knapsack/.meta/src/reference/java/Knapsack.java, exercises/practice/knapsack/src/test/java/KnapsackTest.java
I saw someone else group their AssertJ conversions together and figured I'd start doing the same.
The tests have been converted from using JUnit's assertions to use AssertJ, cleaning up and inlining portions of the tests that make sense to do so.
I also updated the reference implementation for knapsack.  It needlessly specified ArrayList in its method signatures (instead of just List).  Switching to List let me clean up the tests a little more.
Exercises updated:
- hamming
- hangman
- hello-world
- hexadecimal
- house
- isbn-verifier
- isogram
- kindergarten-garden
- knapsack
---
=> Converting tests to AssertJ (exercises starting with H, I, K)

CONTRIBUTING.md
Link for the 'Exercism Contributing Guide' on the Overview
was broken. Fixed with the correct link.
Screenshots with the change:
Before ->
After ->
---
=> Fix Exercism Contributing Guide Link on CONTRIBUTING.md

concepts/arrays/about.md, concepts/arrays/introduction.md, exercises/concept/bird-watcher/.docs/introduction.md
In java, the class that contains static methods,
to manipulate arrays, is java.util.Arrays.
Corrected the instructions.
https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Arrays.html
---
=> Replaced the class name Array with Arrays

gradle/wrapper/gradle-wrapper.properties
This updates the Gradle wrapper to the latest version. This version supports Java 17 for local use when fetching from the Exercism command line client. The Java test runner for the web editor currently supports Java 17. This addresses issue #2034
---
=> Update gradle wrapper to latest release for local Java 17 support.

config.json
Issue #1867
Added prerequisites and practices from `reverse-string` to `resistor-color`.
Also updated the concept in `linked-list` from `generics` to `generic-types`, to conform with the `concepts` slug.
---
=> Added prerequisites up to Resistor Color

exercises/concept/wizards-and-warriors/src/test/java/FighterTest.java
An issue arose when mentoring the exercise, where the person doing it had `return String.format("Fighter is a Warrior");` in their Warrior class, and knew that it was wrong. The tests however passed this incorrect behaviour.
The test I have added ensures they call the override in the correct class - the base class. I believe they may need to Google to use something like `.getClass().getSimpleName()` to figure out the class name.
One more thing to consider is that they may implement the override in each class individually, which would still be wrong really. This is probably better left up to the mentor to guide them where they could improve, as it seems the simplest way of guiding them, and won't add any extra confusion. This test at least helps guide them in the right direction.
Apologies …
=> Add warriors and wizards test

exercises/practice/two-fer/src/test/java/TwoferTest.java
Based on the example in the README.md file, a blank string ("") should return "One for you, one for me". The test currently is looking for a blank response. Fixing the test to align with readme expectations of the problem. 
While in Java null != empty, the directions state they should both return "one for you, one for me"
Readme excerpt:
```Here are some examples:
|Name    |String to return
|:-------|:------------------
|Alice   |One for Alice, one for me.
|Bob     |One for Bob, one for me.
|        |One for you, one for me.
|Zaphod  |One for Zaphod, one for me.
```
---
=> fixed emptyStringIsNotTheSameAsNull test to align with instructions

exercises/concept/need-for-speed/.docs/instructions.md, exercises/concept/need-for-speed/.meta/src/reference/java/NeedForSpeed.java, exercises/concept/need-for-speed/src/main/java/NeedForSpeed.java, exercises/concept/need-for-speed/src/test/java/NeedForSpeedTest.java
This name change clarifies that the method is supposed to try and drive
the car around the track to see if it can finish the track before it
runs out of battery as opposed to exposing the state of the car and
directly calculating the remaining distance that that car can travel.
This can sometimes be confusing to those completing the exercise as to
whether to expose the state of the car or try to drive the car around
the track and see if it can make it. This clarifies that the latter
should be implemented
Co-authored-by: Erik Schierboom <erik_schierboom@hotmail.com>
=> `need-for-speed`: Change method `canFinishTrack` to `tryFinishTrack`

CONTRIBUTING.md, docs/INSTALLATION.md, docs/TESTS.md, exercises/practice/hello-world/.docs/instructions.append.md, exercises/shared/.docs/tests.md
Fixed link on Java track's INSTALLATION.MD for running the tests, was pointing to 404.
---
=> Updated link broken hyperlink to running the tests

exercises/concept/cars-assemble/src/main/java/CarsAssemble.java
It said AssemblyLine instead of CarsAssemble which caused unnecessary confusion.
---
=> Confusing Exception name

POLICIES.md, docs/TESTS.md, exercises/practice/armstrong-numbers/.docs/instructions.append.md, exercises/practice/leap/.docs/instructions.append.md, exercises/practice/rna-transcription/.docs/instructions.append.md, exercises/practice/two-fer/.docs/instructions.append.md, exercises/shared/.docs/tests.md
#2137 
-  When you click on this url [tutorial](https://github.com/exercism/java/blob/main/exercises/hello-world/TUTORIAL.md) you will receive a 404 not found
- Get the real path for the tutorial and substitute all the old ones for the real url tutorial.
---
=> Fixed the url 404 not found for tutorial.md and changed the name

exercises/practice/darts/src/test/java/DartsTest.java
There were two typos in the file. There were two instances where "Cirlce" was written as "Cirlce" at LINE 65 and at LINE 80. 
Just wanted to correct the typos.
Cheers.
---
=> Update DartsTest.java for typos Where "Circle" was written as "Cirlce"

.github/workflows/gradle.yml
The documentation for `setup-java` recommends moving away from 'adopt' which has been discontinued and to use 'temurin' instead:
> NOTE: Adopt OpenJDK got moved to Eclipse Temurin and won't be updated anymore. It is highly recommended to migrate workflows from adopt to temurin to keep receiving software and security updates. See more details in the [Good-bye AdoptOpenJDK post](https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/).
[Source](https://github.com/actions/setup-java).
Summary of changes:
* Use 'temurin' instead of 'adopt'
* Update to Java 17, which is the version of java the test runner uses
* Convert action versions to SHAs
cc @exercism/reviewers @exercism/java
=> Use 'temurin' instead of 'adopt' and update to java 17

.github/workflows/gradle.yml, .github/workflows/stale.yml
As per exercism guidelines on actions [GHA Best Practices: Pin actions to SHAs](https://exercism.org/docs/building/github/gha-best-practices#pin-actions-to-shas)
Commit references:
- [actions/setup-java@v3.4.1](https://github.com/actions/setup-java/releases/tag/v3.4.1)
- [actions/stale@v5.1.1](https://github.com/actions/stale/releases/tag/v5.1.1)
cc @exercism/reviewers
=> Pin actions to SHAs

exercises/practice/hello-world/.docs/instructions.append.md
I deleted lines 52 - 59 in [java/exercises/practice/hello-world/.docs](https://github.com/exercism/java/blob/9abbe2a744625d698691249714d992fbdc17662c/exercises/practice/hello-world/.docs/instructions.append.md?plain=1#L52-L59)
Thanks @andrerfcsantos for the issue assignment! Always happy to contribute to building Exercism. 
---
=> removed the reference to UnsupportedOperationException in instructions

exercises/concept/cars-assemble/src/test/java/CarsAssembleTest.java
I am creating this pull request as one of my students stumble upon a test case where it failed due to machine epsilon and in this pr, I have refactored the unit tests in a way that it ignores machine epsilon as i think it's too early to challenge students with this kind of errors and it was probably unintentional for this particular exercise.
While this issue can be avoided by calculating productionRatePerHour function as follows:
```defaultProductionRate  * speed * successRate(speed) ```
The issue can be reproduced by calculating productionRatePerHour function as follows which confuses students:
```defaultProductionRate * successRate(speed) * speed```
---
=> Numbers: Cars, Assemble! Refactored unit tests in a way that ignores machine epsilon

exercises/practice/affine-cipher/src/test/java/AffineCipherTest.java, exercises/practice/all-your-base/src/test/java/BaseConverterTest.java, exercises/practice/alphametics/src/test/java/AlphameticsTest.java, exercises/practice/bank-account/src/test/java/BankAccountTest.java, exercises/practice/binary-search/src/test/java/BinarySearchTest.java, exercises/practice/bowling/src/test/java/BowlingGameTest.java
Convert `assertThrows` to `assertThatExceptionOfType` in classes starting with 'A' and 'B'.
---
=> Convert exception assertions to AssertJ in classes starting with 'A' and 'B'.

exercises/practice/linked-list/src/main/java/DoublyLinkedList.java
See discussion on
https://github.com/exercism/java/issues/2133#issuecomment-1281543458
Original issue:
Right now for some exercises, a student is required to read the tests to know which functions they should implement. This is annoying, time consuming and might discourage people from doing the exercise entirely. We should provide stubs for all exercises. Stubs should provide the signature of functions and classes, just so the student is immediately ready to start writing the custom logic. This is an example of a stub, from the [Raindrops exercise](https://github.com/exercism/java/blob/main/exercises/practice/raindrops/src/main/java/RaindropConverter.java):
---
=> Doubly linked list

CONTRIBUTING.md, README.md, docs/TESTS.md, exercises/practice/hello-world/.docs/instructions.append.md, exercises/shared/.docs/tests.md
The Exerism Forum (https://forum.exercism.org/) has now made Gitter redundant.
We're directing everyone there.
---
=> Remove reference to Gitter

exercises/practice/satellite/src/main/java/Satellite.java, exercises/practice/series/src/main/java/Series.java, exercises/practice/sgf-parsing/src/main/java/SgfParsing.java, exercises/practice/simple-cipher/src/main/java/Cipher.java, exercises/practice/simple-linked-list/src/main/java/SimpleLinkedList.java, exercises/practice/spiral-matrix/src/main/java/SpiralMatrixBuilder.java, exercises/practice/sublist/src/main/java/RelationshipComputer.java, exercises/practice/tournament/src/main/java/Tournament.java, exercises/practice/transpose/src/main/java/Transpose.java, exercises/practice/two-bucket/src/main/java/TwoBucket.java
Related to #2133 
This PR adds stubs for practice exercises starting with letters S through to V. 
The following exercises have been omitted from this PR as they already have stubs defined:
- saddle-points - ([Matrix.java](https://github.com/exercism/java/blob/main/exercises/practice/saddle-points/src/main/java/Matrix.java))
- say - ([Say.java](https://github.com/exercism/java/blob/main/exercises/practice/say/src/main/java/Say.java))
- scrabble-score - ([Scrabble.java](https://github.com/exercism/java/blob/main/exercises/practice/scrabble-score/src/main/java/Scrabble.java))
- secret-handshake - ([HandshakeCalculator.java](https://github.com/exercism/java/blob/main/exercises/practice/secret-handshake/src/main/java/HandshakeCalculator.java))
- sieve - …
=> Add stubs to practice exercises S to V

bin/site-editor-check.sh, exercises/practice/allergies/.meta/config.json, exercises/practice/alphametics/.meta/config.json, exercises/practice/bank-account/.meta/config.json, exercises/practice/binary-search/.meta/config.json, exercises/practice/circular-buffer/.meta/config.json, exercises/practice/dominoes/.meta/config.json, exercises/practice/error-handling/.meta/config.json, exercises/practice/go-counting/.meta/config.json, exercises/practice/hangman/.meta/config.json, exercises/practice/kindergarten-garden/.meta/config.json, exercises/practice/meetup/.meta/config.json, exercises/practice/perfect-numbers/.meta/config.json, exercises/practice/rest-api/.meta/config.json, exercises/practice/robot-simulator/.meta/config.json, exercises/practice/saddle-points/.meta/config.json, exercises/practice/satellite/.meta/config.json, exercises/practice/sgf-parsing/.meta/config.json, exercises/practice/sublist/.meta/config.json, exercises/practice/tree-building/.meta/config.json, exercises/practice/triangle/.meta/config.json, exercises/practice/word-search/.meta/config.json, exercises/practice/yacht/.meta/config.json
As per discussion here: https://github.com/exercism/java/issues/2157#issuecomment-1295851262
There are some classes that are not visible in the online editor, making it hard to solve it and causing obscure compilation errors if the student re-declares the class.
PR content:
- extra files exposed as read-only via editor
- a script to check missing files
Further possible actions:
- include the script into CI workflow
- since the script is pretty generic already, it can probably be used in other tracks too after minimal modifictions
- check for orphan files in `config.json`
---
=> Expose all files in online editor

exercises/practice/markdown/src/test/java/MarkdownTest.java
related to #2147 
Importing AssertJ and changing all assertEquals to assertThat.
Example of Change:
assertEquals(expected, markdown.parse(input));
To
assertThat(markdown.parse(input)).isEqualTo(expected);
=> assertEquals converted to assertThat for MarkdownTest

exercises/practice/pig-latin/.approaches/charat-substring/content.md
Change 
```
The `translate()` method starts be defining 
```
to
```
The `translate()` method starts by defining 
```
I do this a lot and I usually catch it.
---
=> Pig Latin typo fix

exercises/practice/grains/.approaches/introduction.md
Fixed the wrong power of two that gives us 8.
https://exercism.org/tracks/java/exercises/grains/dig_deeper
---
=> Fix typo in the Dig Deeper text for Grains

exercises/concept/remote-control-competition/.docs/instructions.md, exercises/concept/remote-control-competition/src/test/java/RemoteControlCarTest.java
Issue #2164 points out that Remote Control Competition's instructions don't match its tests very well. This PR is an attempt to improve this.
Completing each instruction subsection now increases the number of passing tests, which wasn't given previously.
- I have not yet touched the tests themselves, as I feel this would be too big a change for a single (first) PR. Would you agree?
- **Update**: Since @SleeplessByte disagreed with this assessment, I have now introduced more tests that gradually guide the student to a complete solution. 
- The way I understand the [Updating the README](https://github.com/exercism/java/blob/6ef04c4cd2ab62bca7f8d821ff18c5e81390eedd/CONTRIBUTING.md#updating-the-readmes) section of the CONTRIBUTING.md, I should be running `configlet` to maintain README files. …
=> Improve instructions and tests for Remote Control Competition exercise

exercises/practice/largest-series-product/.docs/instructions.md, exercises/practice/largest-series-product/.docs/introduction.md, exercises/practice/largest-series-product/.meta/tests.toml, exercises/practice/largest-series-product/src/test/java/LargestSeriesProductCalculatorTest.java
The largest-series-product exercise has been overhauled as part of a project to make practice exercises more consistent and friendly.
For more context, please see the discussion in the forum, as well as the pull request that updated the exercise in the problem-specifications repository:
- https://forum.exercism.org/t/new-project-making-practice-exercises-more-consistent-and-human-across-exercism/3943
- https://github.com/exercism/problem-specifications/pull/2246 
Note that we have deprecated and removed two test cases that deal with the multiplicative identity (also referred to as an empty product). By doing this we were able to avoid talking about this at all, which makes this exercise much more approachable.
----
If you approve this pull request, I will eventually merge it. However, if …
=> Sync largest-series-product docs with problem-specifications

exercises/concept/remote-control-competition/.docs/instructions.md, exercises/concept/remote-control-competition/.meta/src/reference/java/TestTrack.java, exercises/concept/remote-control-competition/src/main/java/TestTrack.java
=> Change TestTrack.getRankedCars stub to take a list of cars, consistent with the unit tests

.github/workflows/gradle.yml, exercises/build.gradle, exercises/concept/calculator-conundrum/.meta/src/reference/java/IllegalOperationException.java, exercises/concept/calculator-conundrum/.meta/src/reference/java/SimpleOperation.java, exercises/concept/calculator-conundrum/src/main/java/SimpleOperation.java, exercises/concept/remote-control-competition/.meta/src/reference/java/ProductionRemoteControlCar.java, exercises/concept/wizards-and-warriors/.meta/src/reference/java/Fighter.java, exercises/practice/pythagorean-triplet/.meta/src/reference/java/PythagoreanTriplet.java, exercises/practice/sgf-parsing/.meta/src/reference/java/SgfParsing.java, exercises/settings.gradle
I was investigating why the bug in #2330 didn't cause a failure in CI, and apparently the exercises aren't tested at all due to an error in the test script!
```
>>> solve_all_exercises(exercism_exercises_dir="/home/runner/work/java/java/build/exercism")
+ solve_all_exercises /home/runner/work/java/java/build/exercism
+ local exercism_exercises_dir=/home/runner/work/java/java/build/exercism
+ echo '>>> solve_all_exercises(exercism_exercises_dir="/home/runner/work/java/java/build/exercism")'
++ pwd
+ local track_root=/home/runner/work/java/java
++ jq '.exercises[].slug + " "' --join-output
++ cat config.json
jq: error (at <stdin>:2069): Cannot index array with string "slug"
```
It appears there are multiple things wrong with this script:
- It ignores errors from commands in a pipe, causing …
=> Fix CI silently not running exercise tests

exercises/practice/linked-list/src/test/java/DoublyLinkedListTest.java
Add test cases validating popping & shifting from an already "emptied" linked list.
=> Add extra test cases to Linked List

config.json
Some exercises in `config.json` were referencing non-existing concepts in either their respective `practices` or `prerequisites` list.
---
=> Remove non-existing concepts from config.json

concepts/chars/introduction.md, concepts/interfaces/introduction.md, concepts/switch-statement/introduction.md, exercises/concept/annalyns-infiltration/.docs/introduction.md, exercises/concept/annalyns-infiltration/.docs/introduction.md.tpl, exercises/concept/bird-watcher/.docs/introduction.md, exercises/concept/bird-watcher/.docs/introduction.md.tpl, exercises/concept/blackjack/.docs/introduction.md, exercises/concept/blackjack/.docs/introduction.md.tpl, exercises/concept/cars-assemble/.docs/introduction.md, exercises/concept/cars-assemble/.docs/introduction.md.tpl, exercises/concept/elons-toy-car/.docs/introduction.md, exercises/concept/elons-toy-car/.docs/introduction.md.tpl, exercises/concept/football-match-reports/.docs/introduction.md, exercises/concept/football-match-reports/.docs/introduction.md.tpl, exercises/concept/karls-languages/.docs/introduction.md.tpl, exercises/concept/lasagna/.docs/introduction.md, exercises/concept/lasagna/.docs/introduction.md.tpl, exercises/concept/log-levels/.docs/introduction.md, exercises/concept/log-levels/.docs/introduction.md.tpl, exercises/concept/need-for-speed/.docs/introduction.md, exercises/concept/need-for-speed/.docs/introduction.md.tpl, exercises/concept/remote-control-competition/.docs/introduction.md, exercises/concept/remote-control-competition/.docs/introduction.md.tpl, exercises/concept/salary-calculator/.docs/introduction.md, exercises/concept/salary-calculator/.docs/introduction.md.tpl, exercises/concept/squeaky-clean/.docs/introduction.md, exercises/concept/squeaky-clean/.docs/introduction.md.tpl, exercises/concept/wizards-and-warriors/.docs/introduction.md, exercises/concept/wizards-and-warriors/.docs/introduction.md.tpl
This updates all concept exercises to use an `introduction.md.tpl` template file (as described in the [docs](https://exercism.org/docs/building/tracks/concept-exercises#h-file-docs-introduction-md-tpl)), since the introduction for each concept exercise typically contains an introduction to the concept it's trying to teach.
This PR is a good showcase of why this change is necessary: the diff of each `introduction.md` in _both the exercises and the concepts themselves_ shows that it's very easy for the two to diverge over time. Of course there might be reasons for concept exercise introductions to not include the concept's introduction verbatim, but judging by the current state at least it's a sane default. Plus, this makes diverging from re-using the concept introduction explicit per …
=> Use templates to generate concept exercise introductions

config.json
Both practice exercises have been deprecated in the problem specifications. I opened #2357 to get the replacement of `beer-song` added.
---
=> Deprecate `beer-song` and `diffie-hellman`

POLICIES.md
This updates POLICIES.md after the discussion in #2147. 
---
=> Update POLICIES.md on preferring AssertJ

exercises/practice/bank-account/.meta/src/reference/java/BankAccount.java, exercises/practice/bank-account/.meta/tests.toml, exercises/practice/bank-account/src/main/java/BankAccount.java, exercises/practice/bank-account/src/main/java/BankAccountActionInvalidException.java, exercises/practice/bank-account/src/test/java/BankAccountTest.java
=> Sync tests for practice exercise `bank-account`

exercises/concept/karls-languages/build.gradle, exercises/concept/karls-languages/src/test/java/LanguageListTest.java
This PR addresses karl's languages task on issue #2356 
---
=> Update karl's languages to use test runner v3 features

exercises/practice/error-handling/src/test/java/ErrorHandlingTest.java
The changes of this PR make the  `ErrorHandlingTest` exercise use AssertJ in the tests. 
This is related to #2147. As this is my first pull request for Exercism, I only changed the assertions for a single test case. If this merge request is fine, I'd like to also update the missing exercises as well.
---
=> Use AssertJ for exceptions

concepts/enums/.meta/config.json, concepts/enums/about.md, concepts/enums/introduction.md, concepts/enums/links.json, config.json, exercises/concept/logs-logs-logs/.docs/hints.md, exercises/concept/logs-logs-logs/.docs/instructions.md, exercises/concept/logs-logs-logs/.docs/introduction.md, exercises/concept/logs-logs-logs/.docs/introduction.md.tpl, exercises/concept/logs-logs-logs/.meta/config.json, exercises/concept/logs-logs-logs/.meta/design.md, exercises/concept/logs-logs-logs/.meta/src/reference/java/LogLevel.java, exercises/concept/logs-logs-logs/.meta/src/reference/java/LogLine.java, exercises/concept/logs-logs-logs/build.gradle, exercises/concept/logs-logs-logs/src/main/java/LogLevel.java, exercises/concept/logs-logs-logs/src/main/java/LogLine.java, exercises/concept/logs-logs-logs/src/test/java/LogsLogsLogsTest.java, exercises/settings.gradle
This adds a new concept `enums` and the corresponding concept exercise `logs-logs-logs`, forked from the C# track.
To do:
---
=> Add concept `enums` with concept exercise `logs-logs-logs`

exercises/practice/collatz-conjecture/src/test/java/CollatzCalculatorTest.java, exercises/practice/crypto-square/src/test/java/CryptoSquareTest.java, exercises/practice/darts/src/test/java/DartsTest.java, exercises/practice/difference-of-squares/src/test/java/DifferenceOfSquaresCalculatorTest.java, exercises/practice/diffie-hellman/src/test/java/DiffieHellmanTest.java, exercises/practice/dnd-character/src/test/java/DnDCharacterTest.java, exercises/practice/dominoes/src/test/java/DominoesTest.java, exercises/practice/protein-translation/src/test/java/ProteinTranslatorTest.java, exercises/practice/rotational-cipher/src/test/java/RotationalCipherTest.java
Hi @sanderploegsma, I have updated the following tests in this PR. Please review!
1. CollatzCalculatorTest.java
2. CryptoSquareTest.java
3. DartsTest.java
4. DifferenceOfSquaresCalculatorTest.java
5. DiffieHellmanTest.java
6. DnDCharacterTest.java
7. DominoesTest.java
8. ProteinTranslatorTest.java
9. RotationalCipherTest.java
---
=> Update tests to use assertj (#2147)

exercises/practice/complex-numbers/src/test/java/ComplexNumberTest.java, exercises/practice/etl/src/test/java/EtlTest.java, exercises/practice/flatten-array/src/test/java/FlattenerTest.java, exercises/practice/food-chain/src/test/java/FoodChainTest.java, exercises/practice/gigasecond/src/test/java/GigasecondTest.java, exercises/practice/go-counting/src/test/java/GoCountingTest.java, exercises/practice/grains/src/test/java/GrainsTest.java, exercises/practice/grep/src/test/java/GrepToolTest.java, exercises/practice/isbn-verifier/src/test/java/IsbnVerifierTest.java, exercises/practice/largest-series-product/src/test/java/LargestSeriesProductCalculatorTest.java, exercises/practice/matrix/src/test/java/MatrixTest.java, exercises/practice/meetup/src/test/java/MeetupTest.java, exercises/practice/micro-blog/src/test/java/MicroBlogTest.java, exercises/practice/minesweeper/src/test/java/MinesweeperBoardTest.java, exercises/practice/nucleotide-count/src/test/java/NucleotideCounterTest.java, exercises/practice/octal/src/test/java/OctalTest.java, exercises/practice/pascals-triangle/src/test/java/PascalsTriangleGeneratorTest.java, exercises/practice/perfect-numbers/src/test/java/NaturalNumberTest.java, exercises/practice/pig-latin/src/test/java/PigLatinTranslatorTest.java, exercises/practice/poker/src/test/java/PokerTest.java, exercises/practice/pov/src/test/java/PovTest.java, exercises/practice/prime-factors/src/test/java/PrimeFactorsCalculatorTest.java, exercises/practice/pythagorean-triplet/src/test/java/PythagoreanTripletTest.java
In this Pr, all the below tests have been updated to use assertj
1.  ComplexNumberTest.java
2. EtlTest.java
3. FlattenerTest.java
4. FoodChainTest.java
5. GigasecondTest.java
6. GoCountingTest.java
7. GrainsTest.java
8. GrepToolTest.java
9. IsbnVerifierTest.java
10. LargestSeriesProductCalculatorTest.java
11. MatrixTest.java
12. MeetupTest.java
13. MicroBlogTest.java
14. MinesweeperBoardTest.java
15. NucleotideCounterTest.java
16. OctalTest.java
17. PascalsTriangleGeneratorTest.java
18. NaturalNumberTest.java
19. PigLatinTranslatorTest.java
20. PokerTest.java
21. PovTest.java
22. PrimeFactorsCalculatorTest.java
23. PythagoreanTripletTest.java
---
=> Updates tests to use assertThat instead of assertEquals

exercises/practice/grade-school/src/test/java/SchoolTest.java, exercises/practice/tree-building/src/test/java/BuildTreeTest.java, exercises/practice/zipper/src/test/java/ZipperTest.java
This should make the remaining exercises (i.e., the non deprecated ones; see [here](https://github.com/exercism/java/issues/2147#issuecomment-1751319487)) use AssertJ. I believe that this PR closes the issue #2147.
---
=> Use AssertJ for the remaining exercises

exercises/practice/bottle-song/.meta/config.json, exercises/practice/high-scores/.meta/config.json, exercises/practice/meetup/.docs/instructions.md, exercises/practice/phone-number/.docs/instructions.md, exercises/practice/sgf-parsing/.docs/instructions.md
Updates outdated docs and filepaths on some exercises. See #2388
---
=> Sync practice exercise docs + filepaths

.github/workflows/gradle.yml
Currently the Gradle CI action is run twice for every push to every PR, one for the push event and another for the PR event. This changes the workflow to only run for push events to the `main` branch.
---
=> Remove duplicate Gradle workflows being triggered

exercises/practice/simple-cipher/src/test/java/SimpleCipherTest.java
As suggested in #2538, I refactored the exercise tests into a single class.
All the mehods with the same name have been renamed by prepending the name of the class they come from: for example, `RandomKeyCipher.cipherCanDecode` became `randomKeyCipherCanDecode`, and `SubstitutionCipher.cipherCanDecode` is now `subsitituonCipherCanDecode`.
---
=> Remove nested test classes from practice exercise simple-cipher (#2538)

docs/INSTALLATION.md
I updated the installation instructions to install the latest Java LTS version from OpenJDK.
For the most part, I replaces references to AdoptOpenJDK with Adoptium and/or Eclipse Temurin.
Fixes #2368 
---
=> Update installation instructions to install Java 21 (#2368)

.github/workflows/gradle.yml, .github/workflows/test.yml, bin/test-with-test-runner, exercises/practice/bowling/.meta/config.json, exercises/practice/error-handling/.meta/config.json, exercises/practice/forth/.meta/config.json, exercises/practice/hangman/.meta/config.json, exercises/practice/mazy-mice/.meta/src/reference/java/MazeGenerator.java, exercises/practice/mazy-mice/src/test/java/MazeGeneratorTest.java, exercises/practice/ocr-numbers/.meta/config.json, exercises/practice/poker/.meta/config.json, exercises/practice/queen-attack/.meta/config.json, exercises/practice/rest-api/.meta/config.json, exercises/practice/spiral-matrix/.meta/config.json, exercises/practice/tournament/.meta/config.json
Inspired by this forum topic: https://forum.exercism.org/t/re-using-the-test-runners-in-corresponding-track-ci-jobs/8070.
Note that this required some updates to some of the exercises, particularly ones where not all files that are part of the example solution were correctly listed in the exercise's `config.json`. 
The Mazy Mice exercise required a small change because of a compilation error due to a class being defined in both the example solution as well as the tests. Not sure why this wasn't caught when using the tests with Gradle. It shouldn't impact students though.
---
=> Run tests using java-test-runner

exercises/concept/salary-calculator/.docs/hints.md, exercises/concept/salary-calculator/.docs/instructions.md, exercises/concept/salary-calculator/.docs/introduction.md, exercises/concept/salary-calculator/.meta/config.json, exercises/concept/salary-calculator/.meta/design.md, exercises/concept/salary-calculator/.meta/src/reference/java/SalaryCalculator.java, exercises/concept/salary-calculator/src/main/java/SalaryCalculator.java, exercises/concept/salary-calculator/src/test/java/SalaryCalculatorTest.java
Closes #2573.
Wrote relevant test cases for task 1 and task 2 and removed some useless test cases for task 3 that tested implementation of the previous tasks and not only implementation of the task 3.
Updated the documentation for more clarity and readability and corrected some misspelled words. 
=> Add test cases for first two tasks in Salary Calculator

exercises/practice/linked-list/.meta/config.json, exercises/practice/linked-list/.meta/tests.toml, exercises/practice/linked-list/src/test/java/DoublyLinkedListTest.java
=> Sync tests for practice exercise `linked-list`

config.json
Some practice exercises were configured so that they would unlock before their corresponding concept exercises were finished, causing confusion with students who are trying to follow the learning path.
Example: https://forum.exercism.org/t/confused-by-concepts-exercises-and-learning-exercises/8330
Relates to #1867 and #1923
---
=> Fix existing prerequisites for practice exercises

config.json
This adds missing `practices`/`prerequisites` entries to the track configuration, so now all practice exercises should have at least something set. 
Note that the syllabus is still a bit messy, this is also because there are many concepts taught by these exercises that do not exist yet (dates, maps, sets, queues, stacks, randomness, optionals, trees, sorting just to name a few). I'm currently working on a list of concepts that IMO should be added to the track and I intend to open an issue for every concept to add.
@ErikSchierboom I was thinking of adding a pinned topic on the Java forum requesting feedback on the track's syllabus, would that be possible? That should then end up on the right column of the [track homepage](https://exercism.org/tracks/java), right?
Fixes #1867
Fixes #1923 …
=> Add missing prerequisites

concepts/inheritance/introduction.md, exercises/concept/wizards-and-warriors/.docs/hints.md, exercises/concept/wizards-and-warriors/.docs/introduction.md, exercises/concept/wizards-and-warriors/.meta/src/reference/java/Fighter.java
Closes #2561 
I checked and fixed some other typos too.
=> Fixed typos

exercises/concept/captains-log/.meta/config.json, exercises/concept/captains-log/.meta/src/reference/java/CaptainsLog.java, exercises/concept/captains-log/src/test/java/CaptainsLogTest.java
Changed the end index of the randomShipRegistryNumber() so that the range goes from 1000 to 9999
Fixes #2589 
---
=> Fix broken test in Captains Log

exercises/settings.gradle
Note: I explicitly commented the exercises in settings.gradle instead of removing them completely. The reasoning for this is mostly that this makes it explicit _why_ the exercises are not present in the Gradle project. Otherwise, someone might be tempted to add them back in the future.
---
=> Remove deprecated exercises from Gradle project

exercises/concept/booking-up-for-beauty/.docs/introduction.md
The issue addresses: [#2597](https://github.com/exercism/java/issues/2597)
The goal is to fix a typo in the introduction of the exercise Booking for beauty.
---
=> Fixing typo on the introduction of booking up for beauty exercise

exercises/practice/say/.meta/tests.toml, exercises/practice/say/src/test/java/SayTest.java
The goal is to sync the tests of the say practice exercise
=> Sync tests for practice exercise say

exercises/practice/resistor-color-duo/.meta/tests.toml, exercises/practice/resistor-color-duo/src/test/java/ResistorColorDuoTest.java
This issue addresses: [2388](https://github.com/exercism/java/issues/2388)
The goal is to sync the tests of the resistor color duo practice exercise
=> Sync tests for practice exercise ``resistor color duo``

exercises/practice/rectangles/.meta/tests.toml, exercises/practice/rectangles/src/test/java/RectangleCounterTest.java
The goal is to sync the tests of the rectangles practice exercise
=> Sync tests for practice exercise ``rectangles``

exercises/practice/phone-number/.meta/src/reference/java/PhoneNumber.java, exercises/practice/phone-number/.meta/tests.toml, exercises/practice/phone-number/src/test/java/PhoneNumberTest.java
The goal is to sync the tests of the phone number practice exercise
=> Sync tests for practice exercise ``phone number``

exercises/practice/markdown/.meta/src/reference/java/Markdown.java, exercises/practice/markdown/.meta/tests.toml, exercises/practice/markdown/src/main/java/Markdown.java, exercises/practice/markdown/src/test/java/MarkdownTest.java
The goal is to sync the tests of the markdown practice exercise
=> Sync tests for practice exercise ``markdown``

exercises/practice/protein-translation/.meta/src/reference/java/ProteinTranslator.java, exercises/practice/protein-translation/.meta/tests.toml, exercises/practice/protein-translation/src/test/java/ProteinTranslatorTest.java
The goal is to sync the tests of the phone number protein translation
=> Sync tests for practice exercise ``protein translation``

exercises/practice/triangle/.meta/tests.toml, exercises/practice/triangle/src/test/java/TriangleTest.java
This issue addresses: [#2388]( https://github.com/exercism/java/issues/2388)
The goal is to sync the tests of the triangle practice exercise
=> Sync tests for practice exercise ``triangle``

exercises/practice/pangram/.meta/tests.toml, exercises/practice/pangram/src/test/java/PangramCheckerTest.java
The goal is to sync the tests of the rational numbers practice exercise
=> Sync tests for practice exercise ``panagram``

exercises/practice/word-count/.meta/tests.toml, exercises/practice/word-count/src/test/java/WordCountTest.java
The goal is to sync the tests of the word count practice exercise
=> Sync tests from exercise ``word count``

exercises/practice/matching-brackets/.meta/tests.toml, exercises/practice/matching-brackets/src/test/java/BracketCheckerTest.java
The goal is to sync the tests of the matching brackets practice exercise
=> Sync tests from exercise ``matching brackets``

exercises/practice/word-search/.meta/tests.toml, exercises/practice/word-search/src/test/java/WordSearcherTest.java
The goal is to sync the tests of the word search practice exercise
=> Sync tests from exercise ``word search``

exercises/practice/yacht/.meta/tests.toml, exercises/practice/yacht/src/test/java/YachtTest.java
The goal is to sync the tests of the yacht practice exercise
=> Sync tests for practice exercise ``yacht``

exercises/practice/transpose/.meta/tests.toml, exercises/practice/transpose/src/test/java/TransposeTest.java
The goal is to sync the tests of the transpose practice exercise
=> Sync tests for practice exercise ``transpose``

config.json
Step one towards #2631. After merging this, the concept tree will only show the corresponding concept exercise for every concept, similar to the [Go](https://exercism.org/tracks/go/concepts) and [Swift](https://exercism.org/tracks/swift/concepts) tracks.
---
=> Remove practice exercises from concept tree

config.json
The order of the practice exercises on the website is determined by their ordering in `config.json`. This reorders the practice exercises so that less difficult exercises appear before harder exercises. Hopefully that should help students pick their next exercise based on their skill level.
Reordering was done using `jq`:
```sh
cat config.json | jq -r '.exercises.practice | sort_by(.difficulty, .slug)'
```
---
=> Order practice exercises by difficulty

exercises/practice/ledger/.meta/src/reference/java/Ledger.java, exercises/practice/ledger/.meta/tests.toml, exercises/practice/ledger/src/main/java/Ledger.java, exercises/practice/ledger/src/test/java/LedgerTest.java
The goal is to sync the tests of the ledger practice exercise
=> Sync tests for practice exercise ``ledger``

exercises/practice/series/.meta/src/reference/java/Series.java, exercises/practice/series/.meta/tests.toml, exercises/practice/series/src/test/java/SeriesTest.java
The goal is to sync the tests of the series practice exercise
=> Sync tests for practice exercise ``series``

exercises/practice/space-age/.meta/src/reference/java/SpaceAge.java, exercises/practice/space-age/.meta/tests.toml, exercises/practice/space-age/src/main/java/SpaceAge.java, exercises/practice/space-age/src/test/java/SpaceAgeTest.java
This one required a major reformat, due to tests passing a new parameter and also usage of a deprecated method ``setScale``
````
{
"uuid": "57b96e2a-1178-40b7-b34d-f3c9c34e4bf4",
"description": "invalid planet causes error",
"property": "age",
"input": {
"planet": "Sun",
"seconds": 680804807
},
"expected": {
"error": "not a planet"
}
}
````
I used as reference the ``go`` track that is updated.
=> Sync tests for practice exercise ``space age``

exercises/concept/secrets/.docs/instructions.md
Just some typos I've found while solving this exercise.
---
=> Typo on "Secrets" exercise 

README.md, config.json
- The representer was recently disabled because it kept crashing; this bug has been fixed here: https://github.com/exercism/java-representer/pull/82
- The analyzer is still in an early stage: it only has an implementation for the `hamming`, `leap` and `two-fer` exercises. However, due to a recent addition that provides some basic general feedback to _all_ exercises I think it makes sense to enable it. Especially since there are a lot of questions on Discord from people who are struggling with getting tests to pass because they are printing the answers instead of returning them (which is something the analyzer informs them of).
---
=> Enable representer and analyzer

exercises/concept/lasagna/.meta/design.md, exercises/practice/hamming/.meta/design.md, exercises/practice/leap/.meta/design.md, exercises/practice/two-fer/.meta/design.md
This adds the comments already implemented in the Java analyzer to the respective exercise's `.meta/design.md`.
Note that practice exercises generally don't have this file yet, as it is not required.
Still, I think it's good practice to record any major design decisions related to the exercise somewhere, so they might benefit from having one.
Fixes #2679
---
=> Add existing analyzer comments

.github/workflows/test.yml, concepts/chars/introduction.md, exercises/concept/squeaky-clean/.docs/hints.md, exercises/concept/squeaky-clean/.docs/instructions.md, exercises/concept/squeaky-clean/.docs/introduction.md, exercises/concept/squeaky-clean/.meta/config.json, exercises/concept/squeaky-clean/.meta/src/reference/java/SqueakyClean.java, exercises/concept/squeaky-clean/src/test/java/SqueakyCleanTest.java
Related issue: [#2049](https://github.com/exercism/java/issues/2049)
The goal of this PR is to update Squeaky clean to not ask the students to take into count control characters, unicode and greek letters.
=> Updating Squeaky Clean

exercises/concept/lasagna/.meta/design.md
Add missing celebratory comment.
Relates to #2679
---
=> lasagna: Update design.md

exercises/concept/bird-watcher/.meta/design.md, exercises/concept/bird-watcher/.meta/src/reference/java/BirdWatcher.java
Related issue: [#2670](https://github.com/exercism/java/issues/2670)
=> Adding analyzer feedback to design.md for bird watcher concept exercise

exercises/concept/log-levels/.meta/design.md
Related issue: [#2680](https://github.com/exercism/java/issues/2680)
=> Adding analyzer feedback to design.md for log levels concept exercise

.github/org-wide-files-config.toml, .github/workflows/configlet.yml, .github/workflows/no-important-files-changed.yml
Supersedes #2705 and makes sure we don't have to keep fixing the configlet workflow.
---
=> Sync org wide files

exercises/concept/football-match-reports/.meta/design.md
Related issue: [#2677](https://github.com/exercism/java/issues/2677)
The goal was to add the analyzer, but as the concept exercise didn't have anything yet it was created from 0.
=> Creating design.md for ``football match reports``

exercises/concept/need-for-speed/.meta/design.md, exercises/concept/need-for-speed/.meta/src/reference/java/NeedForSpeed.java
Related issue: [#2682](https://github.com/exercism/java/issues/2682)
As the exercise does not have loops as a prerequisites, and we do not have a concept that introduces to while loops I made some slight changes to the reference resolution as well
Also I got my inspiration for the [go analyzer](https://github.com/exercism/go/blob/main/exercises/concept/need-for-speed/.meta/design.md#analyzer)
=> Adding analyzer feedback for need for speed concept exercise

exercises/concept/annalyns-infiltration/.meta/design.md
=> Add analyzer feedback for Annalyns Infiltration

exercises/shared/.docs/representations.md
The `exercises/shared/.docs/representations.md` file contents are displayed in the Automations part of the website used by mentors to set up automated mentor feedback on solution sets grouped by their representations. This is explained here: https://exercism.org/docs/building/tracks/shared-files#h-file-representations-md
Fixes #2699 
---
=> Add documentation on representations

exercises/concept/secrets/.docs/instructions.md
Just fixing a typo I noticed ("decrpyt" -> "decrypt").
---
=> Fixing typo in the 'Secrets' exercise instructions.md file

exercises/concept/need-for-speed/.docs/instructions.md
=> Update typo in instructions.md

exercises/concept/squeaky-clean/.docs/hints.md, exercises/concept/squeaky-clean/.meta/design.md, exercises/concept/squeaky-clean/.meta/src/reference/java/SqueakyClean.java
closes [#2686](https://github.com/exercism/java/issues/2686)
The goal is to add analyzer recommendations to the design.md, update hints to do not directly tell the student what to do and use ``isWhitespace`` in the reference resolution because it was the method recommended in the hints
=> Adding analyzer feedback for Squeaky Clean concept exercise

exercises/concept/need-for-speed/.meta/design.md
Related: [#134](https://github.com/exercism/java-analyzer/pull/134)A
Updating actionables to match the analyzer ones
=> Updating Actionables for the concept exercise Need for Speed

exercises/concept/bird-watcher/src/main/java/BirdWatcher.java, exercises/concept/elons-toy-car/src/main/java/ElonsToyCar.java
The goal is to update the method message to display the correct class name
=> Updating class message to correct one for ``elons-toy-car`` and ``bird-watcher``

exercises/concept/secrets/.meta/design.md
closes [#2685](https://github.com/exercism/java/issues/2685)
This [solution](https://exercism.org/mentoring/automation/ef0f7c0053ec476c86f7144833e6f049/edit?source%5Bcriteria%5D=secrets&source%5Bpage%5D=1&source%5Btrack_slug%5D=java) could be a great example to see if we want to ask the operator `~` to be used 100% or be flexible and only ask  for the `&` one
=> Adding analyzer feedback for ``secrets`` concept exercise

exercises/concept/remote-control-competition/.docs/instructions.md
The instructions mentioned that the TestTrack.getRankedCars() returns the cars in descending order but the example returns the cars in ascending order. This PR is for fixing it.
---
=> Fixing the sorting order example in the instructions.md for the remote-controlcompetition exercise

exercises/concept/booking-up-for-beauty/.meta/src/reference/java/AppointmentScheduler.java, exercises/concept/calculator-conundrum/.meta/src/reference/java/CalculatorConundrum.java, exercises/concept/calculator-conundrum/src/test/java/CalculatorConundrumTest.java, exercises/concept/captains-log/.meta/src/reference/java/CaptainsLog.java, exercises/concept/logs-logs-logs/.meta/src/reference/java/LogLine.java
As we are generally giving feedback on preferring string concatenation over string.format it makes sense to me that all our reference resolutions (at least for concept exercises) comply with that. Changing the practice ones seemed like a bit overkill, because normally we should give more freedom in those cases to students
=> Changing String format for String concatenation

exercises/practice/parallel-letter-frequency/.docs/hints.md, exercises/practice/parallel-letter-frequency/.docs/instructions.append.md
See #2713 
The exercise docs suggested that the submitted code is automatically
tested for the usage of parallelism. This is not the case, so the
paragraph rewritten to instead suggest students to check for parallelism
themselves.
To help, a few links to resources about concurrency and parallelism in
Java are added.
---
=> Update instructions for parallel-letter-frequency (#2713)

exercises/practice/reverse-string/.meta/config.json, exercises/practice/reverse-string/.meta/design.md, exercises/practice/reverse-string/.meta/tests.toml
=> reverse-string: Sync tests

exercises/concept/karls-languages/.docs/instructions.md, exercises/concept/karls-languages/.docs/introduction.md
- Solve a typo found via [cSpell](https://cspell.org/) using VSCode.
- Also added a comma to make a sentence more readable.
- This is my first PR for Exercism.
---
=> fix: solve typo in Karls Languages INSTRUCTIONS.md

exercises/concept/salary-calculator/src/test/java/SalaryCalculatorTest.java
- Removed a typo from a variable name found whilst reading the test cases.
- Formatting was done via: https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack
---
=> fix: remove typo from SalaryCalculatorTest.java

exercises/concept/cars-assemble/.meta/design.md, exercises/concept/cars-assemble/.meta/src/reference/java/CarsAssemble.java
closes [#2675](https://github.com/exercism/java/issues/2675)
I also updated the reference resolution, because an extra helper method seemed kinda overkill for me.
This are some motivations I found on the automation tab of the java track to make this analyzer comments:
- [example](https://exercism.org/mentoring/automation/bd9c25896aa348c6939e38da62e7d984/edit?source%5Bcriteria%5D=cars%2C+ass&source%5Bpage%5D=1&source%5Btrack_slug%5D=java)
- Also I mentored this exercise a couple of times, so in order to guide to the reference resolution could be great to give them prioir to students
=> Adding analyzer feedback for `cars-assemble` concept exercise

exercises/concept/booking-up-for-beauty/.meta/design.md, exercises/concept/booking-up-for-beauty/.meta/src/reference/java/AppointmentScheduler.java
closes [#2672](https://github.com/exercism/java/issues/2672)
The goal is to add the analyzer information for booking-up-for-beauty and update the reference resolution to a more concise solution
=> Adding analyzer feedback for  `booking-up-for-beauty` concept exercise

exercises/concept/booking-up-for-beauty/.docs/instructions.md
The task description for getting the anniversary date had the year 2023 hardcoded. I see even some accepted solutions had hardcoded the year. So I changed the description to make it clear that the task expects the current year.
---
=> Remove hardcoded year 2023 in the anniversary date task description for Booking Up For Beauty Exercise

exercises/concept/captains-log/.meta/design.md
closes [#2674](https://github.com/exercism/java/issues/2674)
=> Adding analyzer feedback for `captains-log` concept exercise

exercises/practice/knapsack/.approaches/config.json, exercises/practice/knapsack/.approaches/dynamic-programming/content.md, exercises/practice/knapsack/.approaches/dynamic-programming/snippet.txt, exercises/practice/knapsack/.approaches/introduction.md, exercises/practice/knapsack/.approaches/recursive/content.md, exercises/practice/knapsack/.approaches/recursive/snippet.txt
Approaches for knapsack, ready for review!
Resolves #2712 
---
=> Add approaches for Knapsack

exercises/concept/gotta-snatch-em-all/.docs/instructions.md, exercises/concept/gotta-snatch-em-all/.meta/src/reference/java/GottaSnatchEmAll.java, exercises/concept/gotta-snatch-em-all/src/test/java/GottaSnatchEmAllTest.java
Following the discussion in [this forum topic](https://forum.exercism.org/t/need-help-in-clarifying-gotta-snatch-them-all-exercise/10640/1), this PR updates the third task in the `gotta-snatch-em-all` exercise to remove some ambiguity.
---
=> gotta-snatch-em-all: change task to use symmetric set difference

exercises/practice/dnd-character/src/test/java/DnDCharacterTest.java
During a mentoring session, I noticed a solution that passed all the existing tests, but would have failed to meet the following example from the instructions. I wonder if it be worth adding a test for it?
> 3, 5, 3, 4: You discard the 3 and sum 5 + 3 + 4 = 12, which you assign to wisdom.
Note, I have put the PR here instead of the [problem specifications](https://github.com/exercism/problem-specifications/blob/main/exercises/dnd-character/canonical-data.json) because I noticed the Java track already has some tests around the `ability` method and the only `ability` test in the spec seems more vague. I think the `ability` tests we have might be Java specific? 
---
=> dnd-character: Add test case for ability with lowest number occurring twice

exercises/concept/elons-toy-car/.docs/introduction.md
Corrected some spelling mistakes.
---
=> Updated introduction.md

exercises/concept/need-for-speed/.docs/instructions.md
I found these changes are necessary.
---
=> Updated instructions.md

exercises/practice/affine-cipher/.docs/instructions.md, exercises/practice/bank-account/.docs/instructions.md, exercises/practice/change/.meta/tests.toml, exercises/practice/change/src/test/java/ChangeCalculatorTest.java, exercises/practice/custom-set/.meta/tests.toml, exercises/practice/custom-set/src/test/java/CustomSetTest.java, exercises/practice/go-counting/.docs/instructions.md, exercises/practice/killer-sudoku-helper/.docs/instructions.md, exercises/practice/pascals-triangle/.docs/instructions.md, exercises/practice/pascals-triangle/.docs/introduction.md, exercises/practice/pig-latin/.docs/instructions.md, exercises/practice/poker/.docs/instructions.md, exercises/practice/protein-translation/.meta/tests.toml, exercises/practice/protein-translation/src/test/java/ProteinTranslatorTest.java, exercises/practice/queen-attack/.meta/tests.toml, exercises/practice/queen-attack/src/test/java/QueenAttackCalculatorTest.java, exercises/practice/roman-numerals/.meta/tests.toml, exercises/practice/roman-numerals/src/test/java/RomanNumeralsTest.java, exercises/practice/sublist/.meta/tests.toml, exercises/practice/sublist/src/test/java/RelationshipComputerTest.java, exercises/practice/zebra-puzzle/.docs/instructions.md, exercises/practice/zebra-puzzle/.docs/introduction.md
Related [#2388](https://github.com/exercism/java/issues/2388)
=> Sync docs and a couple of tests

exercises/concept/need-for-speed/src/test/java/NeedForSpeedTest.java
#2796 
This PR closes the above mentioned issue.
It does so by ensuring that a car with a drain that's larger than the remaining battery will have it's battery drained.
---
=> 🐛 Ensure batteryDrained correctly reflects state of battery

exercises/concept/need-for-speed/.docs/instructions.md, exercises/concept/need-for-speed/.meta/design.md, exercises/concept/need-for-speed/.meta/src/reference/java/NeedForSpeed.java, exercises/concept/need-for-speed/src/main/java/NeedForSpeed.java, exercises/concept/need-for-speed/src/test/java/NeedForSpeedTest.java
Renamed the `tryFinishTrack` in `NeedForSpeed` to be `canFinishRace` to match the expectation of the instructions for the final task.
Resolves https://github.com/exercism/java-analyzer/issues/184.
---
=> Rename tryFinishTrack to canFinishRace for better expectations

exercises/practice/scrabble-score/.approaches/introduction.md
First pull request on this repository, so forgive me if I did anything wrong.
While I was looking at the Dig Deeper section of Scrabble Score, I saw that the links to each approach were broken because "scrabble-score" was instead written as "scrabble=score". They should now link to the correct pages.
---
=> Fix links for Scrabble Score dig deeper page

exercises/practice/error-handling/.docs/instructions.append.md
This PR clarifies the definition of unchecked exception and fixes minor grammar errors in the error-handling exercise instructions.
---
=> Fix the definition of unchecked exception in the error-handling exercise instructions

exercises/concept/secrets/.docs/introduction.md
Fixed minor typo.
Minor typo fix in Secrets concept (Bitwise OR section).
---
=> Fix typo in Secrets introduction.md

concepts/arrays/about.md, concepts/arrays/introduction.md, exercises/concept/bird-watcher/.docs/introduction.md
Hello! I've noticed the sentence "The most commonly used property for arrays is its length" might lead to some misunderstandings, as Java only has a single built-in direct property for arrays. To clarify this, I've made a small adjustment. 
Replaced 
> "The most commonly used property for arrays is its length which can be accessed like this:"
with 
> "Java has a built-in `length` property that returns the length of an array, which can be accessed like this:".
Please let me know if you have any questions. Thanks in advance.
---
=> improve explanation on Java array .length property

exercises/concept/squeaky-clean/.docs/instructions.md, exercises/concept/squeaky-clean/.meta/config.json, exercises/practice/complex-numbers/.meta/config.json
This pull request is aimed at changing the `instructions.md` for the Squeaky-Clean exercise in the track.
Ref- https://forum.exercism.org/t/java-squeaky-clean-unclear-readme/13575
---
=> Update Squeaky Clean instructions

concepts/arrays/about.md, concepts/arrays/introduction.md, exercises/concept/bird-watcher/.docs/introduction.md
Updated the description of Java arrays to avoid confusion with the term "collection" as used in the Java Collections Framework. Previously, the text referred to arrays as collections, which is inaccurate in Java's formal terminology.
Native Java arrays are not part of the Collections Framework, as they do not implement the `Collection` interface or its subtypes, such as `List`, `Set`, or `Map`. They are simply fixed-size objects that hold elements of the same type.
I have rephrased the description to make it more accessible for those who are new to Java, avoiding excessive technical jargon while still preventing misunderstandings and aligning the explanation with Java's official definitions.
---
[Track Policies](https://github.com/exercism/java/blob/main/POLICIES.md#eve …
=> Remove collection from array description

concepts/nullability/about.md, concepts/nullability/introduction.md, exercises/concept/tim-from-marketing/.docs/introduction.md
Small change to the grammar to make more sense.
---
=> Fix grammar and clarity in reference types explanation

exercises/practice/scrabble-score/.approaches/if-statements/content.md, exercises/practice/scrabble-score/.approaches/introduction.md, exercises/practice/scrabble-score/.approaches/map-reduce/content.md, exercises/practice/scrabble-score/.approaches/switch-statement/content.md
=> General fixes in scrabble-score approaches

exercises/practice/bob/.meta/config.json, exercises/practice/bob/.meta/tests.toml, exercises/practice/bob/src/test/java/BobTest.java, exercises/practice/yacht/.meta/config.json
=> Updating tests of Bob exercise to sync with the Problem-Specification repo

exercises/practice/yacht/.meta/config.json, exercises/practice/zipper/.meta/config.json, exercises/practice/zipper/.meta/tests.toml, exercises/practice/zipper/src/test/java/ZipperTest.java
This only adds one test to sync the tests with the Problem-Specification repo
---
=> Updating tests of Zipper exercise to sync with the Problem-Specification repo

exercises/practice/complex-numbers/.docs/instructions.md, exercises/practice/dot-dsl/.meta/config.json, exercises/practice/hamming/.docs/instructions.md, exercises/practice/hamming/.meta/config.json, exercises/practice/luhn/.docs/instructions.md, exercises/practice/pov/.meta/config.json, exercises/practice/protein-translation/.docs/instructions.md, exercises/practice/pythagorean-triplet/.meta/config.json, exercises/practice/rna-transcription/.docs/instructions.md, exercises/practice/square-root/.docs/instructions.md, exercises/practice/square-root/.docs/introduction.md, exercises/practice/state-of-tic-tac-toe/.docs/instructions.md, exercises/practice/sublist/.docs/instructions.md, exercises/practice/yacht/.meta/config.json
This PR aims to synchronize all previously unsynced tests, file paths, metadata, and documentation with the **problem-specifications** repository.
---
=> Sync file paths, metadata, and documentation with the problem-specifications repository

docs/TESTS.md
This PR adds a section on how to add executable permissions to the `gradlew` file, used to run tests.
I find it interesting how no one else seems to be facing this issue, but I always face it on Java when downloading exercises (which I do by using [exercism.el](https://github.com/anonimitoraf/exercism.el)).
---
=> Add text clarifying test executable permissions

exercises/practice/binary-search/src/test/java/BinarySearchTest.java
In JAVA track improve test names for binary search exercise.
Fixes #2881 
=> Fix test name for binary search exercise

exercises/practice/darts/.approaches/introduction.md
=> Write constants in UPPER_CASE 

concepts/switch-statement/.meta/config.json, concepts/switch-statement/about.md, concepts/switch-statement/links.json
Add example with guarded patterns and which LTS Java versions have these features.
---
=> Small improvement on the enhanced switch block explanation

exercises/practice/flatten-array/.meta/config.json, exercises/practice/flatten-array/.meta/src/reference/java/Flattener.java, exercises/practice/flatten-array/src/main/java/Flattener.java
This PR addresses [issue #2896](https://github.com/exercism/java/issues/2896) by updating the method signature in the starter code. Additionally, it updates the example solution to align with the revised method signature in the starter code.
---
=> Updating method signature in flatten array

exercises/practice/sgf-parsing/.meta/config.json, exercises/practice/sgf-parsing/.meta/src/reference/java/SgfParsing.java, exercises/practice/sgf-parsing/.meta/tests.toml, exercises/practice/sgf-parsing/src/test/java/SgfParsingTest.java
Hello @kahgoh,
This PR introduces 11 new tests for the `sfg-parsing` exercise to align it with the `problem-specification` repository.
However, I encountered difficulties with getting the example solution to work, despite spending several hours trying different approaches. Please let me know how you would like me to proceed from here.
---
=> Updating tests for SGF-Parsing

POLICIES.md
Path corrected for sampleFile.java which was maybe pointing to older url which does not exists
---
=> Fix broken link in POLICIES.md

exercises/concept/international-calling-connoisseur/src/test/java/DialingCodesTest.java
I noticed that the new map concept had a test with a missing assertion. I'm assuming this is the expected outcome based on the test name.
---
=> Add missing assertion from updateDialingCode test

exercises/practice/knapsack/.docs/instructions.append.md
fixes #2929 
Remove instructions.append.md from Knapsack as it no more needs
---
=> Remove redundant instructions for knapsack exercise

POLICIES.md, concepts/inheritance/about.md, concepts/switch-statement/about.md, exercises/concept/log-levels/.docs/hints.md, exercises/concept/remote-control-competition/.docs/hints.md, exercises/concept/salary-calculator/.docs/hints.md, exercises/concept/wizards-and-warriors/.docs/hints.md, exercises/practice/dot-dsl/.docs/instructions.md, exercises/practice/hello-world/.docs/instructions.append.md, reference/contributing-to-practice-exercises.md
This PR updates 18 instances of generic link text across 10 files to resolve markdown linting errors introduced by recent [markdownlint](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md059.md) rule upgrades (via Dependabot).
---
=> Fix lint issues

concepts/exceptions/.meta/config.json, concepts/exceptions/about.md, concepts/exceptions/introduction.md, exercises/concept/calculator-conundrum/.docs/introduction.md
Clarify classification of exceptions and errors in Java introduction
This PR:
- Distinguishes clearly between exceptions and errors
- Clarifies that errors are not exceptions
- Moves the section on errors into its own separate category
---
=> Update exception terminology to clarify types of exceptions

exercises/practice/swift-scheduling/src/test/java/SwiftSchedulingTest.java
Add @DisplayName annotations to swift-scheduling tests
Replace existing @DisplayName annotations with canonical descriptions from problem-specifications to ensure consistency across tracks.
Replace existing @DisplayName annotations in swift-scheduling tests with canonical descriptions from problem-specifications to ensure consistency across tracks.
- Updated all 16 test methods with canonical descriptions from `canonical-data.json`
- Maintained existing test logic and functionality
- Only modified @DisplayName annotations for better test output readability
**Before:**
@DisplayName("NOW at 9 AM")
**After:**
@DisplayName("NOW translates to two hours later")
---
=> Add @DisplayName to Test Methods in Practice Exercises #2971

exercises/practice/acronym/src/test/java/AcronymTest.java
As this is my first PR, I'm only including one exercise in this one. For my next PRs, I will include more than one exercise
---
=> acronym display-tag

exercises/practice/circular-buffer/src/test/java/CircularBufferTest.java, exercises/practice/clock/src/test/java/ClockAddTest.java, exercises/practice/clock/src/test/java/ClockCreationTest.java, exercises/practice/clock/src/test/java/ClockEqualTest.java, exercises/practice/collatz-conjecture/src/test/java/CollatzCalculatorTest.java
There are 3 main exercises, but the clock exercise is divided into 3 subfiles .
---
=> ended with adding  @DisplayName to circular-buffer, clock, collatz-conjecture

exercises/practice/complex-numbers/src/test/java/ComplexNumberTest.java, exercises/practice/connect/src/test/java/ConnectTest.java, exercises/practice/crypto-square/src/test/java/CryptoSquareTest.java
Completed with 3 exercises.
---
=> concluded with adding @DisplayName to complex-numbers, connect, crypto-square

exercises/practice/dominoes/src/test/java/DominoesTest.java, exercises/practice/etl/src/test/java/EtlTest.java, exercises/practice/flatten-array/src/test/java/FlattenerTest.java
Completed with 3 exercises: dominoes, et1, flatten-array.
---
=> Added @DisplayName to dominoes, et1, flatten-array

exercises/practice/flower-field/src/test/java/FlowerFieldBoardTest.java, exercises/practice/food-chain/src/test/java/FoodChainTest.java, exercises/practice/forth/src/test/java/ForthEvaluatorTest.java
completed with 3 exercises flower-field, food-chain, forth.
---
=> flower-field, food-chain, forth

exercises/practice/rectangles/src/test/java/RectangleCounterTest.java, exercises/practice/relative-distance/src/test/java/RelativeDistanceTest.java, exercises/practice/resistor-color-duo/src/test/java/ResistorColorDuoTest.java, exercises/practice/resistor-color-trio/src/test/java/ResistorColorTrioTest.java, exercises/practice/resistor-color/src/test/java/ResistorColorTest.java, exercises/practice/rest-api/src/test/java/RestApiTest.java, exercises/practice/reverse-string/src/test/java/ReverseStringTest.java
Add @DisplayName annotations to test methods based on canonical data
Added DisplayName annotations to the following exercises:
- rectangles
- relative-distance
- resistor-color-duo
- resistor-color-trio
- resistor-color
- rest-api
- reverse-string
All tests pass successfully (verified with ./gradlew test)
Addresses #2971 (DisplayName annotations initiative)
---
=> Related to #2971 display names 

exercises/practice/intergalactic-transmission/src/test/java/IntergalacticTransmissionTest.java, exercises/practice/isbn-verifier/src/test/java/IsbnVerifierTest.java, exercises/practice/isogram/src/test/java/IsogramCheckerTest.java
Completed with 3 exercises: intergalactic-transmission, isbn-verifier, isogram.
---
=> intergalactic-transmission, isbn-verifier, isogram

exercises/practice/kindergarten-garden/src/test/java/KindergartenGardenTest.java, exercises/practice/knapsack/src/test/java/KnapsackTest.java, exercises/practice/largest-series-product/src/test/java/LargestSeriesProductCalculatorTest.java, exercises/practice/leap/src/test/java/LeapTest.java
added with exercises : 1. kindergarten-garden
2. knapsack
3. largest-series-product
4. leap
---
=> kindergarten-garden, knapsack, largest-series-product, leap

concepts/chars/.meta/config.json, concepts/chars/about.md, concepts/chars/introduction.md, concepts/chars/links.json, config.json, exercises/concept/squeaky-clean/.docs/introduction.md, exercises/concept/squeaky-clean/.meta/config.json
This change:
- Adds more detail to the chars concept and introduction to try help students get closer to the intended solution the first time. During mentoring, it was noticed there were solutions using String.replace, which was not intended.
- Replace Unicode link from chars concept. In 02d488e7 the concept was updated to remove Unicode. However, this link seems to have been forgotten.
- Replace "if-else-statements" with "strings" as a prerequisite for squeaky clean. The solution seems to require obtaining the characters in the String and looping over them. "if-else-statements" is also a prerequisite for "arrays", so students will still have to "if-else-statements" before squeaky clean.
---
[Track Policies](https://github.com/exercism/java/blob/main/POLICIES.md#event-c …
=> Make squeaky clean more beginner friendly

exercises/practice/ledger/src/test/java/LedgerTest.java, exercises/practice/linked-list/src/test/java/DoublyLinkedListTest.java, exercises/practice/list-ops/src/test/java/ListOpsTest.java
exercises :1. ledger
2. linked-list
3. list-ops
---
=> ledger, linked-list, list-ops

CONTRIBUTING.md, exercises/checkstyle.xml, exercises/concept/annalyns-infiltration/src/test/java/AnnalynsInfiltrationTest.java, exercises/concept/football-match-reports/src/test/java/FootballMatchReportsTest.java, exercises/concept/jedliks-toy-car/src/test/java/JedliksToyCarTest.java, exercises/concept/lasagna/src/test/java/LasagnaTest.java, exercises/concept/log-levels/src/test/java/LogLevelsTest.java, exercises/concept/need-for-speed/src/test/java/NeedForSpeedTest.java, exercises/concept/squeaky-clean/src/test/java/SqueakyCleanTest.java, exercises/practice/affine-cipher/src/test/java/AffineCipherTest.java, exercises/practice/micro-blog/src/test/java/MicroBlogTest.java
This pull request primarily refactors the test method names to follow camelCase naming conventions, improving code readability and consistency. Additionally, it makes a minor documentation fix and updates a method name format check in the Checkstyle configuration.
Test code cleanup and consistency:
* Renamed all test methods from snake_case to camelCase to align with Java naming conventions. 
* Updated the `MethodNameCheck` format in `checkstyle.xml` to require camelCase method names without underscores, enforcing the new convention.
* Fixed a relative link in `CONTRIBUTING.md` for the Gradle update instructions to use the correct path.
Issue: https://github.com/exercism/java/issues/3028
---
[Track Policies](https://github.com/exercism/java/blob/main/POLICIES.md#event-c …
=> Refactor method names to remove snake_case

exercises/practice/saddle-points/src/test/java/MatrixTest.java, exercises/practice/satellite/src/test/java/SatelliteTest.java, exercises/practice/say/src/test/java/SayTest.java, exercises/practice/scrabble-score/src/test/java/ScrabbleScoreTest.java, exercises/practice/secret-handshake/src/test/java/HandshakeCalculatorTest.java, exercises/practice/series/src/test/java/SeriesTest.java, exercises/practice/sgf-parsing/src/test/java/SgfParsingTest.java, exercises/practice/sieve/src/test/java/SieveTest.java, exercises/practice/simple-cipher/src/test/java/SimpleCipherTest.java, exercises/practice/space-age/src/test/java/SpaceAgeTest.java, exercises/practice/spiral-matrix/src/test/java/SpiralMatrixBuilderTest.java, exercises/practice/state-of-tic-tac-toe/src/test/java/StateOfTicTacToeTest.java
Add DisplayName annotations to multiple modules
This merge includes the addition of DisplayName annotations to the following exercises:
- state-of-tic-tac-toe
- spiral-matrix
- space-age
- simple-cipher
- sieve
- sgf-parsing
- series
- secret-handshake
- scrabble-score
- say
- satellite
- saddle-points
---
=> Add displayname annotations #2971
