config.json, docs/INSTALLATION.md, docs/TOOLS.md, docs/WORKFLOW.md
See exercism/x-common#69 and exercism/rossconf#1.
=> Added track specific documentation

accumulate/src/main/java/Accumulate.java, allergies/src/main/java/Allergies.java, anagram/src/main/java/Anagram.java, atbash-cipher/src/main/java/Atbash.java, binary/src/main/java/Binary.java, bob/src/main/java/Bob.java, crypto-square/src/main/java/Crypto.java, etl/src/main/java/Etl.java, gigasecond/src/main/java/Gigasecond.java, luhn/src/main/java/Luhn.java, nucleotide-count/src/main/java/DNA.java, octal/src/main/java/Octal.java, pascals-triangle/src/main/java/PascalsTriangle.java, pig-latin/src/main/java/PigLatin.java, prime-factors/src/main/java/PrimeFactors.java, raindrops/src/main/java/Raindrops.java, rna-transcription/src/main/java/RnaTranscription.java, roman-numerals/src/main/java/RomanNumeral.java, scrabble-score/src/main/java/Scrabble.java, sieve/src/main/java/Sieve.java, simple-cipher/src/main/java/Cipher.java, space-age/src/main/java/SpaceAge.java, strain/src/main/java/Strain.java, triangle/src/main/java/Triangle.java, trinary/src/main/java/Trinary.java, word-count/src/main/java/WordCount.java
Some of the ``java`` files to implement have a class defined, some are not. This pull request is there to add the ``public class`` definitions that miss.
I think it's better to have the class defined as, and it felt strange to have some where it was already defined and some not..
Signed-off-by: Vincent Demeester <vincent@sbr.pm>
=> Define the missing class (with no content)

robot-name/src/test/java/RobotTest.java
First 2 characters in test allows numbers, lowercased letters or underscores.
=> Test for Robot name allows other characters for the first 2 characters

atbash-cipher/src/example/java/Atbash.java, atbash-cipher/src/test/java/AtbashTest.java
Based on the README file, it should have a decode equivalent.
=> atbash: Add test case and sample implementation for decode.

allergies/src/test/java/AllergiesTest.java
Add test case for also checking isAllergicTo() when not allergic to anything.
=> allergies: Add test case to check when not allergic to anything

docs/ABOUT.md
I wrote a description for the Java language as specified on the language page [here](http://exercism.io/languages/java). The file basically contains: 
># OOPs it's Java
>From web applications to games, the Java language is as diverse as it is portable meaning that it is     found nearly everywhere. With a very strong focus on object oriented programming, it is an ideal language in which to implement complex data structures and algorithms.
As this is really my first time contributing to exercism I tried to follow the [contribution instructions](http://help.exercism.io/git-workflow.html) as closely as possible, but I am not entirely sure if what I did was correct. Any feedback or suggestions would be greatly appreciated.
=> Add ABOUT.md documentation to describe the Java language.

hello-world/src/test/java/HelloWorldTest.java
Fixes https://github.com/winterchord/xjava/commit/d09fb713d19abbcbdaaa979adb59aa7fc94532fd#commitcomment-14962172
The original PR (https://github.com/exercism/xjava/pull/69) that this issue
could have been fixed in was merged before I could fix this issue.
=> Clean up hello-world tests

word-count/src/example/java/WordCount.java, word-count/src/test/java/WordCountTest.java
=> Fix example and test to use proper casing for method names

exercises/scrabble-score/src/test/java/ScrabbleScoreTest.java
=> Uppercase oxyphenbutazone

README.md
To address #100 , some changes to xjava files will require developer to restart local x-api server before seeing changes.
=> Modify README to clarify instructions

exercises/meetup/src/test/java/MeetupTest.java
As I don't think the month of Map exists, I'm guessing this is meant to be May ;)
=> Fix typo in test name

exercises/hello-world/GETTING_STARTED.md
Fixed a typo in the getting started guide
but the tests are expects -> but the tests expect
=> Fixed typo "but the tests are expects"

config.json
First step in transitioning from "problems" to "exercises".
Part of exercism/xjava#125.
=> Add there "exercises" key to config.json

README.md
- trimmed a bunch: the fewer words used, the more words read.
- removed step-by-step full setup in favor of referring to the CI
script.
=> Describe "simple" setup, leveraging the CI build.

SETUP.md
=> Describe how to get started with an exercise.

exercises/pangram/src/test/java/PangramTest.java
- ensure titles of tests match those in
https://github.com/exercism/x-common/blob/master/exercises/pangram/canonical-data.json
=> Add missing tests to Pangram

docs/INSTALLATION.md
I spent way too long trying to figure out why gradle wasn't working properly. Ended up with gradle 1.4 which doesn't seem to play nice with java 8.
=> PPA for gradle

exercises/hello-world/TUTORIAL.md
=> Fix minor typo

exercises/sum-of-multiples/src/example/java/SumOfMultiples.java, exercises/sum-of-multiples/src/main/java/SumOfMultiples.java, exercises/sum-of-multiples/src/test/java/SumOfMultiplesTest.java
- Moved `SumOfMultiplesTest.java` to `src/test/java`
- Renamed method from `Sum` to `sum`
- Made the method `static`
- Removed unused `import`
=> sum-of-multiples: Fixed test dir, static method, lowercase method name

exercises/meetup/build.gradle, exercises/meetup/src/test/java/MeetupTest.java
hamcrest assertions. Removed assertj from meetup gradle build file. This should fix issue #198 .
=> Issue #198: Replaced assertj assertions in Meetup test with junit and

exercises/etl/build.gradle
=> Issue #194: Removed assertj and guava from etl gradle build file

exercises/series/build.gradle
=> Issue #201: Removed assertj from series gradle build file.

exercises/all-your-base/src/test/java/BaseConverterTest.java
=> Added Ignore annotation to all tests but the first one in all-your-base.

exercises/queen-attack/src/test/java/QueenAttackCalculatorTest.java
=> Removed Ignore annotation from first test in queen-attack.

exercises/atbash-cipher/src/test/java/AtbashTest.java
Also changed variable names to be more descriptive. This should fix the reopened issue #161 .
=> Added parameters test name annotation Atbash DecodeTest. 

exercises/word-count/src/test/java/WordCountTest.java
=> Issue #167: Refactored WordCountTest to have a setup method

exercises/queen-attack/src/test/java/QueenAttackCalculatorTest.java
Re-ordered the tests according to issue #241.
=> Reorder queen-attack tests

exercises/grade-school/build.gradle, exercises/grade-school/src/test/java/SchoolTest.java
=> Revert "Issue #253: Make the sort test more generic. "

exercises/rectangles/src/example/java/RectangleCounter.java
Following on from https://github.com/exercism/xjava/pull/243.
Renames `Grid.Entry` to `Grid.Element` and adds a couple query methods to the `Grid.Element` type for readability.
=> rectangles: polish example implementation

exercises/grade-school/src/example/java/School.java, exercises/grade-school/src/test/java/SchoolTest.java
Removed .db() function, added numberOfStudents() function and renamed the sort() function to studentsByGradeAlphabetical(). Added test to check that grade() gets the students in the order they were inserted. Removed getsStudentsInAGrade() test as what it was testing was already being covered by the tests before it. This should hopefully fix issue #253 .
=> Issue #253: Tried to improve grade school structure. 

exercises/etl/src/test/java/EtlTest.java
@Ignore added to all tests in EtlTest, except the first one.
=> Issue #284: add Ignore annotation to tests

exercises/luhn/src/example/java/LuhnValidator.java, exercises/luhn/src/test/java/LuhnValidatorTest.java
https://github.com/exercism/x-common/blob/134e4970dfa3f1cee7e054ddcacf694609f19290/exercises/luhn/canonical-data.json
Also includes some adjustments to the example solution to fix broken edge cases.
=> luhn: update to latest canonical tests

bin/journey-test.sh, exercises/allergies/src/example/java/Allergen.java, exercises/meetup/src/example/java/MeetupSchedule.java, exercises/meetup/src/test/java/MeetupTest.java, exercises/perfect-numbers/src/example/java/Classification.java, exercises/robot-simulator/src/example/java/GridPosition.java, exercises/robot-simulator/src/example/java/Orientation.java, exercises/secret-handshake/src/example/java/Signal.java, exercises/sublist/src/example/java/Relationship.java, exercises/triangle/src/example/java/TriangleException.java, exercises/triangle/src/example/java/TriangleKind.java
Hey, hope I did everything okay :D
=> Change test names to Camel case

exercises/hamming/src/test/java/HammingTest.java
=> Change @Test expected parameter to @Rule ExpectedException in hamming [Fix #262]

exercises/allergies/src/test/java/AllergiesTest.java
=> Allergies: remove redundant array creation [Fix #275]

exercises/series/src/test/java/SeriesTest.java
=> Series: use JUnit's @Rule feature [Fix #266]

exercises/nth-prime/src/test/java/PrimeTest.java
=> Nth-prime: use JUnit's @Rule feature [Fix #263]

exercises/simple-linked-list/src/test/java/SimpleLinkedListTest.java
=> Simple-linked-list: use JUnit's @Rule feature [Fix #267]

exercises/pascals-triangle/src/test/java/PascalsTriangleTest.java
=> Pascals-triangle: use JUnit's @Rule feature [Fix #265]

exercises/hamming/src/test/java/HammingTest.java
*Remove mention of "complete"
*Fix spelling mistake in second test
*Add throws Exception to methods that throw exceptions
=> hamming: make test names consistent [Fix #304]

exercises/palindrome-products/src/example/java/Palindromes.java, exercises/palindrome-products/src/test/java/PalindromesTest.java
=> Simplify construction logic for palindrome products

exercises/beer-song/src/test/java/BeerSongTest.java
Hey @FridaTveit please forgive me. I could not resist changing the 3rd test
=> beer-song: split tests per assertion [Fix #318]

exercises/allergies/src/test/java/AllergiesTest.java
Test case - **allergic to eggs in addition to other stuff** is incomplete.
Checks for shellfish and strawberries have been added.
=> allergies: Update to canonical data

exercises/anagram/src/test/java/AnagramTest.java
Add test cases - **does not detect a word as its own anagram** and
**anagrams must use all letters exactly once**
=> anagram: Update to canonical data

exercises/atbash-cipher/src/test/java/AtbashTest.java
Decode test case with description **decode all the letters** has been added.
=> atbash-cipher: Update to canonical data

exercises/flatten-array/src/test/java/FlattenerTest.java
@Ignore added to all test cases but the first one
=> #379 flatten-array: add @Ignore to tests

exercises/hamming/src/example/java/Hamming.java, exercises/hamming/src/test/java/HammingTest.java
=> Make hamming use instance methods

exercises/raindrops/src/example/java/RaindropConverter.java, exercises/raindrops/src/test/java/RaindropConverterTest.java
=> Make raindrops use instance method

exercises/robot-name/src/test/java/RobotTest.java
Moved the robot object to setUp() method.
=> robot-name: avoid test pollution [Fix #362]

exercises/luhn/src/test/java/LuhnValidatorTest.java
Created lunhvalidator object in setUp method. 
Replaced every new object construct with the created object.
=> luhn: extract common setup [Fix #356]

exercises/secret-handshake/src/test/java/HandshakeCalculatorTest.java
extracted instance construction to setUp() method.
=> Fix for issue #354: extract common setup

exercises/diamond/src/test/java/DiamondPrinterTest.java
Extracted construction into setUp() method per issue #359
=> Fixed issue #359

exercises/sieve/src/test/java/SieveTest.java
Switched from 'Arrays.asList()' to 'Collections.singletonList()'
=> Sieve redundant array

exercises/difference-of-squares/src/example/java/DifferenceOfSquaresCalculator.java, exercises/difference-of-squares/src/main/java/Difference.java, exercises/difference-of-squares/src/main/java/DifferenceOfSquaresCalculator.java, exercises/difference-of-squares/src/test/java/DifferenceOfSquaresCalculatorTest.java
=> difference-of-squares: adjust API to use instance method [Fix #253]

exercises/sum-of-multiples/src/example/java/SumOfMultiples.java, exercises/sum-of-multiples/src/test/java/SumOfMultiplesTest.java
=> sum-of-multiples: use instance method instead of static method [Fix #355]

exercises/beer-song/src/example/java/BeerSong.java, exercises/beer-song/src/test/java/BeerSongTest.java
Oops, because I moved a couple of curly brackets, the diff is weird now. Should I fix in case it's confusing?
Also, question: why do we have ignore annotations if gradle runs all the tests anyway?
=> Beer song instance methods

bin/journey-test.sh, exercises/book-store/src/test/java/BookstoreTest.java
=> Ensure that tests compile as-is before stripping annotations

exercises/nth-prime/src/example/java/PrimeCalculator.java, exercises/nth-prime/src/test/java/PrimeCalculatorTest.java
=> nth-prime: make use instance method [Fix #358]

exercises/flatten-array/src/test/java/FlattenerTest.java
https://github.com/exercism/x-common/blob/d7a3c09b6758a8a5d59a2e140e6684031316280a/exercises/flatten-array/canonical-data.json
=> flatten-array: update to v1.1.0 of canonical tests

docs/INSTALLATION.md
Just a small fix for two typos that I noticed in INSTALLATION.md
=> INSTALLATION.md: Fixed spelling errors in documentation

exercises/book-store/src/example/java/Bookstore.java, exercises/book-store/src/test/java/BookstoreTest.java
Closes #416.
Example implementation was updated to match the [xcsharp](https://github.com/exercism/xcsharp/blob/master/exercises/book-store/Example.cs) implementation.
I also ran the classes through my formatter to make them more consistent with other files in the repo.
=> bookstore: fix test suite equality checks

exercises/palindrome-products/src/example/java/PalindromeCalculator.java, exercises/palindrome-products/src/test/java/PalindromeCalculatorTest.java
=> palindrome-products: make class use instance methods [Fix #377]

bin/journey-test.sh, exercises/rna-transcription/src/test/java/RnaTranscriptionTest.java
See issue #426 for discussion.
=> rna-transcription: add hint to Ignore annotation

config.json
=> isogram: rate difficulty 4, reposition

exercises/accumulate/src/test/java/AccumulateTest.java
=> accumulate: add hint to @Ignore annotations

exercises/acronym/src/test/java/AcronymTest.java
=> acronym: add hint to @Ignore annotations

exercises/anagram/src/test/java/AnagramTest.java
=> anagram: add hint to @Ignore annotations

exercises/allergies/src/test/java/AllergiesTest.java
=> allergies: add hint to @Ignore annotations

exercises/all-your-base/src/test/java/BaseConverterTest.java
=> all-your-base: add hint to @Ignore annotations

exercises/triangle/src/test/java/TriangleTest.java
=> triangle: fix mistake in test name

exercises/perfect-numbers/src/test/java/NaturalNumberTest.java
=> perfect-numbers: add hint to @Ignore annotations per #444

exercises/saddle-points/src/test/java/MatrixTest.java
=> saddle-points: add hint to @Ignore annotations per #440

exercises/pangram/src/test/java/PangramCheckerTest.java
=> pangram: add hint to @Ignore annotations

exercises/gigasecond/src/test/java/GigasecondTest.java
=> gigasecond: add hint to @Ignore annotations

exercises/difference-of-squares/src/test/java/DifferenceOfSquaresCalculatorTest.java
=> difference-of-squares: add hint to @Ignore annotation

exercises/secret-handshake/src/test/java/HandshakeCalculatorTest.java
=> secret-handshake: add hint to @Ignore annotations

exercises/palindrome-products/src/test/java/PalindromeCalculatorTest.java
=> palindrome-products: add hint to @Ignore annotations

exercises/simple-cipher/src/test/java/SimpleCipherStepOneTest.java, exercises/simple-cipher/src/test/java/SimpleCipherStepThreeTest.java, exercises/simple-cipher/src/test/java/SimpleCipherStepTwoTest.java
=> simple-cipher: add hint to @Ignore annotations

exercises/list-ops/src/test/java/ListOpsTest.java
=> ListOpsTest : add hint to @Ignore annotations

exercises/change/src/test/java/ChangeCalculatorTest.java
=> ChangeCalculatorTest : add hint to @Ignore annotations

exercises/clock/src/test/java/ClockAddTest.java, exercises/clock/src/test/java/ClockCreationTest.java, exercises/clock/src/test/java/ClockEqualTest.java
=> Clock : add hint to @Ignore annotations

exercises/custom-set/src/test/java/CustomSetTest.java
=> CustomSetTest : add hint to @Ignore annotations

exercises/sublist/src/test/java/RelationshipComputerTest.java
=> sublist: add hints to @Ignore annotations

exercises/minesweeper/src/test/java/MinesweeperBoardTest.java
=> minesweeper: add hints to @Ignore annotations

exercises/robot-simulator/src/test/java/RobotTest.java
=> robot-simulator: add hints to @Ignore annotations

exercises/series/src/test/java/SeriesTest.java
=> series: add hints to @Ignore annotations

exercises/wordy/src/test/java/WordProblemSolverTest.java
=> wordy: add hints to @Ignore annotations

exercises/grade-school/src/test/java/SchoolTest.java
=> grade-school: add hints to @Ignore annotations

exercises/etl/src/test/java/EtlTest.java
=> etl: add hints to @Ignore annotations

exercises/pythagorean-triplet/src/test/java/PythagoreanTripletTest.java
=> pythagorean-triplet : add hint to @Ignore annotations

exercises/luhn/src/test/java/LuhnValidatorTest.java
=> luhn: add hints to @Ignore annotations

exercises/binary-search-tree/src/test/java/BSTTest.java
=> binary-search-tree: replace lambda with method reference

exercises/hamming/src/test/java/HammingTest.java
=> hamming: add hint to @Ignore annotations

exercises/linked-list/src/test/java/DoublyLinkedListTest.java
=> linked list: add hint to @Ignore annotations

exercises/twelve-days/src/test/java/TwelveDaysTest.java
=> twelve-days: add hint to @Ignore annotations

exercises/sieve/src/test/java/SieveTest.java
=> sieve: add hint to @Ignore annotations

exercises/pascals-triangle/src/test/java/PascalsTriangleGeneratorTest.java
=> pascals-triangle: add hint to @Ignore annotations

exercises/flatten-array/src/test/java/FlattenerTest.java
=> flatten-array: add hint to @Ignore annotations

exercises/word-count/src/test/java/WordCountTest.java
=> word-count: add hint to @Ignore annotations

exercises/diamond/src/test/java/DiamondPrinterTest.java
=> diamond: add hint to @Ignore annotations

exercises/phone-number/src/test/java/PhoneNumberTest.java
=> phone-number: add hint to @Ignore annotations

exercises/nucleotide-count/src/test/java/NucleotideTest.java
=> nucleotide-count: add hint to @Ignore annotations

exercises/isogram/src/test/java/IsogramCheckerTest.java
=> isogram: add hint to @Ignore annotations

exercises/nth-prime/src/test/java/PrimeCalculatorTest.java
=> nth prime: add hint to @Ignore annotations

exercises/matrix/src/test/java/MatrixTest.java
=> matrix: add hint to @Ignore annotations

exercises/robot-name/src/test/java/RobotTest.java
=> robot-name: add hint to @Ignore annotations

exercises/triangle/src/test/java/TriangleTest.java
=> triangle: add hint to @Ignore annotations

exercises/meetup/src/test/java/MeetupTest.java
=> meetup: add hint to @Ignore annotations

exercises/rectangles/src/test/java/RectangleCounterTest.java
=> rectangles: add hint to @Ignore annotations

exercises/strain/src/test/java/StrainTest.java
=> strain: add hint to @Ignore annotations

exercises/ocr-numbers/src/test/java/OpticalCharacterReaderTest.java
=> ocr-numbers: add hint to @Ignore annotations

exercises/book-store/src/test/java/BookstoreTest.java
=> book-store: add hint to @Ignore annotation

exercises/binary-search-tree/src/test/java/BSTTest.java
=> binary-search-tree: use Collections.singletonList

exercises/bracket-push/src/test/java/BracketCheckerTest.java
=> bracket-push: add hint to @Ignore annotations

exercises/simple-linked-list/src/test/java/SimpleLinkedListTest.java
=> simple-linked-list: add hint to @Ignore annotations

exercises/atbash-cipher/src/test/java/AtbashTest.java
=> atbash-cipher: add hint to @Ignore annotations

exercises/beer-song/src/test/java/BeerSongTest.java
=> beer-song: add hint to @Ignore annotations

exercises/binary-search/src/test/java/BinarySearchTest.java
=> binary-search: add hint to @Ignore annotations

exercises/binary-search-tree/src/test/java/BSTTest.java
=> binary-search-tree: add hint to @Ignore tags

exercises/bob/src/test/java/BobTest.java
=> bob: add hint to @Ignore annotations

exercises/crypto-square/src/test/java/CryptoSquareTest.java
=> crypto-square: add hint to @Ignore annotations

config.json
Per https://github.com/exercism/xjava/issues/230#issuecomment-298173527 and https://github.com/exercism/xjava/issues/297.
---
=> Deprecate accumulate and strain

exercises/hello-world/src/main/java/HelloWorld.java
=> hello-world: standardize starter implementation

exercises/rna-transcription/src/main/java/RnaTranscription.java
=> rna-transcription: standardize starter implementation

exercises/pangram/src/main/java/PangramChecker.java
=> pangram: standardize starter implementation

exercises/acronym/src/example/java/Acronym.java, exercises/acronym/src/main/java/Acronym.java
=> acronym: standardize starter implementation

exercises/difference-of-squares/src/example/java/DifferenceOfSquaresCalculator.java, exercises/difference-of-squares/src/main/java/DifferenceOfSquaresCalculator.java
=> difference-of-squares: standardize starter implementation

exercises/raindrops/src/example/java/RaindropConverter.java, exercises/raindrops/src/main/java/RaindropConverter.java
=> raindrops: standardize starter implementation

exercises/space-age/src/example/java/SpaceAge.java, exercises/space-age/src/main/java/SpaceAge.java
=> space-age: standardize starter implementation

exercises/scrabble-score/src/test/java/ScrabbleScoreTest.java
Remove unused import; clean up test formatting.
---
=> scrabble-score: remove unused import; clean up test formatting

exercises/hamming/src/main/java/Hamming.java
=> hamming: standardize starter implementation

config.json, exercises/kindergarten-garden/build.gradle, exercises/kindergarten-garden/src/example/java/KindergartenGarden.java, exercises/kindergarten-garden/src/example/java/Plant.java, exercises/kindergarten-garden/src/main/java/KindergartenGarden.java, exercises/kindergarten-garden/src/main/java/Plant.java, exercises/kindergarten-garden/src/test/java/KindergartenGardenTest.java
Implementing [kindergarten-garden](https://github.com/exercism/x-common/blob/master/exercises/kindergarten-garden/description.md)
---
=> kindergarten-garden: add to track

exercises/all-your-base/src/test/java/BaseConverterTest.java
=> all-your-base: remove "public final" from test class

exercises/bracket-push/src/test/java/BracketCheckerTest.java
=> bracket-push: remove "public final" from test class

exercises/wordy/src/test/java/WordProblemSolverTest.java
=> wordy: remove "public final" from test class

exercises/gigasecond/src/example/java/Gigasecond.java, exercises/gigasecond/src/main/java/Gigasecond.java, exercises/gigasecond/src/test/java/GigasecondTest.java
=> gigasecond: standardize starter implementation

exercises/secret-handshake/src/test/java/HandshakeCalculatorTest.java
=> secret-handshake: remove "final" keyword from test declaration

exercises/ocr-numbers/src/test/java/OpticalCharacterReaderTest.java
=> ocr-numbers: remove "final" keyword from test declaration

exercises/flatten-array/src/test/java/FlattenerTest.java
=> flatten-array: remove final from class name

exercises/robot-simulator/src/test/java/RobotTest.java
=> robot-simulator: remove "final" keyword from test declaration

exercises/queen-attack/src/test/java/QueenAttackCalculatorTest.java
=> queen-attack: remove "final" from class declaration

exercises/rectangles/src/test/java/RectangleCounterTest.java
=> rectangles: remove "final" from class declaration

exercises/perfect-numbers/src/test/java/NaturalNumberTest.java
=> perfect-numbers: remove "final" from class declaration

exercises/minesweeper/src/test/java/MinesweeperBoardTest.java
=> minesweeper: remove "final" from class declaration

exercises/diamond/src/test/java/DiamondPrinterTest.java
=> diamond: remove "final" from test class declaration

exercises/largest-series-product/src/test/java/LargestSeriesProductCalculatorTest.java
=> largest-series-product: remove "final" from class declaration

exercises/secret-handshake/src/main/java/HandshakeCalculator.java
=> secret-handshake: update starter implementation

exercises/sum-of-multiples/src/main/java/SumOfMultiples.java
=> sum-of-multiples: update starter implementation

exercises/luhn/src/main/java/LuhnValidator.java
=> luhn: update starter implementation

exercises/triangle/src/example/java/Triangle.java, exercises/triangle/src/example/java/TriangleException.java, exercises/triangle/src/main/java/Triangle.java, exercises/triangle/src/main/java/TriangleException.java
=> triangle: update starter implementation

exercises/acronym/src/test/java/AcronymTest.java
[Canonical data](https://github.com/exercism/x-common/blob/cae7ae184caf9adb08525077d5b2a8e60f844417/exercises/acronym/canonical-data.json)
---
=> acronym: update to latest canonical data

exercises/build.gradle
http://docs.groovy-lang.org/latest/html/documentation/#_string_interpolation
---
=> Use idiomatic string interpolation in build file

exercises/binary-search/src/test/java/BinarySearchTest.java
Move lists used in the tests into the actual tests so that they're more
readable.
Should fix issue #602.
---
=> binary-search: make test class less DRY [Fix #602]

exercises/change/src/test/java/ChangeCalculatorTest.java
=> change: remove "final" from test class declaration

exercises/simple-linked-list/src/example/java/SimpleLinkedList.java
=> simple-linked-list: simplify example implementation [Fix #568]

exercises/clock/HINT.md, exercises/clock/src/test/java/ClockEqualTest.java
e.g. https://stackoverflow.com/questions/20990524/asserttrue-vs-assertequals-for-ints
---
=> clock: prefer assert(Not)Equals to assert(True|False)

exercises/clock/src/test/java/ClockAddTest.java, exercises/clock/src/test/java/ClockCreationTest.java, exercises/clock/src/test/java/ClockEqualTest.java
Test files were already up to date with canonical data; captured current version for future reference.
---
=> clock: tag test files with current version

exercises/sublist/src/example/java/RelationshipComputer.java, exercises/sublist/src/main/java/RelationshipComputer.java
=> sublist: remove unnecessary generic constraint

exercises/diamond/src/example/java/DiamondPrinter.java
=> diamond: fix var name in example

exercises/diamond/src/test/java/DiamondPrinterTest.java
[Canonical data](https://github.com/exercism/x-common/blob/894a7c69319d500a25b1b319bc963f818d0e65b4/exercises/diamond/canonical-data.json)
---
=> diamond: add version comment

config.json
=> perfect-numbers: set estimated difficulty to 3

config.json
=> change: estimate difficulty, update order

config.json, exercises/saddle-points/src/example/java/Matrix.java, exercises/saddle-points/src/example/java/MatrixCoordinate.java, exercises/saddle-points/src/main/java/MatrixCoordinate.java, exercises/saddle-points/src/test/java/MatrixTest.java
=> saddle-points: API cleanup, ordering

exercises/collatz-conjecture/src/test/java/CollatzCalculatorTest.java
https://github.com/exercism/x-common/blob/c7c078dbe85e03bd90e6eb343e154f2d176175cc/exercises/collatz-conjecture/canonical-data.json
---
=> collatz-conjecture: update to latest tests

bin/journey-test.sh
Updates the journey test file with improvements from xkotlin (mostly this involves defining configuration variables per-track up front, then reusing those variables throughout the script instead of hard-coding the track/repo name). I'll open up a similar PR in xkotlin shortly that applies these updates over there too!
---
=> journey test: pull in improvements from xkotlin

bin/journey-test.sh, exercises/build.gradle
Updates with changes from https://github.com/exercism/xkotlin/pull/62.
---
=> Add cross-referencing comments r.e. stripping ignores

exercises/scrabble-score/src/example/java/Scrabble.java, exercises/scrabble-score/src/test/java/ScrabbleScoreTest.java
[Canonical tests](https://github.com/exercism/x-common/blob/11ed5039054a84b58bc7ccdda250d8a0121ccbed/exercises/scrabble-score/canonical-data.json).
---
=> scrabble-score: update to v1.0.0 of tests

exercises/hello-world/GETTING_STARTED.md
As suggested in issue #426.
---
=> hello-world: explain @Ignore annotations

config.json
=> kindergarten-garden: estimate difficulty 4

exercises/build.gradle
@FridaTveit I spent some time poking around this file to make sure I understood it well. Let me know if you think the re-organization and extra commentary add value or just noise!
---
=> Clean up root build script

config.json
=> run-length-encoding: estimate difficulty 5

POLICIES.md
See issue #640 and issue #642.
---
=> Add policy for 'final' classes

docs/MAINTAINING.md
We haven't been using it to set priorities for a while now.
---
=> Remove reference to project board

docs/MAINTAINING.md
Tidies up a loose end from #655
---
=> MAINTAINING.md: add link to docs repo

exercises/kindergarten-garden/src/test/java/KindergartenGardenTest.java
For the custom garden tests it wasn't very clear that the students will
be sorted in alphabetial order before being assinged their plants. This
has been added to the test names to make it more clear.
Fixes #659.
---
=> kindergarten-garden: clarify test names

exercises/minesweeper/src/example/java/MinesweeperBoard.java, exercises/minesweeper/src/test/java/MinesweeperBoardTest.java
=> Minesweeper simplify

docs/ABOUT.md
Java is not an acronym or an abbreviation, it should not be written in all-caps (doing so encourages the misunderstanding further, especially as exerscism.io is aimed at newbies!).
---
=> JAVA -> Java

exercises/pangram/src/test/java/PangramCheckerTest.java
[Canonical data](https://github.com/exercism/problem-specifications/blob/fba1aef6b2237f504bfdd0bf575fd49489f12523/exercises/pangram/canonical-data.json)
---
=> pangram: update to 1.1.0

exercises/hamming/src/test/java/HammingTest.java
[Canonical data](https://github.com/exercism/problem-specifications/blob/ebe9bbf952206384d344aded650407751a881e92/exercises/hamming/canonical-data.json)
---
=> hamming: update to v1.1.0 of canonical data

config.json
=> list-ops: estimate difficulty 9

bin/journey-test.sh
https://github.com/exercism/trackler/commit/69e055ad52b3f8d19da95b6ab0593678b8ee1bb4
=> journey test: fix for trackler submodule rename

docs/RESOURCES.md
=> Create RESOURCES.md and add resources

exercises/sieve/src/main/java/Sieve.java
=> sieve: create and validate starter implementation

config.json, exercises/list-ops/HINTS.md, exercises/list-ops/src/example/java/ListOps.java, exercises/list-ops/src/main/java/ListOps.java, exercises/list-ops/src/test/java/ListOpsTest.java
Based on v1.0.0 of the canonical data:
https://github.com/exercism/problem-specifications/tree/28a32203b96ebaecac6a6968831bd66718d8ba30/exercises/list-ops
Plus modifications that are being discussed in
https://github.com/exercism/problem-specifications/issues/826
---
=> list-ops: update to match Kotlin track

POLICIES.md
@Smarticles101 @FridaTveit please check!
---
=> Update policy around language constructs

exercises/sum-of-multiples/src/test/java/SumOfMultiplesTest.java
Confirmed with canonical data: https://github.com/exercism/problem-specifications/blob/master/exercises/sum-of-multiples/canonical-data.json#L6
that this test should be 3 and 5
---
=> Fix typo: 4 -> 5

bin/README.md, bin/journey-test.sh
Hopefully this is higher-visibility; I've noticed we haven't been propagating recent changes to Kotlin :)
---
=> Move script parity comment into scripts README

config.json
Moving it to the end of the track so that it doesn't get given to users as the third exercise. After merging this I'll open a PR to estimate the difficulty.
---
=> rotational-cipher: move to end of track

POLICIES.md, exercises/nucleotide-count/src/example/java/NucleotideCounter.java, exercises/nucleotide-count/src/test/java/NucleotideCounterTest.java
Rename class under test to NucleotideCounter. Rename test class after class under test. Add this to the policies doc.
Fixes #697.
---
=> nucleotide-count: rename classes

docs/TESTS.md
=> TESTS.md: fix link to tutorial

exercises/sum-of-multiples/src/example/java/SumOfMultiples.java
=> sum-of-multiples: replace forloop

exercises/hello-world/TUTORIAL.md
in this first exercise, I face the problem that Gradle was not installed on my device. the tutorial doesn't mention this part. even before I fetch the exercise there was no mention to the Gradle in the installation. so I think as a beginner it might help to add this part to the new people will try and use the tutorial in future and some of them will probably face this issue.
---
=> update TUTORIAL.md [Hello World!] exercise

.travis.yml
=> Update gitter webhook for travis integration

exercises/custom-set/src/test/java/CustomSetTest.java, exercises/word-count/src/test/java/WordCountTest.java
Resolves #648, resolves #715.
---
=> Fix spelling errors in custom-set, word-count test names

exercises/custom-set/src/test/java/CustomSetTest.java
=> Use Collections.singletonList in custom-set tests

docs/ABOUT.md
See https://github.com/exercism/meta/issues/85 for information about the desired formatting.
---
=> ABOUT.md: update formatting for Nextercism

docs/ABOUT.md
=> ABOUT.md: remove confusing sentence

exercises/minesweeper/src/example/java/MinesweeperBoard.java
Use string builder over looped string concatenation.
---
=> Fixes #737

exercises/series/src/test/java/SeriesTest.java
Micro improvement that replaces Arrays.asList with Collections.singletonList
---
=> Fixes #696

exercises/allergies/src/example/java/Allergies.java
replace lambda expression with method reference to isAllergicTo
---
=> Fixes #720 replace lambda with method ref

exercises/change/src/test/java/ChangeCalculatorTest.java
[Canonical data](https://github.com/exercism/problem-specifications/blob/52cf1cfdf18bc9ca244b007d7bc7c4d0bc72f50b/exercises/change/canonical-data.json).
---
=> change: update to v1.1.0 tests

exercises/pig-latin/src/example/java/PigLatinTranslator.java
tighten access modifier and method invocations
---
=> Fixes #718

exercises/robot-simulator/src/example/java/GridPosition.java, exercises/robot-simulator/src/test/java/RobotTest.java
=> Fixes #714 assertTrue -> assertEquals

exercises/largest-series-product/src/example/java/LargestSeriesProductCalculator.java, exercises/largest-series-product/src/test/java/LargestSeriesProductCalculatorTest.java
=> Fixes #745 correct spelling mistake

exercises/rna-transcription/src/example/java/RnaTranscription.java, exercises/rna-transcription/src/test/java/RnaTranscriptionTest.java
I added version number 2.0.0 to track the changes in tests.  Let me know if there are any questions!
---
=> Add tests to catch invalid input edge cases

bin/run-journey-test-from-ci.sh, bin/unit-tests.sh
Not been tested much, but I believe that this should work
---
=> Potential solve for #326 and journey-test passing when they fail

exercises/custom-set/src/example/java/CustomSet.java, exercises/custom-set/src/test/java/CustomSetTest.java
=> Fixes #647 use typed empty lists

config/maintainers.json
=> Show Smarticles101's bio on the website

config.json
Side exercises can only be unlocked by core exercises. Previously we
had exercises being unlocked by both core and side exercises.
Each core exercise should unlock at least one exercise. Previously we
had some core exercises that didn't unlock any side exercises. Now
that's only true of the last core exercise in the track.
Fixes #758.
This should now be the track ordering:
**Always available**
rna-transcription
pangram
space-age
acronym
**Core**
**`hello-world`** (1) unlocks:
- `raindrops` (3, string manipulation)
- `pig-latin` (4, string manipulation)
- `isogram` (4, string manipulation)
- `anagram` (7, string manipulation)
**`two-fer`** (string, 1) unlocks:
- `twelve-days` (4, string manipulation)
- `diamond` (4, string manipulation)
- `bob` (string manipulation, 5)
- `house` (string …
=> Fix track ordering

config.json
This is probably not the best description but it's better than nothing. Please feel free to offer suggestions for a better blurb/better grammar/better wording or anything! :)
Fixes #759.
---
=> Add blurb to config.json

exercises/bob/src/test/java/BobTest.java
=> Fixes #364 construct bob in setUp

exercises/rna-transcription/src/example/java/RnaTranscription.java, exercises/rna-transcription/src/main/java/RnaTranscription.java, exercises/rna-transcription/src/test/java/RnaTranscriptionTest.java
Closes #730.
Updates to [v1.0.1 of the canonical tests](https://github.com/exercism/problem-specifications/blob/866cbdbea37989682eee57c65570150d79cc2095/exercises/rna-transcription/canonical-data.json).
---
=> rna-transcription: update to v1.0.1 tests

config.json
[List of topics](https://github.com/exercism/problem-specifications/blob/master/TOPICS.txt)
The only other topic which might be relevant is `classes` since you do have to modify a class to do the exercise. But that's true for all exercises. So we could add `classes` as a topic to all exercises? Or none of them? Or just the ones without starter implementation?
See issue #523 for general discussion about adding topics.
---
=> Add topics for hello-world

CONTRIBUTING.md
=> Fix mistake in contributing guide

config.json
See [this](https://github.com/exercism/problem-specifications/blob/master/TOPICS.txt) for a list of topics
See [this issue](https://github.com/exercism/java/issues/523) for a discussion about adding topics. 
---
=> two-fer: add topics

config.json
[List of topics](https://github.com/exercism/problem-specifications/blob/master/TOPICS.txt)
---
=> hamming: add topics

config.json
[List of topics](https://github.com/exercism/problem-specifications/blob/master/TOPICS.txt)
[Issue discussing adding topics](https://github.com/exercism/java/issues/523)
---
=> gigasecond: add topics

exercises/difference-of-squares/src/test/java/DifferenceOfSquaresCalculatorTest.java
#753 Improved test names in difference of squares
---
=> #753 Improve test names - difference-of-squares

config.json
Hi, first time contributing to a project!
Feedback would be nice, I hope I did understand the task..
---
=> Added topics for Bob exercise

exercises/saddle-points/.meta/src/reference/java/MatrixCoordinate.java, exercises/saddle-points/src/main/java/MatrixCoordinate.java
This is to improve the error message when comparison fails.
Fixes #778.
---
=> saddle-points: implement toString for matrix coordinate

config.json
Referencing #788
conditionals: finding if a char is repeated
loops: looping through a string's characters
parsing: parsing a string for repeated characters
strings: self-explanatory :)
---
=> Add Isogram topics

config.json
Added topics for question Pig-latin. This PR fixes #787 
---
=> issue fixed

config.json
Resolves #786 
Happy Hacktoberfest! 🎉 
---
=> Add topics to raindrops exercise

config.json
=> Add topics to twelve-days exercise

config.json
=> Add topics to pangram exercise

config.json
Fixes #807
Adding a list of topics to the phone-number problem statement.
---
=> Adding the list of topics for the phone-number problem

config.json
=> Add topics for space-age

config.json
added relevant topics to java exercise: beer-song.
issue #804
=> Add topics to beer-song exercise

config.json
=> Add topics for acronym

config.json
=> Updated Food-Chain Topics :)

config.json
=> Add topics for largest-series-product

config.json
Added four tags to nucleotide-count topics as described in #808.
---
=> Update nucleotide-count topics as in #808

config.json
=> added topics for difference-of-squares

config.json
=> Update allergies topics as in #827

config.json
added topics for word search
fixes #832
---
=> added topics for word search

config.json
=> Added topics for minesweeper

config.json
=> topics properly spaced for series

config.json
First pull request ever! Just added five topics to the exercise 'luhn'.
---
[Track Policies](https://github.com/exercism/xjava/blob/master/POLICIES.md#event-chec
https://github.com/exercism/xjava/blob/master/POLICIES.md#event-checklist)
=> Added topics for luhn

config.json
fixes #826 
Hopefully I'm doing this right, I've read through the documents about contributing and would love to do more for this repo. I'm pretty new to github in general so if I missed a step somewhere please tell me.
---
=> added topics to roman numerals

config.json
=> added diamond topics

config.json
=> Add topics to rna-transcription

exercises/triangle/.meta/src/reference/java/Triangle.java, exercises/triangle/.meta/src/reference/java/TriangleKind.java, exercises/triangle/src/main/java/Triangle.java, exercises/triangle/src/main/java/TriangleKind.java, exercises/triangle/src/test/java/TriangleTest.java
In reference to change 1 in #800.
---
=> Triangle: Replace enum with isEquilateral, is Isosceles, and isScalene methods

config.json
Adding a list of topics to the scrabble-score problem statement.
There isn't an issue created for it, but it was listed on https://github.com/exercism/java/issues/523#issuecomment-329258303
---
=> scrabble-score: add topics

config.json
=> Add topics to transpose exercise

config.json
Fix #848 
First time contributing, hope this helps :)
---
=> Add topics to Secret Handshake exercise

config.json
Resolves #846 
Happy Hacktoberfest~ 🎉 
---
=> Add topics to sum of multiples exercise

config.json
This fixes #845.
This is my first PR, and I hope I did this correctly according to the PR guidelines.
---
=> added topics to perfect numbers

config.json
Add topics to kindergarten-garden
Fixes #853 
---
=> Add topics to problem kindergarten-garden

exercises/largest-series-product/src/main/java/LargestSeriesProductCalculator.java
=> Added stubs to LargestSeriesProductCalculator

config.json
=> complex-numbers: Add topics for exercise to config.json per #873

exercises/matrix/src/main/java/Matrix.java
=> Added stubs to Matrix #547

config.json
Added Topics to Collatz Conjecture 
fixes #870
---
=> Added Topics to Collatz Conjecture #870

config.json
=> Added topics to Matrix exercise. Fixes #852

config.json
=> Add topics to problem 'nth-prime'

config.json
How about another tag for `memorization`? It is not listed in topics.txt though. Should fix #847 
---
=> Add topics to sieve

config.json
Fixes issue #872 regarding prime factors.
---
=> Adding topics to problem 'Prime Factors'

config.json
=> meetup: add topics

config/maintainers.json
Feel free to comment on wording, grammar, spelling or anything else :)
---
=> maintainers.json: show bio for Frida Tveit

config.json
=> Add topics to flatten-array

config.json
=> added topics for robot simulator

config.json
=> topics added for slug- palindrome- products

config.json
Topics for #875. 
The git issues should be resolved now :D. Thanks a lot for your patience @FridaTveit
---
=> added topics for #875 rotational-cipher

config.json
=> added topics in bracket-push, simple-cipher, crpto-square and atbash-cipher

config.json
=> Adding the topics for the clock example

config.json
=> Adding topics for saddle-points example

config.json
=> Add topics to all-your-base problem

config.json
Added topics for change #916.
---
=> added topics for change

exercises/simple-linked-list/src/test/java/SimpleLinkedListTest.java
This should hopefully fix the `simple-linked-list` part of issue #230 :)
---
=> simple-linked-list: use generics

config.json
=> Add topics to Word Count exercise. Fixes #917

config.json
added topics for #920. 
I feel like something is missing though. What do you think @FridaTveit?
---
=> added topics for robot-name

config.json
=> add topics for grade-school.  resolves #919

config.json
=> Added topics for sublist problem

config.json
=> Issue #923 add topics to linked list

config.json
=> added topics for book store

config.json
First PR to an open source repo not owned by me. Please let me know if I did anything incorrectly.
---
=> fixes #925 add topics to simple linked list exercise

config.json
=> Add topics to etl. Fixes #918

config.json
=> Add topics to binary search tree. Fixes #939

config.json
=> Add topics to custom set. Fixes #937

config.json
=> Add topics to forth. Fixes #851

config.json
added topics for run length encoding #876 
---
=> added topics for run length encoding

config.json
=> Add rectangles topics to config

config.json
=> Add topics to list-ops exercise

config.json
=> Spiral matrix : add topics

CONTRIBUTING.md
Hopefully fixes #954. Also mentioned how the canonical data should be used to construct tests. I could split this into two separate sections if that would be better. This might be worth mentioning in the POLICIES doc as well, that we want to stick as closely to the canonical data as possible?
---
=> Update new exercise guide to mention version file

config.json
Added topics to the question Bank Account. This PR fixes #940 
---
=> Fix940 Added topics: bank-account

config.json
A contribution in the spirit of Hacktoberfest 2017. Hope these are the correct topics, I've touched those programming areas when doing the exercise myself.
Fixes #921
---
=> Add topics for OCR Numbers exercise

config.json
=> Add topic to pythagorean-triplet

config.json
Add topics to the House exercise in config.json, for the future version of exercism.
This fixes #793 .
---
=> Add topics to House as per #793.

exercises/acronym/.meta/src/reference/java/Acronym.java
renamed variable `b` to `stringBuilder`for #978
---
=> renamed stringbuilder variable

config.json
=> Added topics for the bowling java program

config.json
Removed `functions` as I don't think it's a very suitable topic. Added `exception_handling` since the tests expect an exception to be thrown.
---
=> bowling: improve topics

exercises/atbash-cipher/.meta/src/reference/java/Atbash.java
=> atbash-cipher: improve reference solution

config.json
Per https://github.com/exercism/configlet/issues/99
---
=> Fix overly long UUIDs

config.json
=> Run configlet fmt

exercises/isogram/src/main/java/IsogramChecker.java
=> Isogram: add starter implementation

exercises/diamond/src/main/java/DiamondPrinter.java
=> Diamond: add starter implementation.

exercises/beer-song/.meta/src/reference/java/BeerSong.java
=> beer-song: update reference solution to package-private

exercises/saddle-points/src/main/java/Matrix.java
=> saddle-points: add starter implementation.

exercises/anagram/src/test/java/AnagramTest.java
Changing the single element lists from Arrays.asList to Collections.singletonList
---
=> anagram: replace Arrays.asList with Collections.singletonList #981

config.json
=> Add topics to problem 'binary-search' #938

exercises/binary-search-tree/src/test/java/BinarySearchTreeTest.java
=> binary-search-tree: remove unused import

exercises/bob/.meta/src/reference/java/Bob.java
=> bob: improve reference solution

exercises/allergies/.meta/src/reference/java/Allergen.java, exercises/allergies/.meta/src/reference/java/Allergies.java, exercises/allergies/src/main/java/Allergen.java
=> allergies: update reference and starter implementations

exercises/anagram/.meta/src/reference/java/Anagram.java
=> anagram: improve reference solution

exercises/kindergarten-garden/src/main/java/KindergartenGarden.java
=> kindergarten-garden: add starter implementation

exercises/rotational-cipher/src/main/java/RotationalCipher.java
=> rotational-cipher: add starter implementation

exercises/nth-prime/src/main/java/PrimeCalculator.java
=> nth-prime: add starter implementation

exercises/binary-search-tree/.meta/src/reference/java/BinarySearchTree.java
=> binary-search-tree: simplify reference implementation

exercises/collatz-conjecture/src/main/java/CollatzCalculator.java
=> collatz-conjecture: add start implementation.

exercises/difference-of-squares/src/main/java/DifferenceOfSquaresCalculator.java
=> difference-of-squares: add starter implementation

exercises/book-store/.meta/src/reference/java/BookStore.java
=> book-store: change indent from 2 to 4 spaces

exercises/bowling/src/test/java/BowlingTest.java
=> bowling: remove unnecessary exceptions from test method signatures

exercises/bowling/.meta/src/reference/java/BowlingGame.java
=> bowling: improve reference solution

exercises/run-length-encoding/.meta/src/reference/java/RunLengthEncoding.java
Fixes [#1033](https://github.com/exercism/java/issues/1033)
---
=> run-length-encoding: make classes and methods package private in reference solution

exercises/kindergarten-garden/.meta/src/reference/java/KindergartenGarden.java, exercises/kindergarten-garden/.meta/src/reference/java/Plant.java, exercises/kindergarten-garden/src/main/java/Plant.java
Fixes [#1019](https://github.com/exercism/java/issues/1019)
---
=> kindergarten-garden: make classes and methods package private in reference solution

exercises/nth-prime/.meta/src/reference/java/PrimeCalculator.java
Fixes [#1024](https://github.com/exercism/java/issues/1024)
---
=> nth-prime: make classes and methods package private in reference solution

exercises/crypto-square/.meta/src/reference/java/Crypto.java
Fixes [#1034](https://github.com/exercism/java/issues/1034)
---
=> crypto-square: make classes and methods package private in reference solution

exercises/circular-buffer/.meta/src/reference/java/BufferIOException.java, exercises/circular-buffer/.meta/src/reference/java/CircularBuffer.java, exercises/circular-buffer/src/main/java/BufferIOException.java
Fixes [#1032](https://github.com/exercism/java/issues/1032)
---
=> circular-buffer: make classes and methods package private in reference solution

docs/MAINTAINING.md
I noticed these links were broken! I think that they'd been moved, so I adjusted them - let me know if this is all ok :slightly_smiling_face: 
---
=> fix broken links in maintaining.md

config.json
Fixes #1054. Look there for full discussion.
---
=> reverse-string: change unlocked_by exercise to two-fer

exercises/binary/.meta/src/reference/java/Binary.java
=> binary: make classes and methods package private in reference solution

exercises/accumulate/.meta/src/reference/java/Accumulate.java
=> accumulate: make classes and methods package private in reference solution

exercises/etl/.meta/src/reference/java/Etl.java, exercises/etl/src/main/java/Etl.java
=> etl: remove public access modifier from etl

config/maintainers.json
Added myself to the maintainers.json :slightly_smiling_face: 
---
=> maintainers.json: add @sjwarner-bp

exercises/linked-list/.meta/src/reference/java/DoublyLinkedList.java
=> linked-list: make classes and methods package private #1055

exercises/isogram/.meta/src/reference/java/IsogramChecker.java
submitting patch for: isogram: make classes and methods package private in reference solution #1051
---
=> removing public access modifier from IsogramChecker class and methods

exercises/largest-series-product/.meta/src/reference/java/LargestSeriesProductCalculator.java
largest-series-product: make classes and methods package private in reference solution #1052 
---
=> largest-series-product: make classes and methods package private #1052

exercises/custom-set/.meta/src/reference/java/CustomSet.java, exercises/food-chain/.meta/src/reference/java/FoodChain.java, exercises/hamming/.meta/src/reference/java/Hamming.java, exercises/hexadecimal/.meta/src/reference/java/Hexadecimal.java
removing public access modifiers from classes & methods in hexadecimal, hamming, food-chain and custom-set. reference issues -  #1050 #1049 #1047 #1045 
---
=> Nix public access

exercises/secret-handshake/README.md
Fixes broken link in README.md
---
=> secret-handshake: fix broken link in README.md

exercises/meetup/.meta/src/reference/java/Meetup.java, exercises/meetup/.meta/src/reference/java/MeetupSchedule.java, exercises/meetup/src/main/java/MeetupSchedule.java, exercises/meetup/src/test/java/MeetupTest.java
Removed public class modifiers from the Meetup.java and MeetupSchedule.java src and .meta folders.
---
=> "#1081 Removed public class modifiers"

exercises/hamming/.meta/src/reference/java/Hamming.java, exercises/matrix/.meta/src/reference/java/Matrix.java
…ss modifier
I have made the class as package private and removed the public access modifier from the public methods as well. Removed the extra spaces as well to preserve the indentation.  PR #1083
Edited the class Hamming to be package private, retaining the private method as it is. PR #1049 
---
=> matrix: make classes and methods package private in reference solution. Resolved the issue

POLICIES.md
Add reference to section about adding a hints file to all exercises with difficulty 5.
---
=> policies.md: add reference to issue #1075

exercises/hamming/src/main/java/Hamming.java
Fixes the hamming.java class to make it package private.
---
=> Fixes #1049

exercises/beer-song/README.md, exercises/house/README.md, exercises/isbn-verifier/README.md, exercises/kindergarten-garden/README.md, exercises/meetup/README.md, exercises/nucleotide-count/README.md, exercises/palindrome-products/README.md, exercises/parallel-letter-frequency/README.md, exercises/pig-latin/README.md, exercises/protein-translation/README.md, exercises/rectangles/README.md, exercises/simple-cipher/README.md, exercises/sum-of-multiples/README.md
Skipped Bob since the README change is for a newer version than the
current Java test suite.
---
=> Regenerate READMEs

config.json
=> parallel-letter-frequency: move later in track

config/maintainers.json
@exercism/java I have decided to step down from officially helping maintain Exercism's Java and Kotlin tracks. Thank you for the wonderful experiences over the past ~15 months. I know that I'm leaving the Java track in many excellent hands, and I look forward to seeing how Nextercism is received by the community in 2018.
Keep up the great work :)
Stuart
---
=> Mark stkent as an alumnus

exercises/acronym/.meta/src/reference/java/Acronym.java, exercises/anagram/.meta/src/reference/java/Anagram.java, exercises/atbash-cipher/.meta/src/reference/java/Atbash.java
Fixes #1119. 
@FridaTveit thank you for your comments at https://github.com/exercism/java/issues/1119#issuecomment-354663182! :) I've done changes for 3 exercises in this PR because they are all pretty bite-sized and only involving small changes.
---
=> Simplify model answers #1119

exercises/allergies/src/test/java/AllergiesTest.java
=> allergies: replace assertEquals with assertTrue/False as appropriate

exercises/phone-number/.meta/hints.md, exercises/phone-number/README.md
Added hints.md file and regenerated the README.md file with configlet.
Fixes issue #1086 
---
=> phone-number add hints and regenerated README.md file

exercises/nucleotide-count/.meta/hints.md
Copied hints.md file from flatten-array exercise and
generated new README.md file. Fixes #1087
---
=> nucleotide-count: added hints about no starter implementation

exercises/word-count/.meta/hints.md
Copied hints.md from flatten-array exercise and
regenerated README.md file via configlet.
Fixes #1088
---
=> word-count: added hints about no starter implementation

exercises/transpose/src/test/java/TransposeTest.java
Fixes #1151 . [Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/transpose/canonical-data.json)
---
=> Changed test cases as per #1151

exercises/robot-simulator/src/test/java/RobotTest.java
Old PR contained irrelevant commits.
Updated robot-simulator tests. 
Closes #1157
---
=> Updating Robot-Simulator Tests (New PR)

exercises/prime-factors/.meta/hints.md
Added new hints.md file copied from exercises/flatten-array/.meta/hints.md
and regenerated the README.md file using configlet. Fixes #1091
---
=> prime-factors: added hints about no starter implementation

exercises/robot-name/.meta/hints.md
Added new hints.md file copied from exercises/flatten-array/.meta/hints.md
and regenerated the README.md file using configlet. Fixes #1090
---
=> robot-name: added hints about no starter implementation

exercises/series/.meta/hints.md
Added a hints.md file to the series exercise and generated
the README.md file again using configlet. Fixes #1096
---
=> series: added hints about no starter implementation

exercises/bob/.meta/hints.md
Added a hints.md file to the bob exercise and generated
the README.md file again using configlet. Fixes #1093
---
=> bob: added hints about no starter implementation

exercises/pascals-triangle/.meta/hints.md
Added a hints.md file to the pascals-triangle exercise and generated
the README.md file again using configlet. Fixes #1094
---
=> pascals-triangle: added hints about no starter implementation

exercises/allergies/.meta/hints.md
Added a hints.md file to the allergies exercise and generated
the README.md file again using configlet. Fixes #1092
---
=> allergies: added hints about no starter implementation

exercises/sum-of-multiples/src/test/java/SumOfMultiplesTest.java
=> Updated test for sum of multiplies #1253

config.json
=> complex-numbers: remove 'classes' as topic

exercises/rational-numbers/.meta/src/reference/java/Rational.java, exercises/rational-numbers/src/main/java/Rational.java
=> rational-numbers: override hashCode

exercises/binary/src/test/java/BinaryTest.java
Removed the parameterized tests and ensured that the tests follow the current canonical data.
---
=> binary: removed use of parameterized tests

exercises/octal/src/test/java/OctalTest.java
=> Remove Parameterized tests for octal

exercises/pig-latin/README.md
=> regenerate readme

config.json
- Increased two-bucket difficulty from 5 to 7.
- Moved location of two-bucket to place with exercises of similar difficulty level.
---
=> two-bucket: increase difficulty from 5 to 7. Closes #1384

exercises/poker/src/test/java/PokerTest.java
Removed `final` from Pocker testcases
---
=> poker: remove `final` from tests #1426

exercises/acronym/src/test/java/AcronymTest.java
To resolve issue #1417 acronym: remove `final` from tests
---
=> removed final from tests

exercises/minesweeper/src/test/java/MinesweeperBoardTest.java
=> removed final keyword from test

exercises/largest-series-product/src/test/java/LargestSeriesProductCalculatorTest.java
Removed keyword final per issue #1423 
---
=> remove final from tests

exercises/bracket-push/src/test/java/BracketCheckerTest.java
=> bracket-push: remove `final` from tests #1420

exercises/difference-of-squares/src/test/java/DifferenceOfSquaresCalculatorTest.java
=> difference-of-squares: remove `final` from tests #1421

exercises/queen-attack/src/test/java/QueenAttackCalculatorTest.java
This PR will fix issue #1452 
---
=> queen-attack: removed `final` from tests

exercises/robot-simulator/src/test/java/RobotTest.java
=> robot-simulator: remove `final` from tests #1453

exercises/go-counting/.meta/src/reference/java/GoCounting.java, exercises/go-counting/src/test/java/GoCountingTest.java
Use of enumeration should be consistent across the test suite.
---
=> go-counting: use provided enumeration instead of Strings

exercises/kindergarten-garden/src/main/java/KindergartenGarden.java
This will resolve - Kindergarten Garden -> unused constructor in starter solution #1441
---
=> Kindergarten Garden - unused constructor cleanup

exercises/armstrong-numbers/.meta/hints.md, exercises/armstrong-numbers/README.md
=> armstrong-numbers: add reference to tutorial

scripts/insert-ignores.sh
=> Update `insert-ignores.sh` to current requirements #1450

exercises/hello-world/TUTORIAL.md
Update command to reflect the cli command options by providing an example command for downloading the next exercise.
---
=> Replace fetch command with download

docs/INSTALLATION.md, docs/TESTS.md, exercises/hello-world/TUTORIAL.md
See diff & https://www.apple.com/macos/
---
=> Reflect Apple's OS rebranding

exercises/reverse-string/.meta/hints.md, exercises/reverse-string/README.md
=> reverse-string: add reference to tutorial

exercises/grade-school/src/test/java/SchoolTest.java
=> Changes assertThat to assertEquals

exercises/scrabble-score/src/test/java/ScrabbleScoreTest.java
Fixes #1595 by refactoring the instance variable to local variables in each test.
---
=> Refactor `scrabble` instance to local variable in each test.

exercises/series/.meta/src/reference/java/Series.java, exercises/series/src/test/java/SeriesTest.java
=> series: update tests and add version file #1471

exercises/yacht/src/test/java/YachtTest.java
=> yacht: fix test

exercises/bob/README.md, exercises/change/README.md, exercises/complex-numbers/README.md, exercises/crypto-square/README.md, exercises/dominoes/README.md, exercises/hamming/README.md, exercises/pythagorean-triplet/README.md, exercises/simple-cipher/README.md, exercises/two-fer/README.md
=> Update README.md via configlet

exercises/hamming/src/test/java/HammingTest.java
=> hamming: add period to testDisallowLeftEmptyStrand

exercises/acronym/.meta/src/reference/java/Acronym.java, exercises/acronym/src/test/java/AcronymTest.java
=> Fixed tests to call correct method.

exercises/dnd-character/src/main/java/DnDCharacter.java
I would like to suggest these changes to the starter implementation to fix the bug described in Issue #1645. Please let me know if you have any suggestions/corrections.
Fixes #1645.
---
=> DnDCharacter: bugfix starter implementation

exercises/darts/README.md
Just a small fix to the syntax in the darts readme markdown.
---
=> Darts: fix markdown syntax

exercises/binary-search/.meta/src/reference/java/BinarySearch.java
=> Fix integer overflow in binary-search solution

config/maintainers.json
=> maintainers.json: add lemoncurry

exercises/hamming/.meta/src/reference/java/Hamming.java
Java track/Hamming exercise/reference implementation: offer a more modern solution (Java 8), including a more concise management of exceptions
---
=> Update hamming reference

scripts/canonical_data_check.sh
=> canonical data check: sort alphabetically, remove comment

exercises/allergies/.meta/src/reference/java/Allergies.java
Bit wise AND oeprator is used to check if the person is allergic to a given allergen.
If the result is different from 0, this is the case.
---
=> [Allergies] Small simplification

config.json
Based on https://github.com/exercism/problem-specifications/blob/master/TOPICS.txt. Fixes #1656
---
=> Normalize topics (Fixes #1656)

config/maintainers.json
@iHiD invited me to be an official Java maintainer and said I should submit a PR here.
Let me know if there is anything else I need to do.
---
=> Add Jason Runkle as a Java maintainer

exercises/pig-latin/src/test/java/PigLatinTranslatorTest.java
=> Pig Latin: fix typos in test names

config.json
=> config.json: remove leap, grains, say as foregone exercises

.travis.yml
=> travis.yml add trusty

exercises/linked-list/src/test/java/DoublyLinkedListTest.java
Fixed issue #1737 by adding a third entry into the Linked-list tests. 
---
=> Fixed issue #1737 by adding a third entry into the Linked-list tests

exercises/list-ops/src/test/java/ListOpsTest.java
Rename test methods to better match problem specification:
https://github.com/exercism/problem-specifications/blob/master/exercises/list-ops/canonical-data.json
---
=> list-ops: align test method names with spec

exercises/grains/.meta/src/reference/java/Grains.java, exercises/grains/src/main/java/Grains.java, exercises/grains/src/test/java/GrainsTest.java
Hi, 
Following the issue #1778 I thought it'd be better to discuss the issue over some concrete code. 
This is just changing the name of the methods to make them simpler.
Thank you for your time. 
---
=> "Grains" Simpler method names

config.json
=> fix position of knapsack exercise

config/maintainers.json
I think it's time for me to retire as I don't have as much time to spend on maintaining this track unfortunately. I've really enjoyed being a maintainer for the last few years! I'll still be around if anyone has any questions about anything 🙂 
---
=> Frida Tveit retire from maintaining

config/maintainers.json
Like Frida, I think it's time for me to retire from @exercism/java I haven't had much time recently to contribute to the java track and now that I am in college and v3 is coming up, I'll probably have even less time!
I am removing myself from the team, but I will respond to any relevant mentions. I am also still in the Exercism slack if you'd like to reach me on there.
---
=> Set smarticles101 as alumnus

config/maintainers.json
Due to life changes in the last few months and the very limited time to contribute I retire from maintaining the Java-Track. I thought about retiring for the last few weeks and am happy and relieved that there will be new maintainers to this track to take over, with more time on their hands.
I am very grateful for the opportunity to learn about maintaining a track. I especially want to thank @FridaTveit who was the best example I could have wished for as a maintainer. I learned so much from @FridaTveits way to review PRs and her always polite and helpful way of communication.
---
=> Retire as maintainer

config/maintainers.json
Adding myself as maintainer to track.
---
=> add msomji as java maintainer

config/maintainers.json
add myself as Java maintainer
---
=> add mirkoperillo as maintainer

bin/fetch-configlet
Adds helpful debug logging to identify any issues with fetch-configlet. Helps to address #1799.
---
=> Add debug logging to fetch-configlet for issue #1799.

bin/fetch-configlet
=> Fix the version fetching in fetch-configlet to be case-insensitive.

exercises/gigasecond/src/main/java/Gigasecond.java, exercises/hamming/src/main/java/Hamming.java, exercises/two-fer/src/main/java/Twofer.java
* Add access modifiers to Gigasecond.java
* Add access modifiers to Hamming.java
* Add access modifiers to Twofer.java
* Remove unnecessary blank lines from Gigasecond.java
* Remove unnecessary blank line from Hamming.java
---
=> Cleaning up three of the intro Java exercises.

POLICIES.md
=> Update POLICIES to allow AssertJ and ban other assertion libraries.

exercises/bob/src/test/java/BobTest.java
I have change the unit test based on current canonical data
---
=> bob: update tests and version file (v1.4.0 -> v1.6.0)

exercises/rest-api/README.md
=> Fix the README for rest-api.

config/maintainers.json
=> Add to maintainers

config.json
Update the status of the track in config file following the spec.
Ref to #1871 
---
=> Update the track status

exercises/concept/bird-watcher/.meta/config.json, exercises/concept/booleans/.meta/config.json, exercises/concept/chars/.meta/config.json, exercises/concept/classes/.meta/config.json, exercises/concept/conditionals/.meta/config.json, exercises/concept/constructors/.meta/config.json, exercises/concept/inheritance/.meta/config.json, exercises/concept/interfaces/.meta/config.json, exercises/concept/lasagna/.meta/config.json, exercises/concept/numbers/.meta/config.json, exercises/concept/strings/.meta/config.json, exercises/concept/switch-statement/.meta/config.json, exercises/concept/ternary-operators/.meta/config.json
Try to fix configlet checks errors
---
=> Fix missing exemplar paths in concept exercises

config.json
add missing configuration of exemplar path pattern in `config.json`
---
=> add exemplar path file pattern

gradle/wrapper/gradle-wrapper.properties
=> Update Gradle generated distribution url to 6.8.3

concepts/for-loops/links.json, concepts/foreach-loops/links.json
Fix configlet checker errors:
```
Missing key: 'url':
/home/runner/work/java/java/concepts/for-loops/links.json
Missing key: 'url':
/home/runner/work/java/java/concepts/foreach-loops/links.json
```
---
=> Fix configlet checker errors: missing url field in concept links.json

config.json
Added key features from discussion #1883 via issue #1865. The `icon` field will be added as they become available in the near future. TODO: list icons https://github.com/exercism/docs/blob/main/building/tracks/config-json.md#key-features
---
=> Added key features. Icons wip

concepts/abstract/.meta/config.json, concepts/arrays/.meta/config.json, concepts/basics/.meta/config.json, concepts/boolean/.meta/config.json, concepts/booleans/.meta/config.json, concepts/chars/.meta/config.json, concepts/classes/.meta/config.json, concepts/conditionals-if/.meta/config.json, concepts/conditionals/.meta/config.json, concepts/constructors/.meta/config.json, concepts/functions/.meta/config.json, concepts/inheritance/.meta/config.json, concepts/interfaces/.meta/config.json, concepts/lists/.meta/config.json, concepts/numbers/.meta/config.json, concepts/strings/.meta/config.json, concepts/ternary-operators/.meta/config.json, config.json
_TL;DR; Add authors/contributors to a new `concepts/<slug>/.meta/config.json` to Concepts in the same way you have for Concept Exercises._
---
To properly attribute authorship/contributorship for an individual concept, each concept will have its own `.meta/config.json` file with `authors` and `contributors` keys like those for concept and practice exercises. We're also moving the concept's blurb from the track's `config.json` to the `.meta/config.json` file, also similar to concept and practice exercises.
See https://github.com/exercism/docs/pull/96/files for the update to the specification.
This PR adds a `.meta/config.json` file for all concepts found in the track's `config.json` file containing:
- A `blurb` key, which value is copied from the `config.json` file and subsequently removed …
=> 🤖 Add .meta/config.json file for concepts

exercises/practice/markdown/src/main/java/Markdown.java
Recover exercise starting solution from commit 9f05774b5d90afbf9d89292d2ebd7253e447ba59
as reported in issue  #1844
---
=> Fix #1844 restore original exercise starting solution

config.json, exercises/concept/annalyns-infiltration/.meta/config.json, exercises/concept/bird-watcher/.meta/config.json, exercises/concept/lasagna/.meta/config.json, exercises/concept/squeaky-clean/.meta/config.json, exercises/concept/wizards-and-warriors/.meta/config.json
- Fix linter checks
- Align to correct names of forked exercises
- Move status of exercises to active
---
=> Cumulative fixes on concept exercises

exercises/practice/hello-world/src/main/java/Greeter.java
Simplify the `hello-world` exercise's stub. The goal of this is to make things easier for students to get started and to introduce as little syntax as possible.
See https://github.com/exercism/v3-launch/issues/46
=> 🤖 Simplify `hello-world` stub

exercises/concept/blackjack/.meta/config.json
=> Fix forked_from after exercise rename

exercises/shared/.docs/help.md
Creation of `help.md` following the v3 documentation structure.
Information are retrieved from old v2 path `java/docs/RESOURCES.md`
Fix #1955 
---
=> Add help.md

exercises/practice/roman-numerals/.meta/src/reference/java/RomanNumerals.java, exercises/practice/roman-numerals/src/test/java/RomanNumeralsTest.java
=> Fix broken roman-numerals exercise

config.json
Updated empty string values for icons in config.json
https://github.com/exercism/java/issues/1961
---
=> Added icon names to icon empty string values

README.md
=> Updated broken link for contributing guide

concepts/chars/introduction.md, concepts/chars/links.json, concepts/classes/about.md, concepts/classes/introduction.md, concepts/constructors/about.md, concepts/constructors/introduction.md, concepts/inheritance/about.md, concepts/interfaces/introduction.md, concepts/switch-statement/about.md, concepts/switch-statement/introduction.md
minor grammatical and English punctuation corrections 
---
=> fix some grammar 

exercises/practice/hello-world/TUTORIAL.md
Tutorial.md had 404 links, I updated the correct ones. This is under the Hello, World exercise.
Cheers
---
=> updated docs under tutorial in helloWorld to correct links

exercises/concept/blackjack/src/main/java/Blackjack.java
=> Correct parameter types and names in smallHand()

exercises/practice/resistor-color/src/test/java/ResistorColorTest.java
For issue #1982 
Converting junit assertions into AssertJ assertions and ran tests against the reference implementation.
Let me know if there are any issues.  I opted to use concise assertion statements as I feel AssertJ is more readable with them.
---
=> Introduce assertj in resistor-color exercise 

.github/workflows/gradle.yml, exercises/concept/need-for-speed/src/main/java/NeedForSpeed.java, exercises/concept/wizards-and-warriors/src/main/java/Fighter.java, exercises/practice/markdown/src/main/java/Markdown.java
* Adds canonical triggers (including manual launch).
* Removes lint since we have a separate workflow / action for Configlet.
* Fixes any pre-existing issues in the repo that break the build.
Fixes #1986 
---
=> Fix broken Java CI with Gradle workflow

config.json
=> Add foreach-loops and for-loops concepts

exercises/concept/salary-calculator/src/main/java/SalaryCalculator.java
=> Remove spaces from stub that break the test runner

exercises/concept/bird-watcher/.meta/src/reference/java/BirdWatcher.java, exercises/concept/bird-watcher/src/main/java/BirdWatcher.java, exercises/concept/bird-watcher/src/test/java/BirdWatcherTest.java
Fixes a few things that bug me.
For example, allow us to teach better data encapsulation by demonstrating defensive copying rather than requiring the references to be to the same array (which the existing tests required due to an equals assertion).
Fixed a few tests to be clearer on why the answer is what it is without duplicating the code from the expected solution.
Also, modify the API for the increment method to return void rather than having an ambiguous integer returned (should it return the updated value, the original value, etc). What it returns was also untested so it could just as easily have returned 0 on every possible input.
---
=> Update bird-watcher to use best practices

exercises/practice/rna-transcription/src/test/java/RnaTranscriptionTest.java
Updated RNA Transcription tests to use AssertJ.  Let me know if an issue also needs created to track this.
---
=> Converting RNA Transcription tests to AssertJ

exercises/practice/transpose/src/test/java/TransposeTest.java
Just a simple switch from assertEquals to assertThat(...).isEqualTo(...)
---
=> Use AssertJ in TransposeTest

exercises/practice/say/build.gradle, exercises/practice/say/src/test/java/SayTest.java
* Upgrade to Junit 1.13 trying to resolve this https://github.com/exercism/java-test-runner/issues/28
* Move assertions to assertj
---
=> Fix say exercise

exercises/concept/karls-languages/src/main/java/LanguageList.java
=> Corrected an exception message karls-languages

exercises/concept/need-for-speed/src/test/java/NeedForSpeedTest.java
=> Added missing @Test in need-for-speed

config.json
These are just part of the `basics` concept.
---
=> Remove references to `variables` and `methods` concepts

concepts/switch-statement/.meta/config.json, concepts/switch-statement/links.json, config.json
Fixes #1992 (last issue before all implemented concept exercises could be re-enabled)
Primarily:
* Add concept slug for `switch-statement`
Also:
* Update TODO blurb
* Use better canonical link about the switch statement in Oracle's docs
---
=> Fix remaining issues for football-match-reports

exercises/practice/clock/src/test/java/ClockAddTest.java, exercises/practice/clock/src/test/java/ClockCreationTest.java, exercises/practice/clock/src/test/java/ClockEqualTest.java
Updating Clock tests, converting junit assertions into AssertJ ones.
---
=> Converting Clock tests to use AssertJ

exercises/practice/two-fer/src/test/java/TwoferTest.java
Updating Twofer tests, converting junit assertions into AssertJ ones.
---
=> Converting Twofer tests to use AssertJ.

exercises/practice/bob/src/test/java/BobTest.java
Updating Bob tests, converting junit assertions into AssertJ ones.
---
=> Bob assertj

exercises/concept/football-match-reports/src/test/java/FootballMatchReportsTest.java
Tests needed to use AssertJ properly. Also switched to the assertThrows method.
Fixes #2013
---
=> Fix FootballMatchReportsTest

exercises/practice/list-ops/src/test/java/ListOpsTest.java
Fixes #2020 where we were using some deprecated APIs.
---
=> Update ListOpsTest to use AssertJ

exercises/concept/remote-control-competition/.meta/src/reference/java/TestTrack.java, exercises/concept/remote-control-competition/src/main/java/TestTrack.java
There's no indication in the examples that TestTrack.race returns anything.... and doesn't make sense given all the other possible return values given the set of other potential return variables all have type int.
=> Changed return type of race to void in TestTrack.java

exercises/concept/bird-watcher/src/test/java/BirdWatcherTest.java
`currentTodayCount` became unused after #1985 but never got removed.
---
=> Remove unused variable in BirdWatcherTest.java

exercises/concept/annalyns-infiltration/src/test/java/AnnalynsInfiltrationTest.java
the test case for signaling feature of the Annalyn's Infiltration had typos
---
=> add separator in name for the test cases

exercises/concept/annalyns-infiltration/src/main/java/AnnalynsInfiltration.java
=> Renamed QuestLogic to correct class

exercises/concept/blackjack/src/main/java/Blackjack.java
Adds braces to if statement; also cleans up some spacing.
---
=> Adjust pre-implmented Blackjack logic to conform to style guide

exercises/concept/squeaky-clean/.docs/instructions.md
=> fix sentences

concepts/booleans/about.md
Added some more examples explained the operators a little
---
=> Updating java/concepts/booleans/about.md

exercises/concept/need-for-speed/.docs/instructions.md
Class name in instructions.md is not consistent with the Class name in the src file. This may be a little confusing when following the instructions. I changed it to RaceTrack to match the src file.
---
=> Update Class name for RaceTrack

config.json
=> Fix(config.json): change prereq of `cars-assemble` to `conditionals-if`

config.json
=> Fix(config.json): change prereq of `bird-watcher` to `conditionals-if`

.gitignore, config.json, exercises/practice/secret-handshake/src/test/java/HandshakeCalculatorTest.java
Fixes #2060 
Basically, the current assertions are horribly broken, but this fixes that.
---
=> Improve secret-handshake assertions with AssertJ

config.json
This now breaks configlet lint since it matches files.example.
---
=> Remove duplicate files.exemplar entry

exercises/practice/robot-name/.meta/src/reference/java/Robot.java, exercises/practice/robot-name/src/test/java/RobotTest.java
Closes #2056 
Added a test to ensure there will be no collisions between the generated names. 
I did a small research to find the minimum sample size to ensure no collisions, extending the principle of the [Birthday Problem](https://en.wikipedia.org/wiki/Birthday_problem). The ideal size I found, i.e. when the probability of a collision tends to 100%, is 5000 samples.
I also updated the reference solution, so it would pass this test.
---
=> robot-name: added new test

.gitignore, docs/RESOURCES.md
---
---
Closes https://github.com/exercism/java/issues/2067
=> update link to java programming books

exercises/concept/annalyns-infiltration/src/test/java/AnnalynsInfiltrationTest.java, exercises/concept/bird-watcher/src/test/java/BirdWatcherTest.java, exercises/concept/blackjack/src/test/java/BlackjackTest.java, exercises/concept/calculator-conundrum/src/test/java/CalculatorConundrumTest.java, exercises/concept/cars-assemble/src/test/java/CarsAssembleTest.java, exercises/concept/elons-toy-car/src/test/java/ElonsToyCarTest.java, exercises/concept/football-match-reports/src/test/java/FootballMatchReportsTest.java, exercises/concept/karls-languages/src/test/java/LanguageListTest.java, exercises/concept/lasagna/src/test/java/LasagnaTest.java, exercises/concept/log-levels/src/test/java/LogLevelsTest.java, exercises/concept/need-for-speed/src/test/java/NeedForSpeedTest.java, exercises/concept/remote-control-competition/src/test/java/RemoteControlCarTest.java, exercises/concept/salary-calculator/src/test/java/SalaryCalculatorTest.java, exercises/concept/squeaky-clean/src/test/java/SqueakyCleanTest.java, exercises/concept/wizards-and-warriors/src/test/java/FighterTest.java
Fix for issue [https://github.com/exercism/exercism/issues/6167](https://github.com/exercism/exercism/issues/6167)
All @ignore statements removed from concept exercises tests
---
=> All @ignore decorators removed above tests in concept exercises

config.json
Issue #1867 
I started to add the prerequisites for the exercises. I will follow the order the exercises appear in the `config.json` file.
I also updated the prerequisites of the connect exercise, to match the concepts in the `concepts` array.
For new concepts, such as `enums` and `exceptions`, I'll submit new issues to create the corresponding concept exercise first. Once it is implemented, we can update the prerequisites.
I only changed the first 10 exercises. Please be extra critic in the feedback, this will help me make a better job in the next exercises yet to be updated. 
---
=> Added prerequisites up to Rotational Cipher

docs/LEARNING.md
The branch was renamed from `master` to `main`.
---
=> Fix broken link for free programming ebooks

concepts/chars/introduction.md
For a very common pattern - iterating over string and doing something on each character one has to know a way to get specific character from the string. String to Char conversion. In syllabus char section has String requirement so the obvious logical connection would be to explain how to get one from another.
---
=> Add useful charAt function.

config.json
"Practices" and "Prerequisites" from Bank Account -> Anagram. "Topics" field removed from each exercise as dictated by instructions.
---
=> Added prerequisites up to Anagram

config.json
Issue #1867 
Small observation: As exercises of difficulty 5 or more do not include initial implementation, I'll be adding the classes concept to all of those as I move on.
---
=> Added prerequisites up to Binary Search

concepts/switch-statement/introduction.md
Fix grammar on the initial concept page of the Switch statement.
---
=> Fix grammar

config.json
Issue https://github.com/exercism/java/issues/1867
Added prerequisites and practices from `resistor-color-duo` to `largest-series-product`.
---
=> Added prerequisites up to Largest Series Product

config.json
Issue #1867
Added prerequisites and practices from `luhn` to `minesweeper`
---
=> Added prerequisites up to Minesweeper

exercises/practice/perfect-numbers/src/main/java/NaturalNumber.java, exercises/practice/say/src/main/java/Say.java
Fixes Issue #2098 
Added stubs of the required methods for both exercises.
---
=> Added starter implementation for Perfect Numbers and Say

docs/INSTALLATION.md, exercises/concept/wizards-and-warriors/.docs/hints.md
=> remove duplicate the

exercises/practice/pythagorean-triplet/src/test/java/PythagoreanTripletTest.java, exercises/practice/sgf-parsing/src/test/java/SgfParsingTest.java
=> Fixes issues #2158 and #2165

exercises/practice/hello-world/.docs/instructions.append.md
Fixes #2167
- Fixed broken link.
- Fixed inconsistent heading sizes.
- Fixed minor case issues.
---
=> Fixed broken link

exercises/practice/series/src/test/java/SeriesTest.java
=> Convert exception assertions to AssertJ in SeriestTest

exercises/practice/change/src/test/java/ChangeCalculatorTest.java, exercises/practice/collatz-conjecture/src/test/java/CollatzCalculatorTest.java
related to https://github.com/exercism/java/issues/2147
---
=> Convert exception assertions to AssertJ in 2 Exercises

exercises/practice/dominoes/src/test/java/DominoesTest.java, exercises/practice/variable-length-quantity/src/test/java/VariableLengthQuantityTest.java
=>  Convert exception assertions to AssertJ in 2 Exercises

exercises/practice/hamming/src/test/java/HammingTest.java
Adding assertJ style to HammingTest
related to https://github.com/exercism/java/issues/2147
---
=> 2447 assertJ haming

exercises/concept/football-match-reports/src/test/java/FootballMatchReportsTest.java
Fix assertJ just like prev PR: https://github.com/exercism/java/pull/2178
Please tag: hacktoberfest-accepted
---
=> 2447 assertJ FootballMatchReportsTest.java

README.md
=> Add Configlet badge to README

exercises/practice/secret-handshake/.meta/config.json
Closes https://github.com/exercism/java/issues/2157
---
=> Make Signal class visible in online editor

exercises/practice/perfect-numbers/src/test/java/NaturalNumberTest.java
related to https://github.com/exercism/java/issues/2147
@andrerfcsantos
---
=> Convert exception assertions to AssertJ in NaturalNumberTest

exercises/practice/circular-buffer/src/test/java/CircularBufferTest.java, exercises/practice/go-counting/src/test/java/GoCountingTest.java, exercises/practice/largest-series-product/src/test/java/LargestSeriesProductCalculatorTest.java
related to https://github.com/exercism/java/issues/2147
---
=>  Convert exception assertions to AssertJ in 3 exercises

exercises/practice/queen-attack/src/test/java/QueenAttackCalculatorTest.java
https://github.com/exercism/java/issues/2147
---
=> Convert exception assertions to AssertJ in QueenAttackCalculatorTest

bin/site-editor-check.sh, exercises/practice/error-handling/.meta/config.json
Make sure files with `UnsupportedOperationException` in the body are editable
---
=> Correctly expose stub files

CONTRIBUTING.md
- Fix #2197 
- Minor typos
- Update Table Of Contents
- blocks #2203 
---
=> Fix links using exercism web doc

exercises/practice/grains/.approaches/bit-shifting/content.md, exercises/practice/grains/.approaches/bit-shifting/snippet.txt, exercises/practice/grains/.approaches/config.json, exercises/practice/grains/.approaches/introduction.md, exercises/practice/grains/.approaches/pow/content.md, exercises/practice/grains/.approaches/pow/snippet.txt
Approaches for the Grains exercise
---
=> Grains approaches

exercises/practice/bob/.approaches/answer-array/content.md, exercises/practice/bob/.approaches/answer-array/snippet.txt, exercises/practice/bob/.approaches/config.json, exercises/practice/bob/.approaches/if-statements/content.md, exercises/practice/bob/.approaches/if-statements/snippet.txt, exercises/practice/bob/.approaches/introduction.md
Approaches for the Bob exercise
---
=> Bob approaches

exercises/practice/difference-of-squares/.approaches/config.json, exercises/practice/difference-of-squares/.approaches/formula/content.md, exercises/practice/difference-of-squares/.approaches/formula/snippet.txt, exercises/practice/difference-of-squares/.approaches/introduction.md, exercises/practice/difference-of-squares/.approaches/intstream/content.md, exercises/practice/difference-of-squares/.approaches/intstream/snippet.txt
Approaches for Difference of Squares.
---
=> Difference of squares approaches

exercises/practice/hamming/.approaches/config.json, exercises/practice/hamming/.approaches/for-loop/content.md, exercises/practice/hamming/.approaches/for-loop/snippet.txt, exercises/practice/hamming/.approaches/introduction.md, exercises/practice/hamming/.approaches/intstream-filter-count/content.md, exercises/practice/hamming/.approaches/intstream-filter-count/snippet.txt, exercises/practice/hamming/.approaches/intstream-map-sum/content.md, exercises/practice/hamming/.approaches/intstream-map-sum/snippet.txt, exercises/practice/hamming/.approaches/intstream-reduce/content.md, exercises/practice/hamming/.approaches/intstream-reduce/snippet.txt
=> Hamming approaches

exercises/practice/raindrops/.approaches/config.json, exercises/practice/raindrops/.approaches/if-statements/content.md, exercises/practice/raindrops/.approaches/if-statements/snippet.txt, exercises/practice/raindrops/.approaches/introduction.md, exercises/practice/raindrops/.approaches/map/content.md, exercises/practice/raindrops/.approaches/map/snippet.txt
=> Raindrops approaches

exercises/practice/robot-name/.approaches/config.json, exercises/practice/robot-name/.approaches/introduction.md, exercises/practice/robot-name/.approaches/random-add-to-used-names/content.md, exercises/practice/robot-name/.approaches/random-add-to-used-names/snippet.txt, exercises/practice/robot-name/.approaches/sequential-take-from-shuffled-names/content.md, exercises/practice/robot-name/.approaches/sequential-take-from-shuffled-names/snippet.txt
=> Robot name approaches

exercises/practice/scrabble-score/.approaches/config.json, exercises/practice/scrabble-score/.approaches/if-statements/content.md, exercises/practice/scrabble-score/.approaches/if-statements/snippet.txt, exercises/practice/scrabble-score/.approaches/introduction.md, exercises/practice/scrabble-score/.approaches/map-reduce/content.md, exercises/practice/scrabble-score/.approaches/map-reduce/snippet.txt, exercises/practice/scrabble-score/.approaches/switch-statement/content.md, exercises/practice/scrabble-score/.approaches/switch-statement/snippet.txt
Approaches for Scrabble Score
---
=> Scrabble score approaches

exercises/practice/secret-handshake/.approaches/config.json, exercises/practice/secret-handshake/.approaches/for-loop/content.md, exercises/practice/secret-handshake/.approaches/for-loop/snippet.txt, exercises/practice/secret-handshake/.approaches/introduction.md, exercises/practice/secret-handshake/.approaches/intstream/content.md, exercises/practice/secret-handshake/.approaches/intstream/snippet.txt
Approaches for Secret Handshake
---
=> Secret handshake approaches

exercises/practice/isogram/.approaches/config.json, exercises/practice/isogram/.approaches/filter-map-allmatch/content.md, exercises/practice/isogram/.approaches/filter-map-allmatch/snippet.txt, exercises/practice/isogram/.approaches/filter-maptoobj-distinct/content.md, exercises/practice/isogram/.approaches/filter-maptoobj-distinct/snippet.txt, exercises/practice/isogram/.approaches/introduction.md
=> Isogram approaches

exercises/practice/darts/.approaches/config.json, exercises/practice/darts/.approaches/doublepredicate/content.md, exercises/practice/darts/.approaches/doublepredicate/snippet.txt, exercises/practice/darts/.approaches/if-statements/content.md, exercises/practice/darts/.approaches/if-statements/snippet.txt, exercises/practice/darts/.approaches/introduction.md
=> Dart approaches

exercises/practice/pythagorean-triplet/.approaches/config.json, exercises/practice/pythagorean-triplet/.approaches/for-loops/content.md, exercises/practice/pythagorean-triplet/.approaches/for-loops/snippet.txt, exercises/practice/pythagorean-triplet/.approaches/introduction.md, exercises/practice/pythagorean-triplet/.approaches/intstream-parallel-flatmap-filter/content.md, exercises/practice/pythagorean-triplet/.approaches/intstream-parallel-flatmap-filter/snippet.txt
Approaches for Pythagorean Triplet
---
=> Pythagorean Triplet approaches

exercises/practice/pig-latin/.approaches/charat-substring/content.md, exercises/practice/pig-latin/.approaches/charat-substring/snippet.txt, exercises/practice/pig-latin/.approaches/config.json, exercises/practice/pig-latin/.approaches/introduction.md
=> Pig Latin approach

exercises/practice/satellite/src/test/java/SatelliteTest.java
=> Convert exception assertions to AssertJ

exercises/practice/darts/.docs/instructions.md, exercises/practice/darts/src/main/java/Darts.java
=> update Darts.java score method signature to match test class parameter types

exercises/concept/remote-control-competition/.meta/src/reference/java/ProductionRemoteControlCar.java, exercises/concept/remote-control-competition/src/main/java/ProductionRemoteControlCar.java
=> fixed typo in parameter identifier

exercises/concept/remote-control-competition/src/test/java/RemoteControlCarTest.java
=> fixed typo in test method name

exercises/practice/dnd-character/.meta/src/reference/java/DnDCharacter.java, exercises/practice/dnd-character/src/main/java/DnDCharacter.java, exercises/practice/dnd-character/src/test/java/DnDCharacterTest.java
This pull request should fix the problems described in issue #2182
- Added test to check that created characters do not have the same values
- Fixed ability calculation not using 3 largest scores
- Fixed incorrect order of inputs in one of the assertEquals
---
=> Fix dnd character issues

exercises/practice/ledger/src/test/java/LedgerTest.java
=> 2261 exercise ledger fix unit tests

exercises/concept/remote-control-competition/.docs/instructions.md
Since the tests are expecting a clear speed definition `RemoteControlCarTest.java:L16` for the cars, a little notifier on that would be useful.
---
=> Update instructions for clarity on the setup.

exercises/practice/accumulate/src/main/java/Accumulate.java, exercises/practice/binary/src/main/java/Binary.java, exercises/practice/hexadecimal/src/main/java/Hexadecimal.java, exercises/practice/octal/src/main/java/Octal.java, exercises/practice/strain/src/main/java/Strain.java, exercises/practice/trinary/src/main/java/Trinary.java
accumulate, binary, hexadecimal, octal, strain, trinary
---
=> 2133 stub for some exercises

exercises/practice/bob/.approaches/introduction.md
changed `determing` to `determining` in a couple places in the Introduction
---
=> Update introduction.md for Bob approaches

exercises/practice/affine-cipher/src/main/java/AffineCipher.java
=> Added stub for AffineCipher

exercises/practice/isbn-verifier/.approaches/introduction.md
corrected mistyped one word
---
=> Update introduction.md - mistype corrected

exercises/practice/isbn-verifier/.approaches/introduction.md
=> Update introduction.md - correct mistyped word

exercises/practice/robot-name/src/test/java/RobotTest.java
issue #2291 
---
Reviewer Resources
=> Add a test to robot-name (sameRobotsHaveSameNames)

exercises/practice/connect/src/main/java/Connect.java
the method in the test file is called without any parameter, this will adjust the main file.
I don't actually know if this is intentional or not, but I don't find something like this in another java exercises so far.
---
=> remove parameter in method 'computeWinner'

exercises/concept/need-for-speed/.docs/introduction.md
The original spelling was the possessive form for more than one class, but since the Introduction details only a single class, the singular possessive form should be used.
---
=> Fix typo in Introduction of Need for Speed

exercises/concept/football-match-reports/.docs/introduction.md
I fixed a number of typos and clarified the writing in some areas.
---
=> Update the Introduction of Football Match Reports

exercises/practice/saddle-points/.docs/instructions.md, exercises/practice/saddle-points/.docs/introduction.md
As mentioned at https://forum.exercism.org/t/java-one-of-the-tasks-is-wrong-description-bug-saddle-points/6774
```sh
bin/configlet sync -e saddle-points -u
```
---
=> sync saddle-points exercise

exercises/practice/anagram/src/main/java/Anagram.java, exercises/practice/hello-world/.docs/instructions.append.md
stub methods issue #2133 
hello-world readme issue #2263
---
=> added stub methods

exercises/practice/pig-latin/src/main/java/PigLatinTranslator.java
=> added stub method (#2133)

exercises/practice/allergies/src/main/java/Allergies.java
This adds stubs to the `allergies` exercise as part of issue #2133
---
=> Add stubs to `allergies` exercise

exercises/practice/forth/src/main/java/ForthEvaluator.java
This adds stubs to the `forth` exercise as part of issue https://github.com/exercism/java/issues/2133
---
=> Add stubs to `forth` exercise

.github/workflows/gradle.yml, exercises/build.gradle, exercises/concept/need-for-speed/src/main/java/NeedForSpeed.java, exercises/practice/binary-search/src/main/java/BinarySearch.java, exercises/practice/binary-search/src/main/java/ValueNotFoundException.java, exercises/practice/custom-set/src/main/java/CustomSet.java, exercises/practice/perfect-numbers/src/main/java/NaturalNumber.java, exercises/practice/pov/src/test/java/PovTest.java, exercises/practice/prime-factors/src/main/java/PrimeFactorsCalculator.java, exercises/practice/pythagorean-triplet/src/main/java/PythagoreanTriplet.java, exercises/practice/rail-fence-cipher/src/main/java/RailFenceCipher.java, exercises/practice/rational-numbers/src/main/java/Rational.java, exercises/practice/robot-simulator/src/main/java/Robot.java, exercises/practice/roman-numerals/src/main/java/RomanNumerals.java, exercises/practice/zipper/src/main/java/Zipper.java
This updates the Gradle build configuration to enable us to check whether the starter sources are able to compile with the unit tests. Hopefully this can help students by making sure that the code they receive for each exercise is able to compile without errors from the start, as figuring out why the tests don't compile is out of scope wrt learning on Exercism IMO.
Note that this PR is depending on each exercise having valid stubs, which are being added as part of #2133.
---
=> Compile starter source with tests

exercises/practice/acronym/.docs/instructions.md
=> Sync docs for practice exercise acronym

exercises/practice/all-your-base/.docs/instructions.md
=> Sync docs for practice exercise all-your-base

exercises/practice/allergies/.docs/instructions.md
=> Sync docs for practice exercise allergies

exercises/practice/alphametics/.docs/instructions.md
=> Sync docs for practice exercise alphametics

exercises/practice/armstrong-numbers/.docs/instructions.md
=> Sync docs for practice exercise armstrong-numbers

exercises/practice/atbash-cipher/.docs/instructions.md
=> Sync docs for practice exercise atbash-cipher

exercises/practice/bank-account/.docs/instructions.md
=> Sync docs for practice exercise bank-account

exercises/practice/binary-search/.docs/instructions.md
=> Sync docs for practice exercise binary-search

exercises/practice/binary-search-tree/.docs/instructions.md
=> Sync docs for practice exercise binary-search-tree

exercises/practice/book-store/.docs/instructions.md
=> Sync docs for practice exercise book-store

exercises/practice/bowling/.docs/instructions.md
=> Sync docs for practice exercise bowling

exercises/practice/clock/.meta/config.json
=> Sync docs for practice exercise clock

exercises/practice/meetup/.meta/config.json
=> Sync docs for practice exercise meetup

exercises/practice/secret-handshake/.meta/config.json
=> Sync docs for practice exercise secret-handshake

exercises/practice/zipper/.docs/instructions.md
=> Sync docs for practice exercise zipper

exercises/practice/zebra-puzzle/.docs/instructions.md
=> Sync docs for practice exercise zebra-puzzle

exercises/practice/yacht/.docs/instructions.md
=> Sync docs for practice exercise yacht

exercises/practice/wordy/.docs/instructions.md
=> Sync docs for practice exercise wordy

exercises/practice/word-search/.docs/instructions.md
=> Sync docs for practice exercise word-search

exercises/practice/variable-length-quantity/.docs/instructions.md
=> Sync docs for practice exercise variable-length-quantity

exercises/practice/two-fer/.docs/instructions.md
=> Sync docs for practice exercise two-fer

exercises/practice/twelve-days/.docs/instructions.md
=> Sync docs for practice exercise twelve-days

exercises/practice/triangle/.docs/instructions.md
=> Sync docs for practice exercise triangle

exercises/concept/calculator-conundrum/build.gradle, exercises/concept/calculator-conundrum/src/test/java/CalculatorConundrumTest.java
this PR addresses the calculator-conundrum task on issue #2356 
---
=> Update calculator conundrum to use test runner v3 features

exercises/practice/sublist/.docs/instructions.md
=> Sync docs for practice exercise sublist

exercises/practice/spiral-matrix/.docs/instructions.md
=> Sync docs for practice exercise spiral-matrix

exercises/practice/space-age/.docs/instructions.md
=> Sync docs for practice exercise space-age

exercises/practice/simple-linked-list/.docs/instructions.md
=> Sync docs for practice exercise simple-linked-list

exercises/practice/series/.docs/instructions.md
=> Sync docs for practice exercise series

exercises/practice/tree-building/.docs/instructions.md
=> Sync docs for practice exercise tree-building

exercises/practice/change/.docs/instructions.md
=> Sync docs for practice exercise change

exercises/practice/circular-buffer/.docs/instructions.md
=> Sync docs for practice exercise circular-buffer

exercises/practice/collatz-conjecture/.docs/instructions.md
=> Sync docs for practice exercise collatz-conjecture

exercises/practice/complex-numbers/.docs/instructions.md
=> Sync docs for practice exercise complex-numbers

exercises/practice/connect/.docs/instructions.md
=> Sync docs for practice exercise connect

exercises/practice/custom-set/.docs/instructions.md
=> Sync docs for practice exercise custom-set

exercises/concept/bird-watcher/build.gradle, exercises/concept/bird-watcher/src/test/java/BirdWatcherTest.java
this PR addresses the bird-watcher task on issue #2356 
---
=> Test runner v3 bird watcher

exercises/practice/anagram/.docs/instructions.md, exercises/practice/anagram/.meta/tests.toml, exercises/practice/anagram/src/test/java/AnagramTest.java
=> Sync docs for practice exercise anagram

exercises/practice/transpose/.docs/instructions.md
=> Sync docs for practice exercise transpose

exercises/practice/tournament/.docs/instructions.md
=> Sync docs for practice exercise tournament

exercises/practice/say/.docs/instructions.md
=> Sync docs for practice exercise say

exercises/practice/satellite/.docs/instructions.md
=> Sync docs for practice exercise satellite

exercises/practice/run-length-encoding/.docs/instructions.md
=> Sync docs for practice exercise run-length-encoding

exercises/practice/rotational-cipher/.docs/instructions.md
=> Sync docs for practice exercise rotational-cipher

exercises/practice/roman-numerals/.docs/instructions.md
=> Sync docs for practice exercise roman-numerals

exercises/practice/robot-simulator/.docs/instructions.md
=> Sync docs for practice exercise robot-simulator

exercises/practice/robot-name/.docs/instructions.md
=> Sync docs for practice exercise robot-name

exercises/practice/crypto-square/.docs/instructions.md
=> Sync docs for practice exercise crypto-square

exercises/practice/simple-cipher/.docs/instructions.md
=> Sync docs for practice exercise simple-cipher

exercises/practice/two-bucket/.docs/instructions.md
=> Sync docs for practice exercise two-bucket

exercises/concept/cars-assemble/build.gradle, exercises/concept/cars-assemble/src/test/java/CarsAssembleTest.java
This PR addresses the cars-assemble task on issue #2356 
---
=> Update cars assemble to use test runner v3 features

exercises/practice/hello-world/.docs/instructions.md
=> Sync docs for practice exercise hello-world

exercises/practice/house/.docs/instructions.md
=> Sync docs for practice exercise house

exercises/practice/isbn-verifier/.docs/instructions.md
=> Sync docs for practice exercise isbn-verifier

exercises/practice/isogram/.docs/instructions.md
=> Sync docs for practice exercise isogram

exercises/practice/kindergarten-garden/.docs/instructions.md
=> Sync docs for practice exercise kindergarten-garden

exercises/practice/knapsack/.docs/instructions.md
=> Sync docs for practice exercise knapsack

exercises/practice/leap/.docs/instructions.md
=> Sync docs for practice exercise leap

exercises/practice/list-ops/.docs/instructions.md
=> Sync docs for practice exercise list-ops

exercises/practice/luhn/.docs/instructions.md
=> Sync docs for practice exercise luhn

exercises/practice/markdown/.docs/instructions.md
=> Sync docs for practice exercise markdown

exercises/practice/matching-brackets/.docs/instructions.md
=> Sync docs for practice exercise matching-brackets

exercises/practice/matrix/.docs/instructions.md
=> Sync docs for practice exercise matrix

exercises/practice/micro-blog/.docs/instructions.md
=> Sync docs for practice exercise micro-blog

exercises/practice/minesweeper/.docs/instructions.md
=> Sync docs for practice exercise minesweeper

exercises/practice/nth-prime/.docs/instructions.md
=> Sync docs for practice exercise nth-prime

exercises/practice/nucleotide-count/.docs/instructions.md
=> Sync docs for practice exercise nucleotide-count

exercises/practice/ocr-numbers/.docs/instructions.md
=> Sync docs for practice exercise ocr-numbers

exercises/practice/palindrome-products/.docs/instructions.md
=> Sync docs for practice exercise palindrome-products

exercises/practice/pangram/.docs/instructions.md
=> Sync docs for practice exercise pangram

exercises/practice/proverb/.docs/instructions.md
=> Sync docs for practice exercise proverb

exercises/practice/protein-translation/.docs/instructions.md
=> Sync docs for practice exercise protein-translation

exercises/practice/prime-factors/.docs/instructions.md
=> Sync docs for practice exercise prime-factors

exercises/practice/poker/.docs/instructions.md
=> Sync docs for practice exercise poker

exercises/practice/parallel-letter-frequency/.docs/instructions.md
=> Sync docs for practice exercise parallel-letter-frequency

exercises/practice/pascals-triangle/.docs/instructions.md
=> Sync docs for practice exercise pascals-triangle

exercises/practice/perfect-numbers/.docs/instructions.md
=> Sync docs for practice exercise perfect-numbers

exercises/practice/phone-number/.docs/instructions.md
=> Sync docs for practice exercise phone-number

exercises/practice/pig-latin/.docs/instructions.md
=> Sync docs for practice exercise pig-latin

exercises/practice/pythagorean-triplet/.docs/instructions.md
=> Sync docs for practice exercise pythagorean-triplet

exercises/practice/queen-attack/.docs/instructions.md
=> Sync docs for practice exercise queen-attack

exercises/practice/rail-fence-cipher/.docs/instructions.md
=> Sync docs for practice exercise rail-fence-cipher

exercises/practice/raindrops/.docs/instructions.md
=> Sync docs for practice exercise raindrops

exercises/practice/rational-numbers/.docs/instructions.md
=> Sync docs for practice exercise rational-numbers

exercises/practice/rectangles/.docs/instructions.md
=> Sync docs for practice exercise rectangles

exercises/practice/resistor-color/.docs/instructions.md
=> Sync docs for practice exercise resistor-color

exercises/practice/resistor-color-duo/.docs/instructions.md
=> Sync docs for practice exercise resistor-color-duo

exercises/practice/rest-api/.docs/instructions.md
=> Sync docs for practice exercise rest-api

exercises/practice/rna-transcription/.docs/instructions.md, exercises/practice/rna-transcription/.docs/introduction.md
=> Sync docs for practice exercise rna-transcription

exercises/concept/blackjack/build.gradle, exercises/concept/blackjack/src/test/java/BlackjackTest.java
This PR addresses task blackjack on issue #2356 
---
=> Update blackjack to use test runner v3 features

exercises/practice/darts/.docs/instructions.md
=> Sync docs for practice exercise darts

exercises/practice/diamond/.docs/instructions.md
=> Sync docs for practice exercise diamond

exercises/practice/difference-of-squares/.docs/instructions.md
=> Sync docs for practice exercise difference-of-squares

exercises/practice/dnd-character/.docs/instructions.md
=> Sync docs for practice exercise dnd-character

exercises/practice/dominoes/.docs/instructions.md
=> Sync docs for practice exercise dominoes

exercises/practice/error-handling/.docs/instructions.md
=> Sync docs for practice exercise error-handling

exercises/practice/etl/.docs/instructions.md
=> Sync docs for practice exercise etl

exercises/practice/flatten-array/.docs/instructions.md
=> Sync docs for practice exercise flatten-array

exercises/practice/food-chain/.docs/instructions.md
=> Sync docs for practice exercise food-chain

exercises/practice/forth/.docs/instructions.md
=> Sync docs for practice exercise forth

exercises/practice/grade-school/.docs/instructions.md
=> Sync docs for practice exercise grade-school

exercises/practice/grains/.docs/instructions.md
=> Sync docs for practice exercise grains

exercises/practice/hamming/.docs/instructions.md
=> Sync docs for practice exercise hamming

exercises/practice/hangman/.docs/instructions.md
=> Sync docs for practice exercise hangman

exercises/practice/go-counting/.docs/instructions.md
=> Sync docs for practice exercise go-counting

exercises/practice/grep/.docs/instructions.md
=> Sync docs for practice exercise grep

exercises/concept/elons-toy-car/build.gradle, exercises/concept/elons-toy-car/src/test/java/ElonsToyCarTest.java
This PR addresses elons toy car task on issue #2356 
---
=> Update elons toy car to use test runner v3 features

exercises/concept/log-levels/build.gradle, exercises/concept/log-levels/src/test/java/LogLevelsTest.java
This PR addresses the log levels task on issue #2356 
---
=> Update log levels to use test runner v3 features

exercises/concept/salary-calculator/build.gradle, exercises/concept/salary-calculator/src/test/java/SalaryCalculatorTest.java
This PR addresses the salary calculator rask on issue #2356 
---
=> Update salary calculator to use test runner v3 features

exercises/concept/wizards-and-warriors/build.gradle, exercises/concept/wizards-and-warriors/src/test/java/FighterTest.java
This PR addresses the wizards and warriors task on issue #2356 
---
=> Update wizards and warriors to use test runner v3 features

exercises/concept/need-for-speed/build.gradle, exercises/concept/need-for-speed/src/test/java/NeedForSpeedTest.java
This PR addresses the need for speed task on issue #2356 
---
=> Update need for speed to use test runner v3 features

exercises/concept/squeaky-clean/build.gradle, exercises/concept/squeaky-clean/src/test/java/SqueakyCleanTest.java
This PR addresses the squeaky clean task on issue #2356 
---
=> Update squeaky clean to use test runner v3 features

exercises/practice/complex-numbers/.meta/config.json, exercises/practice/complex-numbers/.meta/src/reference/java/ComplexNumber.java, exercises/practice/complex-numbers/src/main/java/ComplexNumber.java, exercises/practice/complex-numbers/src/test/java/ComplexNumberTest.java
Made small changes to make methods in exercise more idiomatic and for better readability
Fixes #2317 
---
=> Changed method names to make more idiomatic in complex-numbers (#2317)

.github/workflows/gradle.yml
=> Add test-summary action for Gradle tests

exercises/concept/annalyns-infiltration/build.gradle, exercises/concept/annalyns-infiltration/src/test/java/AnnalynsInfiltrationTest.java
This PR addresses the annalyns infiltration task on issue #2356 
---
=> Update annalyns infiltration to use test runner v3 features

exercises/concept/remote-control-competition/build.gradle, exercises/concept/remote-control-competition/src/test/java/RemoteControlCarTest.java
This PR addresses the remote control competition on issue #2356 
---
=> Update remote control competition to use test runner v3 features

exercises/concept/need-for-speed/src/test/java/NeedForSpeedTest.java
Fix misleading comment in "Need for speed" test. closes #2518 
---
=> Fix comment in "Need for speed"

exercises/practice/hamming/.approaches/intstream-reduce/content.md
Just a quick fix to change the type of variable in the description. Code above description shows type correctly declared as int and the reduce() method returns an int.
---
=> Quick fix variable type in the description

.github/workflows/configlet.yml, config.json, exercises/concept/logs-logs-logs/.meta/config.json, exercises/practice/bob/.approaches/config.json, exercises/practice/collatz-conjecture/.approaches/config.json, exercises/practice/darts/.approaches/config.json, exercises/practice/difference-of-squares/.approaches/config.json, exercises/practice/grains/.approaches/config.json, exercises/practice/hamming/.approaches/config.json, exercises/practice/isbn-verifier/.approaches/config.json, exercises/practice/isogram/.approaches/config.json, exercises/practice/leap/.approaches/config.json, exercises/practice/pangram/.approaches/config.json, exercises/practice/pig-latin/.approaches/config.json, exercises/practice/pov/.meta/config.json, exercises/practice/pythagorean-triplet/.approaches/config.json, exercises/practice/raindrops/.approaches/config.json, exercises/practice/robot-name/.approaches/config.json, exercises/practice/scrabble-score/.approaches/config.json, exercises/practice/secret-handshake/.approaches/config.json, exercises/practice/square-root/.meta/config.json
This PR configures the Configlet workflow in CI to also run `configlet fmt`, so that all files in the repository maintain a consistent formatting.
[no important files changed]
---
=> Check formatting using Configlet in CI

config.json
The representer always 500s. This is now a critical issue as it means no community solutions show, so I'm disabling it.
=> Disable representer

POLICIES.md
=> Fix table formatting in POLICIES.md

exercises/practice/rest-api/src/test/java/RestApiTest.java
closes: #2539
* removed nested classes from main RestApiTest class
---
=> Remove nested test classes from practice exercise rest-api 

README.md
=> Update status badges on README.md

docs/ABOUT.md
=> Fixed typo in docs/ABOUT.md

exercises/practice/roman-numerals/.meta/tests.toml, exercises/practice/roman-numerals/src/test/java/RomanNumeralsTest.java
The goal is to sync the tests of the roman numerals practice exercise
=> Sync tests for practice exercise roman numerals

exercises/practice/prime-factors/.meta/tests.toml, exercises/practice/prime-factors/src/test/java/PrimeFactorsCalculatorTest.java
This issue addresses: [2388](https://github.com/exercism/java/issues/2388)
The goal is to sync the tests of the prime factors practice exercise
=> Sync tests for practice exercise ``prime factors``

concepts/datetime/introduction.md, exercises/concept/booking-up-for-beauty/.docs/introduction.md
=> Fix typo in datetime concept introduction

exercises/practice/rational-numbers/.meta/src/reference/java/Rational.java, exercises/practice/rational-numbers/.meta/tests.toml, exercises/practice/rational-numbers/src/test/java/RationalTest.java
The goal is to sync the tests of the rational numbers practice exercise
=> Sync tests for practice exercise ``rational numbers``

reference/implementing-a-concept-exercise.md
=> Update contribution guide on concept exercises

exercises/practice/leap/.docs/instructions.md, exercises/practice/leap/.docs/introduction.md, exercises/practice/leap/.meta/config.json, exercises/practice/perfect-numbers/.docs/instructions.md, exercises/practice/pythagorean-triplet/.meta/config.json, exercises/practice/queen-attack/.docs/instructions.md, exercises/practice/rest-api/.docs/instructions.md, exercises/practice/spiral-matrix/.meta/config.json, exercises/practice/transpose/.meta/config.json
=> Sync docs and metadata for practice exercises

exercises/concept/logs-logs-logs/.docs/instructions.md
Related issue: [#2563](https://github.com/exercism/java/issues/2563)
=> Fix Overflow Typo

config.json
=> Change exercise name "secrets" to "Secrets"

bin/test-with-test-runner
Fixes #2666
The goal is to make test runner exclude deprecated exercises
=> Adding jq check of the exercise status to test runner

.github/workflows/configlet.yml, .github/workflows/no-important-files-changed.yml
Based on #2663, but reverted a change made by the bot that shouldn't be merged.
---
=> Add no important files changed workflow

exercises/concept/squeaky-clean/.meta/design.md
Related to [comment](https://github.com/exercism/java/pull/2664#issuecomment-1918402736)
=> Updating design.md for squeaky clean after exercise refactor

exercises/practice/dominoes/.meta/src/reference/java/Domino.java, exercises/practice/dominoes/src/main/java/Domino.java
* Add a comment in the Domino class making explicit that changes in the Domino class are not accepted by the solution. (Believe me,
I was really surprised during my first submission that my changes in the Domino class were rejected. As well as my mentee ).
* Change the way equals and hashcode are implemented to use the min+max value of each side instead of left+right.
* Added a constraint validation within the Domino class constructor, that tiles must
have a maximum number of 9 on each side (this is needed for the hash implementation).
* In the equals code, a comparison between a Domino and an Object would generate a
class cast exception instead of the expected value, false.
---
=> Issue #2642 solution - hashcode for dominoes.

exercises/concept/lasagna/src/test/java/utils/Lasagna.java, exercises/concept/wizards-and-warriors-2/src/test/java/GameMasterProxy.java
After the implementation of reflection proxy on wizard-and-warriors we realize that ``invokeMethod`` already handles the exceptions
=> Updating ``lasagna`` and ``wizards-and-warriors-2`` to use directly invokemethod

exercises/practice/two-fer/.meta/design.md
Related https://github.com/exercism/java-analyzer/pull/137
=> Updating prefer string concatenation comment for ``Two Fer`` 

exercises/concept/wizards-and-warriors-2/.meta/design.md
closes [#2689](https://github.com/exercism/java/issues/2689)
=> Adding analyzer feedback for ``wizards-and-warriors-2`` concept exercise

exercises/concept/salary-calculator/.meta/design.md
closes [#2684](https://github.com/exercism/java/issues/2684)
=> Adding analyzer feedback for salary-calculator concept exercise

exercises/concept/logs-logs-logs/.docs/instructions.md
fix typo in instructions.md
---
=> fix typo in instructions.md

exercises/shared/.docs/representations.md
Updates the shared documentation on representations to match the recently updated java-representer.
---
=> Update representations documentation

exercises/practice/alphametics/.docs/instructions.md, exercises/practice/alphametics/.meta/config.json, exercises/practice/darts/.docs/instructions.md, exercises/practice/darts/.meta/config.json, exercises/practice/flatten-array/.docs/instructions.md, exercises/practice/go-counting/.docs/instructions.md, exercises/practice/meetup/.meta/config.json, exercises/practice/parallel-letter-frequency/.docs/instructions.md, exercises/practice/raindrops/.meta/config.json, exercises/practice/say/.docs/instructions.md, exercises/practice/two-bucket/.docs/instructions.md
=> Sync outdated practice exercise docs and metadata

exercises/practice/anagram/.meta/config.json, exercises/practice/anagram/.meta/tests.toml, exercises/practice/anagram/src/test/java/AnagramTest.java
=> anagram: Sync tests

exercises/practice/tournament/.meta/config.json, exercises/practice/tournament/.meta/tests.toml, exercises/practice/tournament/src/test/java/TournamentTest.java
=> tournament: Sync tests

exercises/concept/log-levels/.meta/design.md
Related [#150](https://github.com/exercism/java-analyzer/issues/150)
After this one I will also update the analyzer to allow the methods to be solved with split
=> Expanding analyzer comment possibilities for log-levels concept exercise

exercises/practice/hello-world/.docs/instructions.append.md
closes [#2786](https://github.com/exercism/java/issues/2786)
The original goal was to update a broken URL, but I also made some other changes to the documentation  to make it easier to understand 
=> Updating hello-world instructions.append

exercises/concept/bird-watcher/.docs/instructions.md
This pull request addresses and corrects several grammatical errors in the instructions.md file. The changes include:
- Fixing incorrect word usage.
- Improving sentence structure for clarity.
These revisions enhance the readability and professionalism of the documentation, ensuring that users can understand the instructions more clearly and accurately.
- Corrected instances of incorrect word usage.
These changes are purely editorial and do not affect the functionality of the codebase. The updates are intended to improve the overall quality and readability of the documentation.
---
=> changed some grammatical errors in instructions.md

exercises/concept/football-match-reports/.docs/instructions.md
I made a small change. Merge it if you fond is necessary.
---
=> Updated instructions.md in Football Match Reports

exercises/concept/salary-calculator/.docs/instructions.md
I made a simple change. Merge the change if you find it necessary.
---
=> Updated instructions.md in Salary Calculator

exercises/concept/elons-toy-car/.docs/hints.md
Changed a word which gives a correct hint to the students about the problem.
---
=> Updated hints.md in the elons-toy-car

config.json
Forum:
https://forum.exercism.org/t/java-cook-your-lasagna-inconsistent-capitalization/12188
---
=> Cook your lasagna update to title-case

exercises/practice/secret-handshake/.meta/config.json
Previously, it was listed as an "editor" file, which makes the file "read only" (i.e. students are not allowed to modify this file). But this contradicts our mentoring notes, which encourage students to make changes. Moving to "solution" allows students to make modifications.
Config.json docs: https://exercism.org/docs/building/tracks/config-json
Mentoring notes: https://github.com/exercism/website-copy/blob/main/tracks/java/exercises/secret-handshake/mentoring.md
Fixes #2824
---
=> Move Signal.java to "solution" file in Secret Handshake

concepts/bit-manipulation/about.md, concepts/bit-manipulation/introduction.md
- remove the same typo from `about.md` and `introduction.md`
---
=> Fix typo in bit manipulation

exercises/concept/need-for-speed/.docs/instructions.md
This is to reflect the changes from 4dc67688, where the preferred solution was changed to NOT call this method.
This is for exercism/java-analyzer#216
---
=> Remove distanceDriven from Need for Speed examples

exercises/practice/satellite/src/test/java/TreeTest.java
This test was missing the @disabled annotation, to make all the exercises consistent it was added.
---
=> fix: Added @Disabled annotation

exercises/practice/complex-numbers/.meta/config.json
This PR adds my name to the contributors list following my recent contribution to the Java track. My contribution includes improvements and refinements to the [Complex Number exercise](https://github.com/exercism/java/pull/2852), where I contributed to changing some methods in reference answers and in the boiler code for starting the exercise. Thank you for reviewing and considering my addition to the list of contributors!
---
=> Adding contributor for Complex-Number exercise

exercises/practice/yacht/.meta/config.json
This PR addresses the issue raised by the maintainer, @kahgoh, regarding syncing the test cases for yacht exercise and updating them accordingly. Although the tests were already in sync, there were minor changes in the metadata (`meta.md` files) which are being synced in this update.
The issue was raised by @kahgoh regarding syncing of the test cases. You can view the issue [here](https://github.com/exercism/java/issues/2862).
To confirm that everything else was already synced, please see the following screenshot of the successful sync process:
---
=> Sync Yacht with problem-specification

exercises/concept/annalyns-infiltration/.docs/instructions.md, exercises/concept/annalyns-infiltration/.docs/introduction.md
* Formatting into one sentence per line
* Various grammar fixes, such as splitting overly long sentences into two, using American spelling, and rewording to improve readability, consistency, and clarity
---
=> annalyns-infiltration: Grammar fixes

exercises/practice/pig-latin/.meta/config.json, exercises/practice/pig-latin/.meta/tests.toml, exercises/practice/pig-latin/src/test/java/PigLatinTranslatorTest.java
Added a missing test case to align with `problem-specifications`. Checkstyle and all tests passed locally.
---
=> Updating tests for "Pig Latin" exercism

exercises/practice/affine-cipher/.docs/instructions.md, exercises/practice/atbash-cipher/.docs/instructions.md, exercises/practice/atbash-cipher/.meta/config.json, exercises/practice/change/.docs/instructions.md, exercises/practice/change/.docs/introduction.md, exercises/practice/collatz-conjecture/.docs/instructions.md, exercises/practice/collatz-conjecture/.docs/introduction.md, exercises/practice/collatz-conjecture/.meta/config.json, exercises/practice/dominoes/.docs/instructions.md, exercises/practice/dominoes/.docs/introduction.md, exercises/practice/eliuds-eggs/.docs/introduction.md, exercises/practice/grade-school/.docs/instructions.md, exercises/practice/hamming/.docs/instructions.md, exercises/practice/hamming/.docs/introduction.md, exercises/practice/knapsack/.docs/instructions.md, exercises/practice/knapsack/.docs/introduction.md, exercises/practice/luhn/.docs/instructions.md, exercises/practice/luhn/.docs/introduction.md, exercises/practice/pascals-triangle/.docs/introduction.md, exercises/practice/phone-number/.docs/introduction.md, exercises/practice/pythagorean-triplet/.docs/instructions.md, exercises/practice/pythagorean-triplet/.docs/introduction.md
This PR syncs` filepaths`, `metadata` & `docs` with the `problem-specification` repository!
```
.\bin\configlet.exe sync --filepaths --metadata --docs -u
Updating cached 'problem-specifications' data...
Checking exercises...
Every exercise has up-to-date docs!
Every exercise has up-to-date filepaths!
Every exercise has up-to-date metadata!
```
---
=> Syncing docs, filepaths and metadata with problem-specification repo

exercises/practice/parallel-letter-frequency/src/test/java/ParallelLetterFrequencyTest.java
=> Fix typo in test

exercises/concept/cars-assemble/.docs/instructions.md
As discussion in the forum: https://forum.exercism.org/t/cars-assemble-exercise-java/15229
the function naming the cars assemble exercise is a little unfortunate, as it doesn't indicate that task one should return working cars, but only produced cars. 
Changing the function name in the exercise, will break ~11K solutions, so I suggest to extend the note, to help the users get this right.
---
=> Update cars-assemble tasks description

exercises/concept/international-calling-connoisseur/.meta/config.json, exercises/practice/affine-cipher/.docs/instructions.md, exercises/practice/anagram/.docs/instructions.md, exercises/practice/grains/.docs/instructions.md, exercises/practice/grains/.docs/introduction.md, exercises/practice/grains/.meta/config.json, exercises/practice/leap/.meta/config.json, exercises/practice/rna-transcription/.meta/config.json, exercises/practice/say/.meta/config.json, exercises/practice/sieve/.docs/instructions.md, exercises/practice/simple-cipher/.docs/instructions.md
This PR updates the documentation, filepaths, and metadata for all exercises to align with the latest changes from the [problem-specifications](https://github.com/exercism/problem-specifications) repository.  
```sh
PS C:\Programming\Exercism\java> ./bin/configlet.exe sync  
Updating cached 'problem-specifications' data...  
Checking exercises...  
Every exercise has up-to-date docs, filepaths, metadata, and tests! 
```
---
=> Sync docs, filepaths, and metadata with problem-specifications 

exercises/practice/leap/.meta/design.md
This is associated with this [PR](https://github.com/exercism/java-analyzer/pull/260) on the [analyzer repo](https://github.com/exercism/java-analyzer).
---
=> updating design.md for leap analyzer

exercises/practice/binary-search-tree/.docs/instructions.md, exercises/practice/dot-dsl/.docs/instructions.md, exercises/practice/eliuds-eggs/.docs/introduction.md, exercises/practice/luhn/.docs/instructions.md, exercises/practice/luhn/.docs/introduction.md, exercises/practice/meetup/.docs/instructions.md, exercises/practice/phone-number/.docs/instructions.md, exercises/practice/saddle-points/.docs/instructions.md, exercises/practice/simple-cipher/.docs/instructions.md
Sync docs to fix linting errors!
---
=> Syncing-docs-to-address-linting-errors

exercises/concept/bird-watcher/src/test/java/BirdWatcherTest.java
- Added a test to validate the behavior of `hasDayWithoutBirds` when the last day has zero visits. 
- Updated the `lastWeek` field to be final and align with best practices.
https://forum.exercism.org/t/bird-watcher-in-java-should-we-add-a-test-case/17933
---
=> Add test for `hasDayWithoutBirds` method

.github/workflows/java.yml, .github/workflows/markdown.yml
http://forum.exercism.org/t/github-actions-runner-breaking-changes-announced/12612/10
=> ci uses ubuntu-24.04

exercises/practice/change/.approaches/config.json, exercises/practice/change/.approaches/introduction.md
=> Adding approach link
